### ISSUE TITLE
已经在使用，效果非常好，想问在Linux上如何运行

### ISSUE THREAD

**Issue by Jortana** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#10]
买了个树莓派，想在上面长期自动运行，但是我下载后不知道如何运行，望有人解答

**Comment by kalike23** [comment]
跟你一样 待解答

**Comment by noway2014** [comment]
等待，应该怎么运行呢？运行后在一个网页学习界面没有动静了

**Comment by Fxxk-XueXiQiangGuo** [comment]
1. 需要在树莓派上安装一个桌面操作系统（程序需要控制程序内置的Chromium浏览器），[使用VNC](shumeipai.nxez.com/2013/09/04/login-rpi-with-vnc.html)或者直接连接键盘鼠标和显示器控制树莓派
2. 下载[树莓派版](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/raw/master/Fuck%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD-raspberrypi.zip)并解压
3. 在使用前为程序添加可执行权限: `chmod +x Fuck学习强国`
4. 打开程序

**Comment by noway2014** [comment]
如果树莓派连接显示器，运行软件并登陆，是不是还要手机来扫描屏幕的二维码才可以？
如果手机直接命令行树莓派运行软件，那不是无法扫描二维码了？

**Comment by kalike23** [comment]
用vnc连接树莓派 然后运行 然后扫描二维码登录

**Comment by noway2014** [comment]
楼上说的vnc连接树莓派，是pc上运行vnc还是安卓手机运行vnc？

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 楼上说的vnc连接树莓派，是pc上运行vnc还是安卓手机运行vnc？

在树莓派上运行vnc服务端，客户端设备随意

**Comment by Jortana** [comment]
已经完美运行
