### ISSUE TITLE
一帮精神太监让让技术不应该夹杂政治。可当某人用政治肆无忌惮迫害技术的时候你们去了哪儿？

### ISSUE THREAD

**Issue by g101418** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#100]

**Comment by jvbaocn** [comment]
美国利用政治肆无忌惮迫害我国技术公司华为中兴的时候你们去哪里了？

**Comment by listar2000** [comment]
@jvbaocn 哈哈一看到提“迫害”华为中兴的睿智真的笑掉大牙。华为都能叫被“迫害”，那Google/FB/Youtube被墙算啥？双标玩的真溜

**Comment by jvbaocn** [comment]
@listar2000 谷歌拒绝删除危害我国和平稳定的反动言论，甚至纵容他们传播！华为传播反动言论了吗？？

**Comment by soulofc** [comment]
NSA搞监听是为了防止恐怖分子伤害本国国民，而某国监控主要目的是为了防止民间讨论高层腐败、社会不公甚至争取民主。一个是为了保护国民，一个是为了高层的统治压迫国民。

**Comment by jvbaocn** [comment]
> NSA搞监听是为了防止恐怖分子伤害本国国民

那么美国窃听欧洲各国领导人是为了啥？难道欧洲各国领导人都是潜在恐怖分子吗？？那么美国领导人如果是潜在恐怖分子该咋办？？凭啥美国领导人就该知道世界上所有机密，宁有种乎？？
