### ISSUE TITLE
小粉红都是苦孩子( 刘荻)

### ISSUE THREAD

**Issue by sizukari** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#104]
最近，哈佛大学生珍妮弗·潘（Jennifer Pan）和麻省理工大学博士生Yiqing Xu联合发表了论文《中国的意识形态光谱》（《China’s Ideological Spectrum》），采用数据分析的方法，描绘出中国各省市的“意识形态性格”。

两位作者一共分析了171830个调查样本。样本来源于一套许多人并不陌生的“中国政治坐标系测试”，这套测试从政治、经济和文化三个维度设置了50道选择题（如“西方的多党制不适合中国国情”、“即使有人口压力，国家和社会也无权干涉个人要不要孩子，要几个孩子”），参与者可以选择“强烈反对、反对、强烈同意、同意”。根据结果，判断参与者在意识形态上是偏“左”（保守主义）还是偏“右”（自由主义）。2014年，一共有171830位网民参与了测试，他们的答案以及个人信息便是论文的分析材料。

有必要说明的是，根据中国特殊的语境，论文作者将“左”（保守主义）定义为对威权体制、国家统一和安全、社会主义经济政策、传统文化价值的偏好和重视；而“右”（“自由主义”）则被定义为对市场化改革、民主自由、现代科技的认同和提倡。

经过数据分析，哈佛和麻省理工的学生发现，一个地方的现代化水平越高，生活条件越优越，那个地方的人就越认同“自由主义”；反之，现代化水平偏低、人均收入上不去的地区，民众就越表现出对“保守主义”的迷恋。

被划入“自由主义阵营”的地区中，得分最高的依次是上海、广东、浙江，此外还有北京、江苏、福建、海南、山西、湖北、辽宁。与此相反的是“深红”的“保守主义地区”，边远的新疆、贵州和广西占据前三甲，宁夏、河南、江西、湖南、安微、内蒙古、河北紧随其后。“不左不右”的地区是天津、重庆、四川、吉林、甘肃、云南、山东、陕西、黑龙江。

这一研究结果与我的观察大致相符：底层往往拥护体制，而中上层往往对当前的体制有诸多不满，希望变革。很多人以为爱国“小粉红”都是什么红二代富二代，我却认为他们大多来自内地三线以下城市的小市民家庭：去年南海仲裁时，愤青围堵肯德基，通常都是发生在内地城市或者三线以下的城市。有人还撰文指出，愤青之所以只围肯德基不围麦当劳，是因为三线以下的城市一般只有肯德基，没有麦当劳。再往前的侯聚森事件中，参与打架斗殴的“那兔吧”“爱国青年”，大都是些中专技校学生。红二代富二代是不会去上这些学校的。总之，“小粉红”所在的阶层大致属于市民阶层的中下层。比他们更低阶层的孩子连中专技校的教育也没有机会接受，初中毕业甚至没毕业就要去工厂打工，这些人通常没有时间和精力在网上就政治问题发表意见。因此，在经常在互联网上发表意见的人当中，小粉红可以说是比较下层的了。

这样一来就出现了一个问题：人们都说屁股决定脑袋，而现实中发生的事却是，支持变革的往往是当前体制的受益者，而拥护体制的往往是那些没有得到多少好处的人。

当然，肯定有人会说，这没什么好奇怪的：市场经济发达的地方现代化程度高，人们的生活水平也高，这些地方的人们自然也就更支持市场化改革。不过，这似乎还不足以解释为什么这些地方的人们同时也对当前体制更加不满，更加认同自由民主。这种现象并不只是中国才有——美国革命之前，北美殖民地其实是当时世界上最自由平等，老百姓生活最好的地方。

为什么会出现这种“既得利益者反体制”的现象呢？我认为可能有以下几个原因：

第一、社会地位更高、生活更加富裕的人眼界更宽阔，欲望更多，因此也就有更多的不满。而底层往往已经习惯了当前的状况，想象不到还有别的可能性。人们常说“光脚的不怕穿鞋的”，但是面对剧烈变革的时候，底层往往更加脆弱，更容易成为牺牲品，因此他们往往更加害怕变革。

第二、人们通常是自我中心的，往往会把自己的成功归功于天赋和努力，而不是外在环境。那些社会地位更高、生活更加富裕的人通常自我评价更高，他们绝对不会认为自己是沾了体制的光才有了今天的幸福生活。相反，他们通常会认为，自己今天的成功完全是自己应得的，如果换个体制，他们只会生活得更好。

第三、从家庭教育的角度来说，中产阶级家庭中的儿童与父母的关系更加平等，他们从小更加习惯与父母“讨价还价”，争取自己的权利（计划生育政策也加强了这一趋势）。而底层的家庭往往更加权威主义。

总之，通过人们的个人利益来预测他们的政治立场，并不十分靠谱，人们的习惯、知识、心理状态和对现实的解释可能更加重要。利益是暂时的，观点和立场才是长远的。

**Comment by sizukari** [comment]
http://jenpan.com/jen_pan/ideology.pdf

**Comment by jvbaocn** [comment]
光调查网民没意义，挨家挨户问问是不是多数人都支持我党的领导？？！
西方一遍口口声声假惺惺的说不要抛弃低端人口底层人民，一遍又发表这种侮辱底层人民的言论是否双标？？实际上只有我国政府带领1.2亿人脱贫，才是真正给底层带来利益！！

**Comment by chn-lyzhi** [comment]
> 光调查网民没意义，挨家挨户问问是不是多数人都支持我党的领导？？！
> 西方一遍口口声声假惺惺的说不要抛弃低端人口底层人民，一遍又发表这种侮辱底层人民的言论是否双标？？不要被西方误导，西方给我国底层人民什么实际利益了？实际上只有我国政府带领1.2亿人脱贫，才是真正给底层带来实际利益！！

「低端人口」怎么说

**Comment by jvbaocn** [comment]
> 「低端人口」怎么说

我国政府带领底层1.2亿脱贫，西方给我国底层人民带来什么实际利益了？？

**Comment by listar2000** [comment]
@jvbaocn 网评员你好，工作辛苦了

**Comment by navono** [comment]
@jvbaocn 上个世纪的疫苗谁援助你的？WTO是谁支持你国进入的？没长眼的白眼狼。

**Comment by PLQin** [comment]
这是五分党的聚集地 ? 

有个别人的言论我实在看不顺眼 : 

@navono `你国` ?  外国国籍吗 ? 
用着汉字说一下无脑的话, 什么叫做 `支持? 白眼狼` , 全是利益/条件 交换得来的好吧 ;


然后作者 ,  多有点自己的判断
@sizukari 什么叫做 `既得利益者反体制` , 你以为北上广的小白领, 炒房卖房是 `既得利益者` 吗 ?
大企业家 , 政府当权者才是 !
