### ISSUE TITLE
技术人员是自由派居多吗？

### ISSUE THREAD

**Issue by mxvlgrz** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#108]
似乎在热衷技术的人群里，小粉红的比例，比同一位面学历能力相似的其他人群中，少很多很多
这是为什么捏

**Comment by jvbaocn** [comment]
看看这人，真的是自由派吗？为什么把我禁言了呢？？


![jinya](https://user-images.githubusercontent.com/48293959/54070325-5ed5a500-4299-11e9-8876-a91505468e41.jpg)

> 根据社会契约论，国家的一切权利属于我们公民所有。

@wenfeng0218 还啥契约论，西方提个论点你就信？
我们的观点是地球的一切权利属于我们每个地球人所有，然而美国人占了过多的资源！还想侵占我们的资源！！所以我们就要怼美国。
