### ISSUE TITLE
有些人辩论不过我，就会禁言拉黑，为什么有人会相信这种人上台了就会给我们言论自由？

### ISSUE THREAD

**Issue by jvbaocn** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#109]
看到这个issue #97 种有些言论不能认同，想要辩论，居然发现被那个人偷偷禁言了。

![jinya](https://user-images.githubusercontent.com/48293959/54070504-b8d76a00-429b-11e9-8024-1ea3ee244d8b.jpg)

> 根据社会契约论，国家的一切权利属于我们公民所有。

还什么社会契约论，西方提个论点就是真理吗？
那些人跳不出步步跟随西方的思维定势，他们说国家就认定是国家了，难道就看不到更大的地球村的范围？？
记住真理永远在导弹的射程之内。我们的真理就是地球村的一切权利属于我们每个地球人所有，然而美国人占了过多的资源！还想侵占我们的资源！！所以我们就要团结起来对抗美国！！

**Comment by mxvlgrz** [comment]
谁来告诉我一下 这个人是反串还是认真的…

**Comment by Mark9804** [comment]
你有你说话的权利，我也有不听的权利。权力对等。

**Comment by Uptobillion** [comment]
1.这个人主动碰瓷 可能是希望这个项目消失
2.issue建议关闭 项目归属于 @Fxxk-XueXiQiangGuo 的 你有处置此项目的权力

另外：issue这个功能不要有了 弊大于利

**Comment by caryle** [comment]
这人是认真的，被洗脑多了

**Comment by fenglipop29** [comment]
为啥这软件下面的issue全是一些不相干的内容啊？大家讨论下学习强国软件也好啊，非得搞这些斗嘴有意思么？

**Comment by bes165** [comment]
好了好了不要說了。關掉issue改成pr反饋算了。

**Comment by AngelFalse** [comment]
所以我们甚至不能拉黑我们看不惯的脑残，所以我们甚至连GitHub应许给我们的权利都没有。
精彩，实在精彩。
