### ISSUE TITLE
每天都要扫描一下么

### ISSUE THREAD

**Issue by jwc19890114** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#11]
能不能常驻后台，扫描一次以后就不用处理了

**Comment by ads1356** [comment]
开个云主机一直运行

**Comment by noway2014** [comment]
这个程序如何使用的呢？

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 这个程序如何使用的呢？

扫码登录之后放在后台运行就可以了

**Comment by jwc19890114** [comment]
> > 这个程序如何使用的呢？
> 
> 扫码登录之后放在后台运行就可以了

很感谢了，这个app我一直没下载，就是不想每天刷

**Comment by lgxnas** [comment]
> > 这个程序如何使用的呢？
> 
> 扫码登录之后放在后台运行就可以了

请问扫码后是保存cookies吗？有时限吗？是否运行一段时间后需要再次扫码？

**Comment by Fxxk-XueXiQiangGuo** [comment]
是保存cookies。cookie的寿命是6个小时，所以6个小时之后需要再次扫码。预计在下一个版本中能够永久保存cookies，只需要扫一次码。但最近很忙，不知道要等到什么时候了。

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 是保存cookies。cookie的寿命是6个小时，所以6个小时之后需要再次扫码。预计在下一个版本中能够永久保存cookies，只需要扫一次码。但最近很忙，不知道要等到什么时候了。

已经解决。
