### ISSUE TITLE
issue不要有了 全都close吧

### ISSUE THREAD

**Issue by Uptobillion** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#110]
1.这个人jvbaocn  主动碰瓷 可能是希望这个项目消失
2.issue建议关闭 整个项目都是你的 @Fxxk-XueXiQiangGuo  它不属于公共资源 你有权力这么做
3.开水烫人 但晾凉了就不烫了... 我们需要做的就是不理不睬 让其所有的发言都发到黑洞里

**Comment by jvbaocn** [comment]
这种违法软件伤害多数正常用户的利益凭啥不该消失？我们说两句正义的话就看不惯了，就要给给删了？还有人会相信你们上台了就能给人民带来言论自由吗？

没关系反正依据备份了  https://archive.is/ybNVi
