### ISSUE TITLE
针对使用Fuck-XueXiQiangGuo学习强国刷分软件作弊的人士的最后通牒！

### ISSUE THREAD

**Issue by yuye2133** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#132]
吓得我要取关了。。
https://medium.com/@jvbaoillegal/%E9%92%88%E5%AF%B9%E4%BD%BF%E7%94%A8fuck-xuexiqiangguo%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD%E5%88%B7%E5%88%86%E8%BD%AF%E4%BB%B6%E4%BD%9C%E5%BC%8A%E7%9A%84%E4%BA%BA%E5%A3%AB%E7%9A%84%E6%9C%80%E5%90%8E%E9%80%9A%E7%89%92-a98ccd6018e6#--respond

**Comment by Fxxk-XueXiQiangGuo** [comment]
不用理 jvbaocn ，很多人是把他当猴子看的。

**Comment by tangerinepeel** [comment]
现在是没法用了吗？点击主程序没反应
小白一枚
