### ISSUE TITLE
可以用安卓termux跑吗

### ISSUE THREAD

**Issue by poemsiu** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#133]
如题，可以在安卓上用termux跑吗？

**Comment by Fxxk-XueXiQiangGuo** [comment]
理论上是可以使用树莓派版 (armv7l) 在安卓手机上运行的，但是需要解决依赖安装问题。

**Comment by AngelFalse** [comment]
所有引用的库都得静态编译进去，现有的版本我觉得大概不行。树莓派的系统是比较标准的linux系统，而安卓不是。

**Comment by poemsiu** [comment]
@Fxxk-XueXiQiangGuo 跑树莓派版本的话可以退出界面放在后台跑吗

**Comment by kchen0x** [comment]
你直接 tmux 或者 screen 创建一个 session，--headless 运行起来之后，关掉 terminal 就可以了。不需要界面，也不需要什么桌面。后台安安静静刷分就行了。
