### ISSUE TITLE
这个软件会检测今日分数吗，今天学完了，我登录上去不会动了，是不是设置好的

### ISSUE THREAD

**Issue by Tasukawin1** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#134]

**Comment by Alivon** [comment]
I wrote a program that can be done on a daily basis points, can have a try, project address is https://github.com/Alivon/Panda-Learning
Welcome to use it
熊猫/学习/强国

**Comment by Fxxk-XueXiQiangGuo** [comment]
是设置好的，会检测今日各项得分情况，刷满就不会继续刷分了。
