### ISSUE TITLE
解决重复文章视频不加分问题，多线程加速学习，欢迎尝试使用Panda-learning熊猫/学习/强国

### ISSUE THREAD

**Issue by Alivon** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#135]
hi guys  I wrote a program that can be done on a daily basis points, can have a try, project address is https://github.com/Alivon/Panda-Learning
Welcome to use it
解决重复文章/视频不得分问题
支持线程加快学习效率
支持多用户同时学习
熊猫/学习/强国

**Comment by baoang** [comment]
> hi guys I wrote a program that can be done on a daily basis points, can have a try, project address is https://github.com/Alivon/Panda-Learning
> Welcome to use it
> 解决重复文章/视频不得分问题
> 支持线程加快学习效率
> 支持多用户同时学习
> 熊猫/学习/强国

应当有LINUX版本，这样通过一台VPS可实现“挂机”且同时为多个账户服务，也就是说，一台VPS解决一个部门党员的挣分问题。

**Comment by Alivon** [comment]
> > hi guys I wrote a program that can be done on a daily basis points, can have a try, project address is https://github.com/Alivon/Panda-Learning
> > Welcome to use it
> > 解决重复文章/视频不得分问题
> > 支持线程加快学习效率
> > 支持多用户同时学习
> > 熊猫/学习/强国
> 
> 应当有LINUX版本，这样通过一台VPS可实现“挂机”且同时为多个账户服务，也就是说，一台VPS解决一个部门党员的挣分问题。

我当前电脑没有装linux 所以暂时没有发布linux版本，若有多人需要使用我可以下载linux一个分发程序，服务器挂载可以实现，只是现在手中有其他任务，我的想法是直接做成手机端自动学习，智能答题。过一阵子时间允许开发。

**Comment by YeBing000** [comment]
> > > hi guys I wrote a program that can be done on a daily basis points, can have a try, project address is https://github.com/Alivon/Panda-Learning
> > > Welcome to use it
> > > 解决重复文章/视频不得分问题
> > > 支持线程加快学习效率
> > > 支持多用户同时学习
> > > 熊猫/学习/强国
> > 
> > 
> > 应当有LINUX版本，这样通过一台VPS可实现“挂机”且同时为多个账户服务，也就是说，一台VPS解决一个部门党员的挣分问题。
> 
> 我当前电脑没有装linux 所以暂时没有发布linux版本，若有多人需要使用我可以下载linux一个分发程序，服务器挂载可以实现，只是现在手中有其他任务，我的想法是直接做成手机端自动学习，智能答题。过一阵子时间允许开发。

请问什么时候能解决挂载在VPS上的批量刷分工具呢？

**Comment by Alivon** [comment]
> > > > hi guys I wrote a program that can be done on a daily basis points, can have a try, project address is https://github.com/Alivon/Panda-Learning
> > > > Welcome to use it
> > > > 解决重复文章/视频不得分问题
> > > > 支持线程加快学习效率
> > > > 支持多用户同时学习
> > > > 熊猫/学习/强国
> > > 
> > > 
> > > 应当有LINUX版本，这样通过一台VPS可实现“挂机”且同时为多个账户服务，也就是说，一台VPS解决一个部门党员的挣分问题。
> > 
> > 
> > 我当前电脑没有装linux 所以暂时没有发布linux版本，若有多人需要使用我可以下载linux一个分发程序，服务器挂载可以实现，只是现在手中有其他任务，我的想法是直接做成手机端自动学习，智能答题。过一阵子时间允许开发。
> 
> 请问什么时候能解决挂载在VPS上的批量刷分工具呢？

欢迎可以在Panda-learning项目下留言，近期我有其他项目在做，暂时抽不开精力做vps版本，此版本应该能解决日常使用，等我忙完一段时间之后我会评估开发Panda-Learning 手机app版本还是vps版本

**Comment by gantrylueng** [comment]
越来越牛X的感觉了。但是还是要安全为上的，刷分要不能被清空，否则白搞了。
反正手机上自动学习，就没有必要加速了吧

**Comment by afboyxiyang** [comment]
现在pc版也可以答题了！

**Comment by ec000** [comment]
用docker部署就可以实现多用户同时刷分

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 用docker部署就可以实现多用户同时刷分

现在程序已原生支持[多用户模式](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#040---2019-03-13)，可以使用 `--multi-user` 命令行选项启用。

```
./Fuck学习强国 --multi-user
```

**Comment by Alivon** [comment]
> 用docker部署就可以实现多用户同时刷分

window下面可以多开程序多用户同时学习
https://github.com/Alivon/Panda-Learning 请品尝

**Comment by whhxmwhh** [comment]
熊猫的用不了

**Comment by Fxxk-XueXiQiangGuo** [comment]
> window下面可以多开程序多用户同时学习
> https://github.com/Alivon/Panda-Learning 请品尝

多用户模式 Windows 下也可以使用。

[已经](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#042---2019-03-13)可以直接正常打开程序，多开时自动使用多用户模式。

**Comment by lgxnas** [comment]
多线程学习会不会被人机识别,安全第一

**Comment by Alivon** [comment]
今天进行了更新，开放源码，解决活跃时间和用户app和熊猫学习一起使用的冲突问题

**Comment by Alivon** [comment]
> 今天进行了更新，开放源码，解决活跃时间和用户app和熊猫学习一起使用的冲突问题
项目地址
https://github.com/Alivon/Panda-Learning

**Comment by summym** [comment]
> > 今天进行了更新，开放源码，解决活跃时间和用户app和熊猫学习一起使用的冲突问题
> > 项目地址
> > https://github.com/Alivon/Panda-Learning
winmm.dll的问题怎么解释
https://www.virustotal.com/#/file/60f1cbab9b30bb9013b006cd714e4ceddca40f576050dc867d4510d0044fe7ae/detection

**Comment by Alivon** [comment]
> 熊猫的用不了

已更新32位系统支持，请尝试

**Comment by Alivon** [comment]
> > > 今天进行了更新，开放源码，解决活跃时间和用户app和熊猫学习一起使用的冲突问题
> > > 项目地址
> > > https://github.com/Alivon/Panda-Learning
> > > winmm.dll的问题怎么解释
> > > https://www.virustotal.com/#/file/60f1cbab9b30bb9013b006cd714e4ceddca40f576050dc867d4510d0044fe7ae/detection

项目开源，并不存在病毒

**Comment by summym** [comment]
> > > > 今天进行了更新，开放源码，解决活跃时间和用户app和熊猫学习一起使用的冲突问题
> > > > 项目地址
> > > > https://github.com/Alivon/Panda-Learning
> > > > winmm.dll的问题怎么解释
> > > > https://www.virustotal.com/#/file/60f1cbab9b30bb9013b006cd714e4ceddca40f576050dc867d4510d0044fe7ae/detection
> > > > 谢提醒
> > > > 项目开源，并不存在病毒，winmm.dll 为绿化chrome浏览器而产生的，来源于greenchrome  地址：https://shuax.com/project/greenchrome/ 可以查证
> > > > 我忘记删除  绝无病毒。
建议用MyChrome作为绿化浏览器，起码可以用官方安装包直接绿化
https://github.com/cnjackchen/my-chrome

**Comment by Alivon** [comment]
> > > > > 今天进行了更新，开放源码，解决活跃时间和用户app和熊猫学习一起使用的冲突问题
> > > > > 项目地址
> > > > > https://github.com/Alivon/Panda-Learning
> > > > > winmm.dll的问题怎么解释
> > > > > https://www.virustotal.com/#/file/60f1cbab9b30bb9013b006cd714e4ceddca40f576050dc867d4510d0044fe7ae/detection
> > > > > 谢提醒
> > > > > 项目开源，并不存在病毒，winmm.dll 为绿化chrome浏览器而产生的，来源于greenchrome  地址：https://shuax.com/project/greenchrome/ 可以查证
> > > > > 我忘记删除  绝无病毒。
> > > > > 建议用MyChrome作为绿化浏览器，起码可以用官方安装包直接绿化
> > > > > https://github.com/cnjackchen/my-chrome

thanks，当时也看了Mychrome 觉得麻烦一点点，打包chrome只是针对windows下很多用户动手能力弱，不然就不用把chrome也打包进来了，新版还特别大。

**Comment by cz1980** [comment]
原理是不是模拟打开多个浏览器同时学习啊？

**Comment by NATO2000** [comment]
建议这个软件开发安卓客户端 用来自动答题、分享之类的
