### ISSUE TITLE
cannot open display:

### ISSUE THREAD

**Issue by MQL9011** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#136]
Ubuntu 服务器上运行，第一次运行还好好的， 后面再运行就报这个错。请大佬帮忙看看。

![image](https://user-images.githubusercontent.com/11871158/54203852-ffcc9600-450d-11e9-8137-09e6b7c01301.png)

**Comment by hongyuatcufe** [comment]
是不是因为加了headless参数？

**Comment by GZQ369** [comment]
没有安装好依赖

**Comment by yu-liang-zheng** [comment]
碰到了同样的问题， 麻烦@MQL9011 指教指教怎么处理

**Comment by MQL9011** [comment]
@yu-liang-zheng  暂时没有处理，抱歉
