### ISSUE TITLE
突然想到

### ISSUE THREAD

**Issue by AngelFalse** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#138]
作为反检测的一部分，是否考虑加装一些插件（如chrome-ua-switcher），从而进一步减小被检测出的可能？毕竟（在运营看起来）突然有一大堆人拿着**同一个版本的chrome**刷刷刷，还是很显眼的。
或者说，允许在启动时选择用Firefox还是chromium？

**Comment by emutau** [comment]
现在有多少人用？感觉相比于整个中国的基数，还是可以忽略吧

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已支持使用自定义 User Agent 运行](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#042---2019-03-13)，
使用 `--ua=<user_agent>` 命令行选项：
```
./Fuck学习强国 --ua="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0"
```
