### ISSUE TITLE
界面一片空白

### ISSUE THREAD

**Issue by 1234567890123467** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#148]
软件刷分完关闭后再打开总是白板，一片空白，怀疑是不是cookie的问题，或者是无法从网站处获取登陆所需二维码。

重启windows可以解决这一问题，但有没有什么清除缓存的办法？或者其他解决方案？

**Comment by 1234567890123467** [comment]
找到原因了，是因为代理，抱歉，打扰了。

**Comment by lizhao628** [comment]
如何解决？
