### ISSUE TITLE
在窗口最上方显示目前刷了多少分

### ISSUE THREAD

**Issue by Fxxk-XueXiQiangGuo** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#15]
建议在窗口最下方显示目前刷了多少分。

_Originally posted by @XueTeng2 in https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/issues/5#issuecomment-468523089_

**Comment by Steven-nagisa-Y** [comment]
支持这个想法

**Comment by seseshenqiu** [comment]
确实需要

**Comment by dzenhuoechian** [comment]
144

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经支持](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#060---2019-03-30)。
