### ISSUE TITLE
技术无罪，但希望大佬起的项目名不要这么搞事。

### ISSUE THREAD

**Issue by GitZinc** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#161]
我们倒是没有硬性要求学习积分，可能地铁上无聊看一看，既填补了一些碎片时间，还能看些新闻。不过这个项目对于有硬性要求的一些工作党来说还是挺好的，学习应该是凭自己意愿的，这样量化要求下的学习会适得其反。不过大佬的项目名称有点搞，改成Love-XueXiQiangGuo之类的（滑稽）这样比较和谐。没必要起个名这么刚，容易激起issue区和项目无关的讨论，还是希望Gayhub能纯粹一点。

**Comment by dsoiew** [comment]
赞同。的确是更好的策略。

**Comment by AngelFalse** [comment]
同意，但是Love-xuexiqiangguo已经被占了，还是这个项目的clone

**Comment by GitZinc** [comment]
> 同意，但是Love-xuexiqiangguo已经被占了，还是这个项目的clone

正面形容词还挺多的嘛，随便找一个）

**Comment by xuexiqiangguo2019** [comment]
同意您的几个观点：
学习应该是凭自己意愿的。强迫的效果极差，甚至反倒引发憎恶。
issue区最好不要讨论与项目本身无关的。给作者和用者带来不必要的附带政治风险。

但是“love”才是很搞，心里不喜欢，嘴上还love，这人格得有多扭曲啊？说到底项目起名是作者的权利，意见阐述情绪表达都是公民的自由。

**Comment by youyinnn** [comment]
help不多好？非要用f word- -
hub如果被墙的话，始终有你一份愚力

**Comment by GitZinc** [comment]
> help不多好？非要用f word- -
> hub如果被墙的话，始终有你一份愚力

是这样的，不知道跟我讲“明明心里很厌恶却还要Love更搞”的人是怎么想的，能屈能伸活着不好吗？又不是美帝想F总统就F总统，口无遮拦也有个限度，真的不要觉得自己这么做很Real。

**Comment by xuexiqiangguo2019** [comment]
项目作者fuck的是那个强制学习的app，而不是领导人。而美帝究竟能否fuck trump？只要google搜索一下不就知道了？何必臆测呢？https://www.youtube.com/watch?v=1zNr8Pf1QkY

**Comment by baoang** [comment]
> 
> 
> help不多好？非要用f word- -
> hub如果被墙的话，始终有你一份愚力

hub当初被封的时候，还没有作者的这个软件呢。
软件的这个名字不重要，因为即便是改成“更和谐”的，也不会改变其态度和性质。
推特被禁止，不是因为其名字，改成推不特，也一样被封，同样的，“脸书”改成“不要脸的书”也不会得到进入中国大陆的许可。既然如此，小羊喝不喝水，都不影响狼眼中对河水被污染的结论，还是任着作者的意愿吧。
能屈能伸应当在墙内，出了墙还要禁声，那么不如在大陆的网站上建立个和谐的repo。何况，屈着屈着，可能就不知道腿伸直了是什么感觉了。

**Comment by emutau** [comment]
1.技术无罪这个本事就是错的：中共开发的GWF就是罪过，这个学习app就是罪过！
2.项目发起人想 fuck就是fuck，关你吊事
3.  github被封与否无作者没有半点关系，难道犹太人被纳粹杀了，要归因于犹太人钱多？

Do not be evil =不要做道德警察

**Comment by GitZinc** [comment]
> 1.技术无罪这个本事就是错的：中共开发的GWF就是罪过，这个学习app就是罪过！
> 2.项目发起人想 fuck就是fuck，关你吊事
> 3. github被封与否无作者没有半点关系，难道犹太人被纳粹杀了，要归因于犹太人钱多？
> 
> Do not be evil =不要做道德警察

1、起这个项目名就容易引发政治讨论，我也对于在github里讨论政治感到恶心。
2、这个app我没看出来哪有错误，倒不如说第一次见到官方出的App能做的这么精致的，像是找的外包。里面的新闻质量也都不错，紧跟时事，我甚至还看到了流浪地球。要说错，也是强制要求每周达到指标的人的错。
3、上来嘴就这么臭，你也属实是来恶心len的。少在这偷换概念，有钱和涉及到政治敏感的项目里放F word是一回事？不会说话就看看楼上是怎么讨论的。
4、F word可以，我自己写码写的烦也喜欢给代码起名带F word，但是放到git上，还是比较敏感的方面，用F word完全没必要。

**Comment by emutau** [comment]
1. 学习app本来就是政治问题，有什么好逃避的。想吃屎还想吃得优雅，就是好好学习去，这是给不想的。你对政治恶心，我还对你恶心，我能要求github封了你的账号吗？
2. 看你就是喜欢吃屎呗
3. 这个app的目的是什么？不就是包子要搞个人崇拜，学点历史，看看从建国到腊肉死了，多少人死于腊肉之手
4. 有没有必要不是你说的算。就是没有必要，但是developer就是放这里，怎么了。还是那句话：不要做道德警察 +  fuck包子

**Comment by hongyuatcufe** [comment]
> > 1.技术无罪这个本事就是错的：中共开发的GWF就是罪过，这个学习app就是罪过！
> > 2.项目发起人想 fuck就是fuck，关你吊事
> > 3. github被封与否无作者没有半点关系，难道犹太人被纳粹杀了，要归因于犹太人钱多？
> > Do not be evil =不要做道德警察
> 
> 1、起这个项目名就容易引发政治讨论，我也对于在github里讨论政治感到恶心。
> 2、这个app我没看出来哪有错误，倒不如说第一次见到官方出的App能做的这么精致的，像是找的外包。里面的新闻质量也都不错，紧跟时事，我甚至还看到了流浪地球。要说错，也是强制要求每周达到指标的人的错。
> 3、上来嘴就这么臭，你也属实是来恶心len的。少在这偷换概念，有钱和涉及到政治敏感的项目里放F word是一回事？不会说话就看看楼上是怎么讨论的。
> 4、F word可以，我自己写码写的烦也喜欢给代码起名带F word，但是放到git上，还是比较敏感的方面，用F word完全没必要。

唉，developer爱起什么名字是人家的事，想要love的可以自己clone改一下啊，反正不管改成啥样，早晚都一样会被封，被强制学习已经够糟糕了，连developer表达下不满都不行哦

**Comment by GitZinc** [comment]
> 1. 学习app本来就是政治问题，有什么好逃避的。想吃屎还想吃得优雅，就是好好学习去，这是给不想的。你对政治恶心，我还对你恶心，我能要求github封了你的账号吗？
> 2. 看你就是喜欢吃屎呗
> 3. 这个app的目的是什么？不就是包子要搞个人崇拜，学点历史，看看从建国到腊肉死了，多少人死于腊肉之手
> 4. 有没有必要不是你说的算。就是没有必要，但是developer就是放这里，怎么了。还是那句话：不要做道德警察 +  fuck包子

我的意思只是说这么做可以让issue区安静一点，作者也开投票问要不要关闭政治敏感的issue，能不能不要老是代表别人，你又懂developer想什么了？满口道德警察，不会好好说人话就爬，还纳粹杀犹太人，有你🐴在我把你🐴杀了，脑残东西。

**Comment by GitZinc** [comment]
> > > 1.技术无罪这个本事就是错的：中共开发的GWF就是罪过，这个学习app就是罪过！
> > > 2.项目发起人想 fuck就是fuck，关你吊事
> > > 3. github被封与否无作者没有半点关系，难道犹太人被纳粹杀了，要归因于犹太人钱多？
> > > Do not be evil =不要做道德警察
> > 
> > 
> > 1、起这个项目名就容易引发政治讨论，我也对于在github里讨论政治感到恶心。
> > 2、这个app我没看出来哪有错误，倒不如说第一次见到官方出的App能做的这么精致的，像是找的外包。里面的新闻质量也都不错，紧跟时事，我甚至还看到了流浪地球。要说错，也是强制要求每周达到指标的人的错。
> > 3、上来嘴就这么臭，你也属实是来恶心len的。少在这偷换概念，有钱和涉及到政治敏感的项目里放F word是一回事？不会说话就看看楼上是怎么讨论的。
> > 4、F word可以，我自己写码写的烦也喜欢给代码起名带F word，但是放到git上，还是比较敏感的方面，用F word完全没必要。
> 
> 唉，developer爱起什么名字是人家的事，想要love的可以自己clone改一下啊，反正不管改成啥样，早晚都一样会被封，被强制学习已经够糟糕了，连developer表达下不满都不行哦

并不是不许发泄，很正常，只是这么做会在issue区引发很多跟项目无关的讨论，没必要，提个建议而已。

**Comment by GitZinc** [comment]
> 1. 学习app本来就是政治问题，有什么好逃避的。想吃屎还想吃得优雅，就是好好学习去，这是给不想的。你对政治恶心，我还对你恶心，我能要求github封了你的账号吗？
> 2. 看你就是喜欢吃屎呗
> 3. 这个app的目的是什么？不就是包子要搞个人崇拜，学点历史，看看从建国到腊肉死了，多少人死于腊肉之手
> 4. 有没有必要不是你说的算。就是没有必要，但是developer就是放这里，怎么了。还是那句话：不要做道德警察 +  fuck包子

弄个注册了6天的小号在这里振振有词给👴整笑了，怂逼赶紧爬出去，少在这恶心人。你妈的正常交流不听非得恰点蜜再跟你说话你才愿意听是不是？

**Comment by GitZinc** [comment]
> 1. 学习app本来就是政治问题，有什么好逃避的。想吃屎还想吃得优雅，就是好好学习去，这是给不想的。你对政治恶心，我还对你恶心，我能要求github封了你的账号吗？
> 2. 看你就是喜欢吃屎呗
> 3. 这个app的目的是什么？不就是包子要搞个人崇拜，学点历史，看看从建国到腊肉死了，多少人死于腊肉之手
> 4. 有没有必要不是你说的算。就是没有必要，但是developer就是放这里，怎么了。还是那句话：不要做道德警察 +  fuck包子

你真的像个非主流傻卵，拿个小号在这无能狂喷，滚回家玩蛋去好吗，来这丢人现眼显你nb了。那么不喜欢China怎么不去美帝自由啊？我寻思你要是在美帝也不用开小号畏畏缩缩的了，说到底还是个喜欢叫的怂逼

**Comment by youyinnn** [comment]
有的人是真的easy

有的人说能屈能伸应该在墙内，现在hub不就是在墙内嘛？hub现在就在墙内，我看你腿能伸直多久
@baoang 

还有的人嘴上说着关你吊事，要求封号，那你倒是用大号啊？我看你到底能多事不关己 @emutau 

说到底我说这句话：
> hub如果被墙的话，始终有你一份愚力

没错吧？没做就接着我的话，don't thing in an easy way

**Comment by baoang** [comment]
这个主题贴挺可惜的；
跑到这儿来的，大多数应当是理工类的人或者至少有一定的理工类的逻辑，却连贴都不看完（也可能是屎吃多了脑子也抽成水糊状的了）就硬要回人贴；
人人都有自由——这句话我看应当不会有人吃饱了撑的要挑根骨头出来“讨论”了吧？那么爱学习的，就自己改个名字不就行了？顺带着去警察局申请改姓赵也可以了。

**Comment by youyinnn** [comment]
@baoang 
1. 明打明告诉您，help和fword完全是两个不一样的态度，无论作者自身是什么态度，他人看到的态度就从你title上体现的，free speech也是要隐晦title的，明着和人刚，我劝着收敛点还有错了，真牛皮；
2. 我请您反驳我这句话啊，您自己的逻辑呢？反驳不了就别再说了，别拿您那上不了台面的文学隐喻来添砖加瓦，没必要
    > 能屈能伸应当在墙内，出了墙还要禁声，那么不如在大陆的网站上建立个和谐的repo。何况，屈着屈着，可能就不知道腿伸直了是什么感觉了。

    您看您这逻辑，能屈能伸在墙内，hub现在不就是在墙内嘛，自己都知道能屈能伸那您在这和我杠个酸萝卜呢？

您逻辑这么差，和周围人相处一定很困难吧？
逻辑没搞懂，就别这么easy mind

**Comment by baoang** [comment]
> 
> 
> @baoang
> 
>     1. 明打明告诉您，help和fword完全是两个不一样的态度，无论作者自身是什么态度，他人看到的态度就从你title上体现的，free speech也是要隐晦title的，明着和人刚，我劝着收敛点还有错了，真牛皮；
> 
>     2. 我请您反驳我这句话啊，您自己的逻辑呢？反驳不了就别再说了，别拿您那上不了台面的文学隐喻来添砖加瓦，没必要
>        > 能屈能伸应当在墙内，出了墙还要禁声，那么不如在大陆的网站上建立个和谐的repo。何况，屈着屈着，可能就不知道腿伸直了是什么感觉了。
>        
>        
>        您看您这逻辑，能屈能伸在墙内，hub现在不就是在墙内嘛，自己都知道能屈能伸那您在这和我杠个酸萝卜呢？
> 
> 
> 您逻辑这么差，和周围人相处一定很困难吧？
> 逻辑没搞懂，就别这么easy mind

1. github不在墙内
2. 我指的是，你连墙内和墙外都没搞清楚
3. 你很强势、你很厉害、我跟周围的人没法相处、逻辑我比你差：这四段全是送给你的
4. 无论是否反驳，我都不再说了，原因见3——这句也是送给你的
5. 墙内和墙外是说话的前提，所以我知道，不能再说了

**Comment by youyinnn** [comment]
@baoang 

自知理亏就别抠字眼了，hub服务器不在大陆，并不代表不在墙内，墙内外的定义是根据物理位置定义的？大陆任意公众网络都能reach和login到github，你还给hub分墙内外做什么呢？神仙逻辑

既然任意您喜欢抠字眼，那你可否告诉我，**墙内**和**墙外**的区别是什么呢？
think in smart way，这是我第三次送您这句话了，希望您谨记 （抱拳）
