### ISSUE TITLE
建议大神增加一个自己判断活跃时段的功能，在活跃时段自己运行的功能。。。

### ISSUE THREAD

**Issue by GaoHuaTJ** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#167]
# 大神你好！

**Comment by Alivon** [comment]
> # 大神你好！
> ## 希望你能考虑一下活跃时段的功能！可以出一个新的版本。。。
> ## 希望你能稍微换个名字。。。

@GaoHuaTJ 鉴于你的需求可以尝试下https://github.com/Alivon/Panda-Learning

**Comment by GaoHuaTJ** [comment]
哇！感谢大佬的的回复！


大佬关于二维码登陆变成账号密码登陆能给点思路吗？


万谢！


| |
高华
| |
|
邮箱：1551336@tongji.edu.cn
|

签名由 网易邮箱大师 定制

在2019年03月16日 11:16，代文豪 写道：
大神你好！
希望你能考虑一下活跃时段的功能！可以出一个新的版本。。。
希望你能稍微换个名字。。。

@GaoHuaTJ 鉴于你的需求可以尝试下https://github.com/Alivon/Panda-Learning

**Comment by AngelFalse** [comment]
这个不太可能，因为之前也有issue指出了，那个授权ticket是只能用几个小时的。过了那段时间还要继续刷的话，就只能重新扫码登录了。
顺带，如果是要在活跃时段运行的话，可以使用linux的crontab或者windows的任务计划功能。
