### ISSUE TITLE
建议作者增加一些功能，让软件更吊炸天

### ISSUE THREAD

**Issue by meterXu** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#170]
建议作者增加如下功能：
1、会话保持功能；
2、判断今日是否学满积分，未学满继续学习，学满就停止学习。判断当前学习的文章或者视频是否能获得积分，若观看的几分钟之后还未获得积分，则换另一个；
3、定时学习功能，用户可以自行设定每天几点开始自动开始学习，该功能基于会话保持功能
4、增加用户会话超时邮件提醒功能，这样我就可以开着这个软件不用管他，让他每天自动学习，除了用户退出之外。用户退出了的话就发邮件提醒，这样再扫码登一下就好了

**Comment by noway2014** [comment]
物極必反…軟件能幫幫忙就算了…

**Comment by herocspx** [comment]
支持支持，希望能增加上面那些功能，这样就完全不用管了。

**Comment by baoang** [comment]
现在软件还没屌呢，你看看这issue区都已经有点炸的意思了，官派和精赵们已经准备炸天了，要是增加功能，软件到了屌炸天的程度，他们赵氏精卫们还不得把宇宙给灭了？

**Comment by KyonCN** [comment]
免费软件能用就行了 别整天想有的没的

**Comment by whhxmwhh** [comment]
最近一直刷不满分数。。
视频学习时长不够。能救一开始就进入新闻联播？30分钟每天都是新的。

**Comment by tefiszx** [comment]
定时登录会被判断为异常行为。不支持加入

**Comment by whhxmwhh** [comment]
我在考虑是更为人性化一点的设计。只要一个网站，然后我们去把电话号码密码往上面一填。然后就没有我们的事儿。那才真叫解放。

**Comment by whhxmwhh** [comment]
这个网站名字可以不用fuck。

**Comment by BigCatLi** [comment]
> 我在考虑是更为人性化一点的设计。只要一个网站，然后我们去把电话号码密码往上面一填。然后就没有我们的事儿。那才真叫解放。

我们写程序并开源分享出来，是情分而不是本分。平时工作上被项目经理提各种需求就算了，像up这种业余做点好事，还要被你这种伸手党提各种需求，换做我肯定恶心死了。

**Comment by DolorHunter** [comment]
免费软件 能用就行了 弄太屌了 “学习”特征太强被搞特征识别就不好玩了

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 我在考虑是更为人性化一点的设计。只要一个网站，然后我们去把电话号码密码往上面一填。然后就没有我们的事儿。那才真叫解放。

#175

**Comment by meterXu** [comment]
....
