### ISSUE TITLE
一个成熟的小建议《日常3分钟30积分法》

### ISSUE THREAD

**Issue by clownvary** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#173]
这个程序我用了下，就是模拟鼠标自动浏览文章，整体速度较慢，可能也是为了安全，但这样开半个小时还不如我人工操作3分钟拿的分数多，既然我们就是为了快速拿积分，这个自动程序我觉得并不高效，且有被封号的风险， 现奉上本人常用的《日常3分钟30积分法》如下：
1. 登录打开后，直接选择有评论的新闻，快速收藏，评论，重复5次，用时40秒，得8积分
2. 关注2个学习公众号，用时5秒，得2积分
3. 每周答题(可以答之前没答过的)，答案都在答案解析里，很弱智，10题1分钟，得8-10分
4. 专题考试（可以答之前没答过的），答案如上，10题1分钟，得8-10分。
以上总计不到3分钟，得30分，安全高效，上个厕所就可以做完，仅供参考。

**Comment by wwyyii** [comment]
这个软件我怎么登录不了

**Comment by whhxmwhh** [comment]
关注2个学习公众号。。关注后一直不给刷出分数的很郁闷。

**Comment by sltalex** [comment]
10题1分钟是怎么做到的？  我做的好多答案都要靠理解，比如诗词 ，谁知道语境是啥，还要自己排序。很多答案都不会标出来。你确定10题1分钟？

**Comment by clownvary** [comment]
@sltalex 那种占比很少的，就算理解也花不了多久，绝对比自动程序快，大部分都是标准答案，现在好像都用颜色标注了，更快捷了。

**Comment by gantrylueng** [comment]
你做过题目吧？认真做过？很多是要打字的，还有一半没有颜色标注，得找。反正你想拿全8分10分不是那么1分钟能搞定的。
而且这个软件赚的分是不包括答题的余下的31分。现在就没有软件可以搞定你所谓的30分。
所以，最后不知道你要表达啥？

**Comment by whhxmwhh** [comment]
红本书不会让费太多时间。估计就是楼主要表达的意识。

**Comment by clownvary** [comment]
@gantrylueng 软件使用有风险，等哪天上面收紧了被封号，后果就严重了， 要背处分，除党籍的。 说白了，各有各的好处，就看你是想每天一分钟不花担点风险，还是每天3分钟安全度过了，还是那句话，仅供参考。

**Comment by stonebreaker2019** [comment]
> @gantrylueng 软件使用有风险，等哪天上面收紧了被封号，后果就严重了， 要背处分，除党籍的。 说白了，各有各的好处，就看你是想每天一分钟不花担点风险，还是每天3分钟安全度过了，还是那句话，仅供参考。

除党籍求之不得，只要不要进行政治报复，反正我又不想当官，我现在很羡慕那些不用每天刷题看视频的非党员同事，他们的闲暇时间相对于每天多我十几二十分钟

**Comment by stonebreaker2019** [comment]
> @gantrylueng 软件使用有风险，等哪天上面收紧了被封号，后果就严重了， 要背处分，除党籍的。 说白了，各有各的好处，就看你是想每天一分钟不花担点风险，还是每天3分钟安全度过了，还是那句话，仅供参考。

其实这些都是一步步温水煮青蛙，最早的时候是每天15积分，后来加码到30分，谁知以后会不会变成45分，60分？你一天就要花半个小时一个小时在上面，你给我工资吗？我比群众还要交党费啊，还要受这些折腾。我一天工作8-10小时已经够辛苦了，我不在那些机关单位，还是要真正干活的赚钱的。我能告诉你我现在才刚下班吗？

**Comment by Zayia** [comment]
> > @gantrylueng 软件使用有风险，等哪天上面收紧了被封号，后果就严重了， 要背处分，除党籍的。 说白了，各有各的好处，就看你是想每天一分钟不花担点风险，还是每天3分钟安全度过了，还是那句话，仅供参考。
> 
> 除党籍求之不得，只要不要进行政治报复，反正我又不想当官，我现在很羡慕那些不用每天刷题看视频的非党员同事，他们的闲暇时间相对于每天多我十几二十分钟

非党表示一样要学习

**Comment by jmdqnm** [comment]
葱省要求顶格满48分，荷兰省已经有单位自主发文件要求非党员也要注册学习，外聘人员也不能幸免

**Comment by dsoiew** [comment]
某省某地已要求非党员也要注册学习。

**Comment by funnypro** [comment]
> 已经有单位自主发文件要求非

那太可怕了

**Comment by Fxxk-XueXiQiangGuo** [comment]
《日常3分钟30积分法》可以作为对本软件的补充，谁愿意花时间看某人一直出现在你的屏幕上？
