### ISSUE TITLE
视频进度控制可以加快视频刷的速度

### ISSUE THREAD

**Issue by iZiwer** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#177]
经过实测，没必要每个视频从头看到尾部，只需要拖到最后直到自动停止就算看完了一个视频。看可以控制进度到最后3秒  这样效率会很高
新版本后面出现了很多其他的任务比如什么关注之类的，可以加入一下。

Ps:
每天上班，回家了想学一些专业的东西，还要学这个，之前每天30分，忍了，现在60分，qnmd，这是在逼人啊

**Comment by bingyuxq** [comment]
然而并不能，时间是pclog这个页面处理的，每30秒上报一次当前页面的驻留情况，并不是播放完上报

**Comment by whhxmwhh** [comment]
兄弟，要把前面的10秒钟看完，之后拉进度条才算合格的哦。
sb视频哪有人看呀。

**Comment by iZiwer** [comment]
> 然而并不能，时间是pclog这个页面处理的，每30秒上报一次当前页面的驻留情况，并不是播放完上报

然而我每个视频只是打开然后拖到最后自动结束，就算分了

**Comment by iZiwer** [comment]
> 兄弟，要把前面的10秒钟看完，之后拉进度条才算合格的哦。
> sb视频哪有人看呀。

然而我每个视频只是打开然后拖到最后自动结束，就算分了

**Comment by LevineWoo** [comment]
> > 兄弟，要把前面的10秒钟看完，之后拉进度条才算合格的哦。
> > sb视频哪有人看呀。
> 
> 然而我每个视频只是打开然后拖到最后自动结束，就算分了

貌似不算那个看视频每5分钟计分的那个吧？

**Comment by iZiwer** [comment]
> > > 兄弟，要把前面的10秒钟看完，之后拉进度条才算合格的哦。
> > > sb视频哪有人看呀。
> > 
> > 
> > 然而我每个视频只是打开然后拖到最后自动结束，就算分了
> 
> 貌似不算那个看视频每5分钟计分的那个吧？

a，好像是的

**Comment by Fxxk-XueXiQiangGuo** [comment]
程序是要刷看视频时长的分，所以视频进度控制没有什么用。

**Comment by iZiwer** [comment]
> 程序是要刷看视频时长的分，所以视频进度控制没有什么用。

看到你出现了真是开心啊
