### ISSUE TITLE
你们真无聊

### ISSUE THREAD

**Issue by qwerty258** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#185]
不喜欢他们做法就退出啊，又不虔诚的接受洗脑，又想拿分不想严重到被开除，有意思？

**Comment by stonebreaker2019** [comment]
除党籍没所谓，但是凭什么开除我呀？我犯法了吗？我颠覆国家了吗？只不过不想把宝贵的时间花在这些形式主义上（大部分的被要求学习的都只不过开着网页或者手机app挂机）。而且目前的做法跟共产党的初衷偏离了。

**Comment by duobixibeila** [comment]
还真有退党不学习会被开除的，那这种公司还呆着又什么意义呢？反正都是屎窝了，要刚怎么不再刚一点？开除就开除啊，工作又不差这一个，随便开除，告公司啊，继续刚呗，别在网络上用键盘刚啊

**Comment by iZiwer** [comment]
> 除党籍没所谓，但是凭什么开除我呀？我犯法了吗？我颠覆国家了吗？只不过不想把宝贵的时间花在这些形式主义上（大部分的被要求学习的都只不过开着网页或者手机app挂机）。而且目前的做法跟共产党的初衷偏离了。

支持  目前的做法太形式主义了，我现在披露下我们这开会的应付形式——
在正常的工作日，要求9点到居委会，不来就各种言语损，但是请假了过去了，等到快9:20了，开始了，然后装模做样的拿个东西在那念一段，让大家都坐在那装着听，赶紧拍照！！！赶紧拍照！！！赶紧拍照！！！
大概9:30之前拍完了，就散会了，也就是说 你请假就是为了他们应付差事，帮助他们把表面工作做漂亮，这样的党给我党籍开除了是可以的，没意义啊！

**Comment by WLH666666Wang** [comment]
生活被逼啊，谁不想活的有滋有味的，到前提你得有钱啊

**Comment by sltalex** [comment]
> > 除党籍没所谓，但是凭什么开除我呀？我犯法了吗？我颠覆国家了吗？只不过不想把宝贵的时间花在这些形式主义上（大部分的被要求学习的都只不过开着网页或者手机app挂机）。而且目前的做法跟共产党的初衷偏离了。
> 
> 支持 目前的做法太形式主义了，我现在披露下我们这开会的应付形式——
> 在正常的工作日，要求9点到居委会，不来就各种言语损，但是请假了过去了，等到快9:20了，开始了，然后装模做样的拿个东西在那念一段，让大家都坐在那装着听，赶紧拍照！！！赶紧拍照！！！赶紧拍照！！！
> 大概9:30之前拍完了，就散会了，也就是说 你请假就是为了他们应付差事，帮助他们把表面工作做漂亮，这样的党给我党籍开除了是可以的，没意义啊！

你这是国企吧，私企这样早倒闭了

**Comment by iZiwer** [comment]
> > > 除党籍没所谓，但是凭什么开除我呀？我犯法了吗？我颠覆国家了吗？只不过不想把宝贵的时间花在这些形式主义上（大部分的被要求学习的都只不过开着网页或者手机app挂机）。而且目前的做法跟共产党的初衷偏离了。
> > 
> > 
> > 支持 目前的做法太形式主义了，我现在披露下我们这开会的应付形式——
> > 在正常的工作日，要求9点到居委会，不来就各种言语损，但是请假了过去了，等到快9:20了，开始了，然后装模做样的拿个东西在那念一段，让大家都坐在那装着听，赶紧拍照！！！赶紧拍照！！！赶紧拍照！！！
> > 大概9:30之前拍完了，就散会了，也就是说 你请假就是为了他们应付差事，帮助他们把表面工作做漂亮，这样的党给我党籍开除了是可以的，没意义啊！
> 
> 你这是国企吧，私企这样早倒闭了

你没认真看我说的

**Comment by jmdqnm** [comment]
令堂今晚出来吗
