### ISSUE TITLE
直接在命令行界面运行，有可能实现吗？

### ISSUE THREAD

**Issue by gitodo** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#19]
很好用，无论是在Windows还是在Linux图形化界面。
但，有可能直接命令行界面运行吗？
我有台虚拟主机，CentOS7，想长期挂着每天自动刷分，然后从生活中忘记这个事情。

**Comment by Steven-nagisa-Y** [comment]
我觉得应该不能，它这个是模拟你浏览网页刷分的，没有网页应该不能刷分吧？

**Comment by Fxxk-XueXiQiangGuo** [comment]
理论上可以使用 Electron 的 [无头模式](https://electronjs.org/docs/tutorial/testing-on-headless-ci) 和 [离屏渲染](https://electronjs.org/docs/tutorial/offscreen-rendering) 。

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经实现了](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#%E7%9B%B4%E6%8E%A5%E5%9C%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E7%95%8C%E9%9D%A2%E8%BF%90%E8%A1%8C)

**Comment by gitodo** [comment]
棒！

**Comment by dexterque** [comment]
请问 这样是不是不能 变成守护进程的模式 在后台运行呢？
