### ISSUE TITLE
建议编译一个mac版本

### ISSUE THREAD

**Issue by locxiang** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#2]
好东西，看名字就很骚，必须赞，可以考虑开源大家一起维护

**Comment by Fxxk-XueXiQiangGuo** [comment]
好的

**Comment by LUOOQ** [comment]
> 好的，已更新
> [Fuck学习强国-darwin.zip](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/raw/master/Fuck%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD-darwin.zip)

刷到视频的时候似乎会卡住，视频不会自动播放。MAC
