### ISSUE TITLE
好消息，学习达人可以免费旅游！

### ISSUE THREAD

**Issue by CoderYellow** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#206]
[通知：凭学习强国积分 可免费浏览14处景区](https://m.toutiaocdn.cn/i6672133357091947011/?app=news_article&timestamp=1553484819&group_id=6672133357091947011&tt_from=weixin_moments&utm_source=weixin_moments&utm_medium=toutiao_ios&utm_campaign=client_share&wxshare_count=6&pbid=6672193213631383048&from=groupmessage&isappinstalled=0)

**Comment by kloudmuka** [comment]
凭积分换取住房指日可待

**Comment by Kurenai322** [comment]
前几天还和人扯到5月强行调休4天是促进旅游的,真是快.
