### ISSUE TITLE
花了点时间写了一些针对性反驳@jvbaotw的内容，结果发布comment的时候github告诉我这个人已经没了（笑哭）😂😂😂

### ISSUE THREAD

**Issue by AngelFalse** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#207]
还是第一次现场见证这种“在？你号没了”的事情，现在我的脸有点不知道该做出什么表情为好。谁给点意见？😂😂😂

**Comment by stonebreaker2019** [comment]
是谁？

**Comment by Kurenai322** [comment]
按照他的用语方式,这位jvbao应该是个旧恶俗系人士,之前混迹于一些名声较臭的贴吧.
现在搞个低级反串黑,你反驳他,他的目的就达到了.
他还巴不得你破口大骂五毛精赵,然后再自己挂到推上扩散,反正他不是五毛精赵,被你骂了也毫无笋丝.

**Comment by AngelFalse** [comment]
> 是谁？

我TM也想知道啊。
😂

> 按照他的用语方式,这位jvbao应该是个旧恶俗系人士,之前混迹于一些名声较臭的贴吧.
> 现在搞个低级反串黑,你反驳他,他的目的就达到了.
> 他还巴不得你破口大骂五毛精赵,然后再自己挂到推上扩散,反正他不是五毛精赵,被你骂了也毫无笋丝.

你真的读过他的帖子吗？我感觉他是发自真心地觉得自己是粉红。
而且我可没怎么骂人喔，我很**儒**( )**雅**( )**随**( )**和**( )的（括号内请填入自己认为合适的字母，滑稽）。

**Comment by Kurenai322** [comment]
> 是谁？
> 
> 我TM也想知道啊。
> 😂
> 
> 按照他的用语方式,这位jvbao应该是个旧恶俗系人士,之前混迹于一些名声较臭的贴吧.
> 现在搞个低级反串黑,你反驳他,他的目的就达到了.
> 他还巴不得你破口大骂五毛精赵,然后再自己挂到推上扩散,反正他不是五毛精赵,被你骂了也毫无笋丝.
> 
> 你真的读过他的帖子吗？我感觉他是发自真心地觉得自己是粉红。
> 而且我可没怎么骂人喔，我很儒( )雅( )随( )和( )的（括号内请填入自己认为合适的字母，滑稽）。

一般粉红侧不会使用正义人士这个自称.
你要是肉他,可能发现他叫王文荣或是刘俊.

**Comment by stonebreaker2019** [comment]
我谷歌搜索到jvbaoillegal这个id，是不是？我觉得要么他是高级黑要么就是脑子有问题。
他在twitter的2007年的记录说由于自己翻墙的VPN被墙了，就走上举报翻墙的道路。（那么他的twitter是如何登录的？普通民众是很难申请到合法的VPN服务的，需要公司申请）那么他岂不是做贼的喊抓贼？

**Comment by stonebreaker2019** [comment]
“我自用的翻墙ss工具被封了，真是气人！更气人的是qq群里居然还有人的没封！
我就想问问怎样才能有效举报？？？让那些人的翻墙vpn vps也都给统统封掉！！！

我现在最气的就是不患寡而患不均，要封大家一块封！来说说到底该怎样举报？举报给网警还是网信办最有效？”
这是他在twitter 2017年7月20日的原话

**Comment by mdevc** [comment]
你们研究个傻逼还这么认真，服

**Comment by anviod** [comment]
> 还是第一次现场见证这种“在？你号没了”的事情，现在我的脸有点不知道该做出什么表情为好。谁给点意见？😂😂😂
 你可以像我这样哈。
https://github.com/boycott-fuck-xuexiqiangguo/Boycott-Fuck-XueXiQiangGuo/issues/69

**Comment by AngelFalse** [comment]
> 你们研究个傻逼还这么认真，服

这不是闲得发慌嘛（滑稽）
