### ISSUE TITLE
为何要做虚拟机检测呢~？

### ISSUE THREAD

**Issue by Hiiragi-Yuriko** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#21]
RT，VM虚拟机内不能运行

**Comment by Fxxk-XueXiQiangGuo** [comment]
没有啊…
虚拟机内运行的操作系统是什么？虚拟机配置正确吗？有报错信息吗？

**Comment by Hiiragi-Yuriko** [comment]
> 没有啊…
> 虚拟机内运行的操作系统是什么？虚拟机配置正确吗？虚拟机能联网吗？有报错信息吗？

Win7 32位（非Ghost，杀软只装了MSE），配置正确（QQ等常用软件运行OK），可以联网（NAT），没有任何报错提示（双击后 任务管理器中进程一闪而过）
可能是我虚拟机的问题吧，换了个操作系统就正常了 XD
