### ISSUE TITLE
感谢作者，希望增加海外手机号登陆选项

### ISSUE THREAD

**Issue by shadow-fight** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#230]
感谢作者的付出，增加了手机号登陆使得自动刷学习强国成为了可能。可是我的学习强国是用海外手机号注册的，作者有空的话能不能增加一个海外归属地手机号选择的功能

**Comment by Fxxk-XueXiQiangGuo** [comment]
v0.5.0 已经支持。
```
./Fuck学习强国 --help
```

```
......
--username=<phone_number> ,
--passwd=<password>  使用用户名（手机号，如果是外国手机号，请以 +1-xxxxxxxxxx 的格式输入）密码自动登录
```

**Comment by cz1980** [comment]
请教一下，用手机号，而不是扫码能够登陆的原理是什么啊？

**Comment by shadow-fight** [comment]
感谢，这就试一下

**Comment by Nevidebla** [comment]
> 感谢作者的付出，增加了手机号登陆使得自动刷学习强国成为了可能。可是我的学习强国是用海外手机号注册的，作者有空的话能不能增加一个海外归属地手机号选择的功能

你好，我最近正在注册测试学习强国这个平台，但是发现海外手机号接收不到验证码和语音来电。不知你当初的情况是什么样？
