### ISSUE TITLE
想进996ICU微信500人大群的请加我,我拉大家

### ISSUE THREAD

**Issue by RexFu** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#233]
![mmqrcode1553825861957](https://user-images.githubusercontent.com/25890885/55210788-15d39980-5224-11e9-8f90-2d345bd1786e.png)

**Comment by AngelFalse** [comment]
@fuck-xuexiqiangguo
与此repo无关的内容，建议关闭此Issue，谢谢。
