### ISSUE TITLE
有没有在树莓派成功运行的朋友？

### ISSUE THREAD

**Issue by noway2014** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#24]
说说安装和运行情况。

**Comment by kalike23** [comment]
1.按照这篇教程开启vnc  https://www.jianshu.com/p/b73f358849de 并在电脑上通过vnc登陆你的树莓派。
2.把树莓派版本的程序放到（下载、smb等等什么办法都可以）树莓派上并解压。
3.在命令行窗口运行 chmod +x Fuck学习强国  修改权限。
4.打开程序，扫码登陆就可以运行了。
ps：希望coder可以解决树莓派定时登陆的功能，目前要每天登陆一次，学习强国的网页版是不是只能通过扫码来登陆，如果是的话是否可以通过scrot定时截图并发邮件给自己。然后在手机上接收截图，并用手机版学习强国来识别登陆就可以了。只是自己的想法，作者可能有更好的方案来解决这个问题，望不吝赐教。

**Comment by noway2014** [comment]
非常感谢你的回复，详细问下，如果使用第三点的命令，下载的这个程序应该放在树莓派那个位置？如何从pc传进去树莓派呢？因为初哥，请不吝赐教。感谢。越详细越好

**Comment by litaoxyz** [comment]
可以直接在树莓派里面wget这个Fuck学习强国-raspberrypi.zip压缩包，放在用户目录下就可以吧，pc传到树莓派可以用winscp

**Comment by noway2014** [comment]
可以在树莓派wget这个软件？wget不是要在软件源上用才可以吗？已经下载的本地文件应如何安装进去？

**Comment by noway2014** [comment]
请问，如果winscp，应该传到树莓派那个目录？传后，又如何安装呢？

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 可以在树莓派wget这个软件？wget不是要在软件源上用才可以吗？已经下载的本地文件应如何安装进去？

软件源的那个是 `apt-get`

**Comment by noway2014** [comment]
反馈一下，在看视频时候，有时候会出现视频失效的对话框提示。看其他正常。希望作者修复这个问题。碰上看不过去的视频能自动跳过去别的。

**Comment by lgxnas** [comment]
> 1.按照这篇教程开启vnc https://www.jianshu.com/p/b73f358849de 并在电脑上通过vnc登陆你的树莓派。
> 2.把树莓派版本的程序放到（下载、smb等等什么办法都可以）树莓派上并解压。
> 3.在命令行窗口运行 chmod +x Fuck学习强国 修改权限。
> 4.打开程序，扫码登陆就可以运行了。
> ps：希望coder可以解决树莓派定时登陆的功能，目前要每天登陆一次，学习强国的网页版是不是只能通过扫码来登陆，如果是的话是否可以通过scrot定时截图并发邮件给自己。然后在手机上接收截图，并用手机版学习强国来识别登陆就可以了。只是自己的想法，作者可能有更好的方案来解决这个问题，望不吝赐教。

@Fxxk-XueXiQiangGuo 我刚发现这个好项目，还不知道是否需要每天扫码，能否使用ftqq的服务推送到微信来方便扫码登陆
