### ISSUE TITLE
本项目将无限期停止更新

### ISSUE THREAD

**Issue by Fxxk-XueXiQiangGuo** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#241]
由于**众所周知的原因**，本项目将无限期停止更新，感谢每位朋友的支持与厚爱，希望有天我们还能再相见。

<br>
<br>
<br>
<br>
<br>
<br>
<br>

*今天是什么日子？*

**Comment by neutronemu** [comment]
众所周知的原因是习大大暴毙，学习app暂时下架

**Comment by AngelFalse** [comment]
nmd，吓死我了

**Comment by mdevc** [comment]
真的假的

**Comment by OMDONG** [comment]
吓死我了

**Comment by whhxmwhh** [comment]
愚人节快乐！

**Comment by Kurenai322** [comment]
> 
> 
> 众所周知的原因是习大大退位，薄熙来复出，学习app暂时下架，新的学熙app预期下个月上马

笑skr人

**Comment by lwy0625** [comment]
众所周知 今天是愚人节

**Comment by Springxi** [comment]
emmmm，当真了，吓死人

**Comment by openwrt1** [comment]
真的假的

**Comment by menghuanchenfeng** [comment]
我了个去，愚人节啊

**Comment by gs666** [comment]
> 真的假的

愚人节快乐！

**Comment by sealdoomer** [comment]
节日快乐。

**Comment by Tsewingto** [comment]
众所周知 今天是愚人节

**Comment by neutronemu** [comment]
插播品葱网消息：
薄熙来在秦城监狱服刑期间，因为表现良好，其无期徒刑减为200年。官方表示，薄熙来努力改造自我，通过学刁强国app，认真学习档中央的政策精神，值得表扬。据称，其学刁积分排名前十，有人怀疑其使用作弊手段获得积分，薄熙来在狱中表示：我听说有人正给秦城监狱“泼脏水”，包括给我本人给家庭泼脏水，甚至说我儿子在外面学习使用了作弊手段，一派胡言，我感觉非常气愤，一派胡言！不仅我儿子，我和我夫人也没有使用fuck-xuexiqiangguo此类的作弊手段，几十月就是这样下来了。

https://pincong.rocks/article/1076

**Comment by SaveMyAss** [comment]
一派胡言！😆

**Comment by Raymond8855** [comment]
吓skr人

**Comment by Rhodes8964** [comment]
加油兄弟，好人一生平安

**Comment by mmm520109** [comment]
吓死我了

**Comment by sunhuanghe** [comment]
这上面言论这么自由的吗？

**Comment by Fxxk-XueXiQiangGuo** [comment]
今天是真的停止更新了，见 #578 。  
多谢大家支持。
