### ISSUE TITLE
这里成了天朝反‘刁’前哨站了吗？

### ISSUE THREAD

**Issue by AeneasZhu** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#242]
如题，感觉在这里遇见好多志同道合的人

**Comment by neutronemu** [comment]
这里主要还是服务于Fuck-XueXiQiangGuo 以下是一些反共基地：
https://program-think.blogspot.com/
https://pincong.rocks
https://mohu.pincong.rocks/
https://www.reddit.com/r/saraba1st

**Comment by stonebreaker2019** [comment]
别乱说，大家只不过想做懒人。这里说话尽量不要涉及政治。你想害死作者和使用该软体的人？万一github被封了。
