### ISSUE TITLE
建议增加topmost及1x1大小

### ISSUE THREAD

**Issue by Justysxh** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#243]
由于程序不能把窗口最小化或者退出.
那么能不能增加一个功能 , 把窗口设置为topmost, 并且大小缩放成1x1大小, 放到屏幕的某个角落, 即不影响用户正常工作, 也不会因最小化等影响上分.

**Comment by NPUTom** [comment]
win10下可以新建一个桌面，把程序窗口放到新建的桌面里面，这样最舒服。

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经解决在最小化窗口后不能继续得分的问题](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#062---2019-04-04)。
