### ISSUE TITLE
我们已经人肉出道了项目作者，要求作者立即停止更新！

### ISSUE THREAD

**Issue by oabvj** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#249]
姓名：王巍凌
出生日期：1989年6月4日
毕业院校：五道口职业技术学院宇宙机科学专业
居民身份证号码：110102198906041141

**Comment by Tohsakahoshi** [comment]
所以说公民隐私就这么让你们随意践踏吗

**Comment by SkilfulBugsMaker** [comment]
我看你是完全不懂哦

**Comment by whhxmwhh** [comment]
1989年6月4日
这个出生日期很熟悉哦。

**Comment by DoAcha** [comment]
姓名：鲍峦
出生日期：1989年6月4日
毕业院校：天安门地区宇宙科学专业
居民身份证号码：110101198906040604

**Comment by mdevc** [comment]
> 所以说公民隐私就这么让你们随意践踏吗

应该不存在"你们"，你以为那个傻逼姓赵？😄不过这个issue应该是倒钩，这生日

**Comment by neutronemu** [comment]
这都过了愚人节了

**Comment by fuck1partynoelectionsys** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Free Tibet 劉曉波动态网自由门 动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Free Tibet 劉曉波动态网自由门

**Comment by imShowhey** [comment]
> 所以说公民隐私就这么让你们随意践踏吗

认真就输了

**Comment by SaveMyAss** [comment]
我TM管你不是友军，反正一炮轰死然后厚葬算逑😂

**Comment by rpfbl** [comment]
![image](https://user-images.githubusercontent.com/41824047/55413613-3b520180-559c-11e9-8dd6-5af2dbfc127f.png)

**Comment by humiliatehua** [comment]
蛤蛤蛤两天前不是4月1日嘛？

**Comment by Fxxk-XueXiQiangGuo** [comment]
开玩笑请适度，谢谢。
