### ISSUE TITLE
win下不会自动播放视频？

### ISSUE THREAD

**Issue by star2k** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#25]
如题，需要手动点击播放，否则不会自动播放，分数也上不去。谢谢

**Comment by noway2014** [comment]
安装后要重启电脑试试

**Comment by star2k** [comment]
> 
> 
> 安装后要重启电脑试试

重启也一样，没法自动播放视频。你那正常？

**Comment by supppig** [comment]
我的貌似也不会，win10 64位 17134。
但是貌似不影响刷分。
也挺好的，起码不吵不闹。。。。
但是视频我发现点开的是一个07年的视频，不是最新的，怕被查水表（行为与正常浏览不符）。。。
而且我发现只要网页打开，放到正文就可以刷分，不需要上上下下来回动作滚动条。。。

**Comment by Fxxk-XueXiQiangGuo** [comment]
已修复自动播放视频

**Comment by star2k** [comment]
为什么没法下载了？是我个例么

**Comment by Fxxk-XueXiQiangGuo** [comment]
GFW 将 raw.githubusercontent.com 屏蔽了

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 为什么没法下载了？是我个例么

可以尝试 [镜像1](https://raw.githack.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/master/Fuck学习强国-win32.zip) 和 [镜像2](https://cdn.staticaly.com/gh/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/master/Fuck学习强国-win32.zip)
