### ISSUE TITLE
有没有可能配合安卓模拟器实现自动答题？

### ISSUE THREAD

**Issue by zm1107** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#251]
比如，电脑安卓模拟器安装软件后，可以实现自动点击，然后自动截图，配合文字识别，可以提取参考答案中合适内容匹配到题中，应该可以实现自动答题吧？
我只是提个可能性建议，我水平不行~

**Comment by stonebreaker2019** [comment]
理论上是可以实现的，就好象目前那些破解检测人机识别文字的程序一样。因为目前大多数题目是采取绿色高亮标识，这样其实很方便让程序自动识别出答案。但是要是这样做，就真是连累那些不开挂老实做题的人了，因为官方为了反破解就不会让答案高亮显示，做题就变得更加困难。那样会招恨的。而这次分值修改后靠挂机看视频和文字顶多也就积累25分，攒够30分其实更难了，必须做题。估计也是因为外挂的原因。
