### ISSUE TITLE
我们已经得到了项目作者的ip地址，要求作者立即停止更新！

### ISSUE THREAD

**Issue by oabvj** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#253]
ipv4：
180.76.76.76
223.5.5.5
223.6.6.6
119.29.29.29
182.254.118.118
119.28.28.28
127.0.0.1
192.996.428.1
225.225.255.0

ipv6：
2400:da00:2::29
2001:da8:20d:7042::f1
2001:da8:20d:7042::f2
2001:0:996:1cu8:1319::7344

欢迎DDOS

**Comment by mdevc** [comment]
妈呀还要反串傻逼，你们累不累的啊

**Comment by SaveMyAss** [comment]
好的，那我们会选择各自的ip去dd的。

顺带一提，你可以先扫一下，比如，127.0.0.1上有什么端口，再针对性地用类似loic之类的东西来d，应该会有不错的效果。
