### ISSUE TITLE
建议增加自动登录自动学习功能

### ISSUE THREAD

**Issue by hfgang** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#270]
指定一个时间范围（为了防止被屏蔽），自动开启学习，并且自动完成登录（已经有别的程序实现了），学习完成后，自动关闭，第二天再自动开启。

**Comment by G3boy** [comment]
人啊，总是欲求不满 永不知足

**Comment by DoAcha** [comment]
回复 G3boy“人啊，总是欲求不满 永不知足”
人都有追求美好的权力，而不是固步自封，否则，技术怎么进步？你长的丑就应该一刀了结吗？@G3boy

**Comment by G3boy** [comment]
> 回复G3boy“人啊，总是欲求不满永不知足” 
> 人都有追求美好的权力，而不是固步自封，否则，技术怎么进步？你长的丑就应该一刀了结吗？@G3boy

你的追求为什么去建议别人给你达成？人家欠你的吗？还是你付钱了？最恶心就是你这种要这个要那个功能的，你怎么建议弄个AI给你，傻儿缺

**Comment by DoAcha** [comment]
做这个产品的目的是什么，大家都知道，就是要往好里做，提提建议/提提功能在你这里就恶心了？请注意看首页的说明，懂英文部？“Browse issues in fuck-xuexiqiangguo/Fuck-XueXiQiangGuo
Issues help repositories track bugs, enhancements, and ideas. You can submit new bugs, requests, or join the discussion.”

**Comment by xuexiqiangguo2019** [comment]
太复杂了敢情好？老人家俺不晓得咋用咧。既是有别的程序实现了，咋不用别的程序？

**Comment by Fxxk-XueXiQiangGuo** [comment]
[自动登录功能是有的](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#050---2019-03-28)。

**Comment by Fxxk-XueXiQiangGuo** [comment]
24小时±30分钟后程序会自动再次开启学习，也可以[用Travis-CI自动化运行](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/issues/175)。
