### ISSUE TITLE
每天首次启动不能自动登陆,也不提示登陆,必要第二次打开才提示登陆

### ISSUE THREAD

**Issue by Justysxh** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#279]
一般每天的第一次启动程序时, 没有提示需要扫码登陆, 也不自动登陆, 就在首页那里不动.
必须要关闭程序 , 再次打开, 才提示扫码登陆, 才能正常工作.

**Comment by cy920820** [comment]
能一直24 小时挂机么，还是必须每天重新登录？@fuck-xuexiqiangguo

**Comment by netXiaoYang** [comment]
你24小时挂机不怕被封号？

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经修复](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#064---2019-04-25)。

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 能一直24 小时挂机么，还是必须每天重新登录？@fuck-xuexiqiangguo

是可以 24 小时挂机的。如果[使用用户名密码自动登录](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#050---2019-03-28)，就算是被强制退出登录，也是能够自动重新登录的。我建议[用Travis-CI每天自动化运行](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/issues/175)。
