### ISSUE TITLE
最近打不开了？什么情况？

### ISSUE THREAD

**Issue by justlearn444** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#282]
从17号开始，网页无法打开登录？有同样情况的吗？怎么了？

**Comment by techiehu** [comment]
确实打不开了。不知道什么原因

**Comment by sunhuanghe** [comment]
这个学习强国都有什么需要注意的 刷分的时候

**Comment by HeyStevenJackson** [comment]
无法打开了，枯了

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经修复](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#064---2019-04-25)。
