### ISSUE TITLE
能配置http代理吗？

### ISSUE THREAD

**Issue by xixitalk** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#295]
windows版本能配置http代理吗？

**Comment by jysqice** [comment]
https://sourceforge.net/projects/proxychains-ng/files/

**Comment by Fxxk-XueXiQiangGuo** [comment]
程序[已经支持](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#070---2019-05-11)配置http和socks代理，可以使用 `--proxy=<proxy_rules>` 命令行选项配置。

```
./Fuck学习强国 --proxy="http://127.0.0.1:1080"
```
