### ISSUE TITLE
大佬请求更新

### ISSUE THREAD

**Issue by WLH666666Wang** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#300]
大佬，项目目前已经没法刷了，请求更新

**Comment by jiancrazy** [comment]
同求。。。

**Comment by xuefliang** [comment]
同求

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#070---2019-05-11)。
