### ISSUE TITLE
多用户脚本 一键启动

### ISSUE THREAD

**Issue by eRenier** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#302]
echo Start

echo 用户1（手机号） 填写手机号方便区分（下同）
start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX

echo 用户2（手机号）
start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX

echo 用户3（手机号）
start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
.
.
.
echo TimeMachine Start

-jar timeMachine.jar

exit

**Comment by Jin-wei** [comment]
请问次数是哪个参数？，如果设置呢？

**Comment by eRenier** [comment]
> 请问echo timeMachine START 是做什么用的呢？

echo 后面的就是文本输出  没什么用  就是个提示作用

**Comment by eRenier** [comment]
> echo start
> 
> echo 学习强国 START
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> 
> echo
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> 
> echo
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> .
> .
> .
> echo timeMachine START
> 
> -jar timeMachine.jar
> 
> exit

**Comment by eRenier** [comment]
C:\Users\User\Desktop\Fuck学习强国-win32
将此路径修改为自己的路径

**Comment by eRenier** [comment]
> echo Start
> 
> echo 用户1（手机号） 填写手机号方便区分（下同）
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> 
> echo 用户2（手机号）
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> 
> echo 用户3（手机号）
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> .
> .
> .
> echo TimeMachine Start
> 
> -jar timeMachine.jar
> 
> exit

**Comment by ryan016** [comment]
太谢谢了！

**Comment by WLH666666Wang** [comment]
> echo Start
> 
> echo 用户1（手机号） 填写手机号方便区分（下同）
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> 
> echo 用户2（手机号）
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> 
> echo 用户3（手机号）
> start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> .
> .
> .
> echo TimeMachine Start
> 
> -jar timeMachine.jar
> 
> exit

大佬，这东西怎么用啊？

**Comment by eRenier** [comment]
> > echo Start
> > echo 用户1（手机号） 填写手机号方便区分（下同）
> > start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> > echo 用户2（手机号）
> > start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> > echo 用户3（手机号）
> > start /d "C:\Users\User\Desktop\Fuck学习强国-win32" Fuck学习强国 --username=XXXXXXXX --passwd=XXXXXXXX
> > .
> > .
> > .
> > echo TimeMachine Start
> > -jar timeMachine.jar
> > exit
> 
> 大佬，这东西怎么用啊？

这个东西已经写的很明白了，再不明白   已经没法解释了
把路径部分改成自己的路径就可以了

**Comment by olejga3d** [comment]
> 请问echo timeMachine START 是做什么用的呢？

类似其他程序的print xxx

**Comment by jiancrazy** [comment]
这个功能实在是太方便了，我之前傻傻的用按键精灵去登录账号

**Comment by programmerZe** [comment]
-jar timeMachine.jar
这一步是什么意思？能运行但是命令框显示：
'-jar' is not recognized as an internal or external command,
operable program or batch file.

**Comment by eRenier** [comment]
> -jar timeMachine.jar
> 这一步是什么意思？能运行但是命令框显示：
> '-jar' is not recognized as an internal or external command,
> operable program or batch file.

后来发现没什么意义  你可以删除
这个命令我也晚上DOWN下来 修改的
