### ISSUE TITLE
好像不能用了

### ISSUE THREAD

**Issue by fzs001** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#32]
刚下载，用了一小会还会自动点文章，关闭后重启程序，就一直在主页一动不动了

**Comment by zbenzhen** [comment]
是不是今天刷视频和文章的积分达到上限了

**Comment by fzs001** [comment]
> 是不是今天刷视频和文章的积分达到上限了

请问这个软件的上限是多少？

**Comment by zbenzhen** [comment]
> > 是不是今天刷视频和文章的积分达到上限了
> 
> 请问这个软件的上限是多少？

看视频和文章30分， 登陆1分。 其他的操作目前只能在手机端完成（具体原因可以看其他的issue）

**Comment by fzs001** [comment]
> > > 是不是今天刷视频和文章的积分达到上限了
> > 
> > 
> > 请问这个软件的上限是多少？
> 
> 看视频和文章30分， 登陆1分。 其他的操作目前只能在手机端完成（具体原因可以看其他的issue）

好的，非常谢谢！
