### ISSUE TITLE
火绒报毒

### ISSUE THREAD

**Issue by Nokedbd** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#322]
exe文件有人报毒吗

**Comment by hiwasax** [comment]
没有

**Comment by SaveMyAss** [comment]
火绒并没有报毒啊。
![image](https://user-images.githubusercontent.com/49082706/58485920-81d86c80-8197-11e9-8f38-938df7cfaade.png)

**Comment by Fxxk-XueXiQiangGuo** [comment]
大概是误报。如果不放心，程序是可以放虚拟机中运行的。
