### ISSUE TITLE
我被封了，凉了！！！

### ISSUE THREAD

**Issue by Lxxsss** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#328]
![4011559182274_ pic_hd](https://user-images.githubusercontent.com/11531863/58603535-bb0dfb00-82c3-11e9-8f4f-4c2156ece935.jpg)

**Comment by ciao1** [comment]
同被封，用过类似刷分软件的貌似都被封了

**Comment by huangyongqi123** [comment]
> 同被封，用过类似刷分软件的貌似都被封了

还能查到谁用过没有？这几天我都没有用了手动刷

**Comment by WLH666666Wang** [comment]
> > 同被封，用过类似刷分软件的貌似都被封了
> 
> 还能查到谁用过没有？这几天我都没有用了手动刷

听说这只是一个前奏，真正的秋后算账正在扫

**Comment by Phishion** [comment]
你们被封的有没有用过其他的软件？一直使用的 fuck 吗
