### ISSUE TITLE
纪念89 纪念6.4运动 反对共产党独裁统治

### ISSUE THREAD

**Issue by chinchiehao** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#334]
6.4运动30周年来临之际，我们一起纪念那段历史。30年前柏林那堵墙倒了，我们的墙摇了摇更坚固了。人民群众对美好生活的追求不仅仅是物质上，更是精神上。互联网开放，言论自由是我们一直追求的目标，或许下一个30年，30年再30. 历史不容忘记。但在纪念6.4之际也请正视那段历史。学运领导人的恶意是造成学生的伤害流血。学生的暴动烧毁汽车，扰乱公共秩序。这些也请记住。纪念6.4不是去推翻共产党，而是去激励我们追求言论自由！宪政民主！

**Comment by GengchenXU** [comment]
我现在都不知道到底示威到底有没有用，和平示威在现代国家机器下很快会被化解，转化为暴动跟国家机器对抗更是不可能，有时候只有彻底的革命才可以
