### ISSUE TITLE
只更新了下说明，没更新程序？

### ISSUE THREAD

**Issue by ZRONIN** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#338]

**Comment by whhxmwhh** [comment]
感谢更新了。谢谢大佬！

**Comment by whhxmwhh** [comment]
二维码刷不出来。
有丁丁的登陆账号

**Comment by whhxmwhh** [comment]
登陆不了。

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#071---2019-06-23)。
