### ISSUE TITLE
作者怎么都不更新了

### ISSUE THREAD

**Issue by huangyongqi123** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#345]

**Comment by hafeng45** [comment]
即便更新也会很快被针对封号，这里已经被盯上了，现在是我们在明他们在暗，更新已经没有意义。

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#071---2019-06-23)。
