### ISSUE TITLE
阅读文章、文章时长不加分

### ISSUE THREAD

**Issue by jzmswe** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#348]
20190614

**Comment by whhxmwhh** [comment]
同样的问题。文章阅读增加不到分数。倒是视频出错了。还没看多少就都满了。个数与时长都满了。

**Comment by xuzhenyi1234** [comment]
一样的问题
![捕获](https://user-images.githubusercontent.com/49029900/59508356-3ab0e200-8ee0-11e9-97fd-4540d93b8134.PNG)

**Comment by JingLuo2017** [comment]
版本：0.7.0
系统：Windows 10
时间：2019年6月15日
问题：阅读文章操作存在，但是阅读文章和文章时长的积分不会增加。存在复现

**Comment by UP1600** [comment]
遇到了一样的问题

**Comment by hahaha34** [comment]
同样的问题

**Comment by hackeredsx** [comment]
求指导如何修改a_log数值

**Comment by shx1943** [comment]
win7,
0.7.0
2019/6/15
存在复现

**Comment by mouniga01** [comment]
我的也是这个问题，怎么大师不出来更新了，已经两天的时间了。呵呵，辛苦

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#071---2019-06-23)。
