### ISSUE TITLE
文章阅读 刷不出分了

### ISSUE THREAD

**Issue by sihuishwngjing** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#349]

**Comment by sihuishwngjing** [comment]
阅读文章 没有分数了

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#071---2019-06-23)。
