### ISSUE TITLE
最新版本V1.0阅读文章没有积分

### ISSUE THREAD

**Issue by sihuishwngjing** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#350]

**Comment by adslhuang** [comment]
文章列表出问题了

**Comment by zidapang** [comment]
https://github.com/Alivon/Panda-Learning/issues/403

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#071---2019-06-23)。
