### ISSUE TITLE
最近发现的一些事情

### ISSUE THREAD

**Issue by Kurenai322** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#351]
相关：非党员、刷刷图个乐

时间：5月20日至今，基本工作日每天刷

这边之前刷的时候一般使用连开12书签（6文章/6视频）多窗口阅读的方式刷分，近期偶尔有分刷不满的现象，今日早上只开了6个**文章**书签多窗口阅读，放置一分钟后观看积分，发现关于**视频**的12分已全部获得，但关于**文章**的分数一分未取得。
之后尝试打开6个**视频**书签，然而并没有获得**文章**相关分数。

刷完文章后观看过网页，网页内容确实还是当时存为书签时的文章。
可以怀疑这个数据库中的链接条目类型发生了有意或无意的改动。

**Comment by Kurenai322** [comment]
经测试，打开**“理论学习”**下最新6篇**文章**，获得了全部12分**文章**相关分数。

看到前几个issue也反映了相同的问题，怀疑旧**文章**都已被标记为**视频**了。

**Comment by adslhuang** [comment]
原来的网页列表的文章，都不加分了，需要新的列表，隔壁已经有人找出问题了，修改代码以后正常了。
这里的人还在摸索

**Comment by Kurenai322** [comment]
> 
> 
> 原来的网页列表的文章，都不加分了，需要新的列表，隔壁已经有人找出问题了，修改代码以后正常了。
> 这里的人还在摸索

感谢回答，感觉这个对刷分脚本的反击略小儿科了。
不过对于自己写不出来的使用者确实能造成一点困扰吧。

我这里党员超3000分的被要求参加20分钟一百题的比赛了，感觉挺搞笑的。

**Comment by xuefliang** [comment]
@adslhuang 怎么修改源码？

**Comment by whhxmwhh** [comment]
Panda-Learning
有人改了。能用。我不会改。遗憾

**Comment by mouniga01** [comment]
> > 原来的网页列表的文章，都不加分了，需要新的列表，隔壁已经有人找出问题了，修改代码以后正常了。
> > 这里的人还在摸索
> 
> 感谢回答，感觉这个对刷分脚本的反击略小儿科了。
> 不过对于自己写不出来的使用者确实能造成一点困扰吧。
> 
> 我这里党员超3000分的被要求参加20分钟一百题的比赛了，感觉挺搞笑的。

能提供个链接吧？我们是菜鸟，看看怎么处理的。

**Comment by zidapang** [comment]
https://github.com/Alivon/Panda-Learning/issues/403

**Comment by TSiGua** [comment]
有没有大神能够修改一下呢？

**Comment by zz803abc** [comment]
同问

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#071---2019-06-23)。
