### ISSUE TITLE
新出的功能，需输入验证码有办法自动登录吗？

### ISSUE THREAD

**Issue by jzmswe** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#368]
请问作者大神有办法做到自动登录吗？搞定验证码就行，至于别的我自己就行。

**Comment by Hxd097** [comment]
验证码好烦啊，我说这两天怎么不能自动登录了

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#080---2019-07-16)。
