### ISSUE TITLE
这是啥错误？

### ISSUE THREAD

**Issue by zz803abc** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#370]
![image](https://user-images.githubusercontent.com/50546321/61170094-33d8c600-a597-11e9-8a3f-7b1bee794842.png)

**Comment by Fxxk-XueXiQiangGuo** [comment]
这些是内置 Chromium 浏览器的内部错误，不能算是报错，这些在任何基于 Electron 框架的程序中都会出现。

**Comment by Fxxk-XueXiQiangGuo** [comment]
libdbus 的问题不会影响运行结果，可以尝试安装或升级相关依赖库解决。
https://stackoverflow.com/questions/137773/what-does-the-no-version-information-available-error-from-linux-dynamic-linker
