### ISSUE TITLE
Windows版0.8照样提示输入验证码

### ISSUE THREAD

**Issue by Fr33raNg3r** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#373]
Windows版0.8照样提示输入验证码

**Comment by Fxxk-XueXiQiangGuo** [comment]
v0.8.0 更新后是仍然会出现验证码的，第一次尝试登录总是会提示输入验证码的。程序是会自动识别并输入验证码重试登录的。

**Comment by FLASH023** [comment]
> v0.8.0 更新后登录还是需要验证码的，第一次尝试登录总是会提示输入验证码的。程序是会自动识别并输入验证码重试登录的。

钉钉验证码有bug   不需要做识别。
只需要在  验证码输入框中输入任意两个字符中加一个空格   不管验证码是什么都会视为正确。
