### ISSUE TITLE
大家都是理工科党员吧～哈哈～检验你们党性的时刻啊！！

### ISSUE THREAD

**Issue by jerrychang125** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#38]

**Comment by Fxxk-XueXiQiangGuo** [comment]
党性不纯

**Comment by star2k** [comment]
> 党性不纯

能7*24*30挂着么，我想忘记这件事，可否？

**Comment by Fxxk-XueXiQiangGuo** [comment]
> > 党性不纯
> 
> 能7_24_30挂着么，我想忘记这件事，可否？

现在不可以，因为现在的登录有效期只有6个小时（cookie的过期时间只有6个小时）。我已经在着力解决这个问题，也许下一个版本。

**Comment by binlkevin** [comment]
> 
> 
> > > 党性不纯
> > 
> > 
> > 能7_24_30挂着么，我想忘记这件事，可否？
> 
> 现在不可以，因为现在的登录有效期只有6个小时（cookie的有效期只有6个小时）。我已经在着力解决这个问题，还需要进一步测试，也许会在下一个版本中解决。

真能这样就功德无量啦。

**Comment by noway2014** [comment]
真的很感谢这个软件的作者，父母为这个事情太辛苦太累了。

**Comment by fzs001** [comment]
请问cookie的目录存放在哪里？

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 请问cookie的目录存放在哪里？

Windows下的存放位置在 `%APPDATA%/fuck-xuexiqiangguo/Cookies`
Linux下在 `~/.config/fuck-xuexiqiangguo/Cookies`
Mac下在 `~/Library/Application Support/fuck-xuexiqiangguo/Cookies`

**Comment by Fxxk-XueXiQiangGuo** [comment]
> > 能7_24_30挂着么，我想忘记这件事，可否？
> 
> 现在不可以，因为现在的登录有效期只有6个小时（cookie的有效期只有6个小时）。我已经在着力解决这个问题，还需要进一步测试，也许会在下一个版本中解决。

已经解决。

**Comment by mdevc** [comment]
> > > 能7_24_30挂着么，我想忘记这件事，可否？
> > 
> > 
> > 现在不可以，因为现在的登录有效期只有6个小时（cookie的有效期只有6个小时）。我已经在着力解决这个问题，还需要进一步测试，也许会在下一个版本中解决。
> 
> 已经解决。

这个方式需要考虑反作弊吗？每天启动刷分是在固定时间吗？

**Comment by stonecai2019** [comment]
十分感谢作者，如果有可能希望paypal给些辛苦费，希望作者继续维护这个软件，每天工作8小时，还要花半小时来学习这个垃圾，真是受不了
