### ISSUE TITLE
开始封账号了，且行且珍惜吧！

### ISSUE THREAD

**Issue by eRenier** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#391]
今天被封了，正常刷分，题也做，每天41分，一样被封！且行且珍惜吧！

**Comment by jzmswe** [comment]
只要以前用过哪怕偶尔几次，就封，据说是这样。

**Comment by xzdbadboy** [comment]
凉凉

**Comment by yamieluo** [comment]
前天才开始用，还没封

**Comment by benladen** [comment]
我觉得这个软件挂机很难查出来，毕竟是模拟正常浏览网页版学习。但是不要挂机和答题同时。

**Comment by xzdbadboy** [comment]
> 我觉得这个软件挂机很难查出来，毕竟是模拟正常浏览网页版学习。但是不要挂机和答题同时。

还是被封了，郁闷四了

**Comment by awlways** [comment]
> > 我觉得这个软件挂机很难查出来，毕竟是模拟正常浏览网页版学习。但是不要挂机和答题同时。
> 
> 还是被封了，郁闷四了

显示封禁截止时间了吗，，，，

**Comment by dingzhao** [comment]
看下自己的积分记录，有没有出现1分钟之内得好几项分得，被封得都是学习得分太密得，不像在认证学习得

**Comment by gaowu9595** [comment]
显示“该账号涉嫌刷分，已被系统封禁，期间无法积分。”，被封了但是没显示时间，有谁知道这样要被封多久吗？

**Comment by eRenier** [comment]
> 显示“该账号涉嫌刷分，已被系统封禁，期间无法积分。”，被封了但是没显示时间，有谁知道这样要被封多久吗？

隔壁基本都是2个月左右，封了挺好的，不用刷，开会批评就交退档申请书

**Comment by FLASH023** [comment]
> 我觉得这个软件挂机很难查出来，毕竟是模拟正常浏览网页版学习。但是不要挂机和答题同时。

后台分分钟  识别出来
你用抓包工具看看文件头

**Comment by Kh3Bv** [comment]
除非辞职，出来单干，谁也管不着。

**Comment by Kh3Bv** [comment]
退也没用，除非辞职，出来单干，谁也管不着。@eRenier

**Comment by mouniga01** [comment]
也被封掉，昨天

**Comment by cryptoweirdo** [comment]
被封了，哭

**Comment by whhxmwhh** [comment]
没有用这个刷分怎么能得分呢？

**Comment by awlways** [comment]
现在问题是 什么时候才能解封吧。。。。

**Comment by xiami2156** [comment]
我之前被封过一次，一个半月。

在 2019-07-24 10:51:34，"MR.Z" <notifications@github.com> 写道：


显示“该账号涉嫌刷分，已被系统封禁，期间无法积分。”，被封了但是没显示时间，有谁知道这样要被封多久吗？

**Comment by jxnuzhouguohong** [comment]
用了2个多月了，一直正常，没被封，电脑挂机的时候，手机不玩其他页面

**Comment by yanguuu** [comment]
> > 我觉得这个软件挂机很难查出来，毕竟是模拟正常浏览网页版学习。但是不要挂机和答题同时。
> 
> 还是被封了，郁闷四了

你是正常挂机学习吗？还是有同时操作

**Comment by wdb1130** [comment]
被封应该是文章和答题之类的交差得分导致的吧? 不然怎么判断是刷分行为, 毕竟不是每个刷分的都被封了.

**Comment by gaowu9595** [comment]
> 被封应该是文章和答题之类的交差得分导致的吧? 不然怎么判断是刷分行为, 毕竟不是每个刷分的都被封了.

每次都是随机抽查，而且听说抽查的都会从最开始的记录开始检查，只要有刷分嫌疑的都会封

**Comment by xiaofei1122** [comment]
能到这里哪个不是翻墙出来的，都能这么通天了（按墙内的意见你不该在墙外的吧），还不会用这个软件避免被封吗？

**Comment by blackforest1840** [comment]
> 被封应该是文章和答题之类的交差得分导致的吧? 不然怎么判断是刷分行为, 毕竟不是每个刷分的都被封了.

我觉得你说的是有道理的，但是我现在已经不敢用了

**Comment by jxnuzhouguohong** [comment]
不用，叫我每天刷手机，实在吃不消啊


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: blackforest1840 <notifications@github.com>
发送时间: 2019年7月28日 12:08
收件人: fuck-xuexiqiangguo/Fuck-XueXiQiangGuo <Fuck-XueXiQiangGuo@noreply.github.com>
抄送: jxnuzhouguohong <76446382@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[fuck-xuexiqiangguo/Fuck-XueXiQiangGuo] 开始封账号了，且行且珍惜吧！ (#391)



 
被封应该是文章和答题之类的交差得分导致的吧? 不然怎么判断是刷分行为, 毕竟不是每个刷分的都被封了.
  
我觉得你说的是有道理的，但是我现在已经不敢用了

**Comment by RuYunW** [comment]
> 能到这里哪个不是翻墙出来的，都能这么通天了（按墙内的意见你不该在墙外的吧），还不会用这个软件避免被封吗？

github不墙

**Comment by yangyangtiaoguo** [comment]
封了也好

**Comment by zzqxztc** [comment]
> 用了2个多月了，一直正常，没被封，电脑挂机的时候，手机不玩其他页面

正解，挂着就好，别想图快，一天刷满都行，那些几分钟就满了的，不封你封谁。

**Comment by slightwangmin** [comment]
不爽退黨啊。

**Comment by zhongziqiang001** [comment]
求一个自动答题的代码

**Comment by holodfall** [comment]
> 显示“该账号涉嫌刷分，已被系统封禁，期间无法积分。”，被封了但是没显示时间，有谁知道这样要被封多久吗？

60天或90天

**Comment by ananymous1982** [comment]
> 
> 
> > 我觉得这个软件挂机很难查出来，毕竟是模拟正常浏览网页版学习。但是不要挂机和答题同时。
> 
> 还是被封了，郁闷四了


被封之前有没有手机APP 和 网页版 应用同时在使用的情况呢？

**Comment by ananymous1982** [comment]
> 
> 
> 用了2个多月了，一直正常，没被封，电脑挂机的时候，手机不玩其他页面

是只要不使用手机APP版xx就行了，还是手机里的其他应用也不要用啊?

**Comment by ananymous1982** [comment]
> 检查，只要有刷分

抽查是人工抽查吗？

**Comment by ananymous1982** [comment]
> 
> 
> 只要以前用过哪怕偶尔几次，比如几个月前，就封，据说是这样。

太恐怖了。

**Comment by Fxxk-XueXiQiangGuo** [comment]
实在是不好意思，我已经决定停止更新本项目了，见 #578 。  
多谢大家支持。
