### ISSUE TITLE
关于官方的封号判断

### ISSUE THREAD

**Issue by LryBackinblack** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#392]
【重要通知】近日，有部分单位反映“学习强国”平台学员账户被封。比较集中的原因有：
1.一个账号同时在两部及两部以上手机登录学习；
2.一部手机先后登录不同账号学习；
 3.一个账号同时在手机和电脑端登录学习；
 4.在“学习强国”电脑端同时打开多个窗口进行学习。

**Comment by baoang** [comment]
一部手机先后登录不同账号学习有什么问题？
一个账号同时在手机和电脑端登录学习又有什么问题？

如果这类做法要封号，那就是说这类做法是不允许的，这样细想下去，这个软件的目的应当在于强制你必须只能在一台手机且不能在电脑上同时使用，换句话说，关键在于手机本身，它是一个监控及定位工具。

**Comment by jh1633295941** [comment]
账号是永久封禁吗，怎么解决的
