### ISSUE TITLE
更新支持

### ISSUE THREAD

**Issue by wyssdbd** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#408]
希望支持Linux-arm系统!

**Comment by Fxxk-XueXiQiangGuo** [comment]
项目是[支持](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#%E4%B8%8B%E8%BD%BD)的，下载 `树莓派 (Linux armv7l)` 版本。
