### ISSUE TITLE
学习到一半会自动停止不学习

### ISSUE THREAD

**Issue by XiaoliChan** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#422]
学习到一半会自动停止不学习

**Comment by sandeli** [comment]
就是这个bug

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#101---2019-11-03)。
