### ISSUE TITLE
大神能不能稍微改下名字啊

### ISSUE THREAD

**Issue by rainbowmirage** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#424]
麻烦改下名字啦，每次打开软件，苹果标志的右边都会亮出一个大大的“fuck”😂😂😂
虽说学习很烦啦，但是里面的内容（尤其是科技军工块的）看看还是不错的嘛，
这软件初衷是好的，不如把软件名里的fuck去掉吧，就叫「xuexiqiangguo」吧

**Comment by Fxxk-XueXiQiangGuo** [comment]
已经[支持](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#101---2019-11-03)配置程序的显示名称，使用 `--appname=<name>` 命令行选项配置。

```
./Fuck学习强国  --appname="xuexiqiangguo"
```
