### ISSUE TITLE
为啥老是学习1-2分就不学了，我啥都没操作啊

### ISSUE THREAD

**Issue by feelinggod** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#425]

**Comment by lldojso** [comment]
一样

**Comment by LLLJJJYYY** [comment]
+1

**Comment by taizi-tp** [comment]
+1，本人发现从1号开始，刷分就失效了，无法正常刷分，希望作者这边检查一下

**Comment by hutaohutc** [comment]
> +1，本人发现从1号开始，刷分就失效了，无法正常刷分，希望作者这边检查一下

我这边时登入不了来，不会返回二维码。。

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#101---2019-11-03)。
