### ISSUE TITLE
反馈一些使用问题

### ISSUE THREAD

**Issue by Barrencastle** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#428]
首先，非常感谢您开发并更新这个应用，对于本来工作时间都非常繁忙的我来说，减少了很多烦恼，相信大家也都是这个情况。
这里反馈一些最近更新的版本使用方面的问题，主要就是**学习文章的时候不能模拟人的浏览操作**，在一篇文章之中不能够模拟阅读，而是反复切换文章，然后在某一篇之中完全停下来，导致阅读文章分数以及阅读时长的分数不能获得，而且影响了视频分数的获取，往往一次打开程序进行学习，几个小时过去后只能得到个位数的分数。
希望作者有时间能够修复这个问题。
幸苦了

**Comment by Barrencastle** [comment]
不知道其它人有没有遇到过这样的问题

**Comment by LLLJJJYYY** [comment]
+1

**Comment by feelinggod** [comment]
+1，之前v0.8给我删了，这个v1.0还不如v0.8，谁可以发个v0.8给我？

**Comment by ronggeyyy** [comment]
0.8的不能用了

**Comment by LifeC0ach** [comment]
+1

**Comment by hutaohutc** [comment]
扫不了二维码了，有一样问题的嘛

**Comment by wang173999** [comment]
+1

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#101---2019-11-03)。
