### ISSUE TITLE
阅读文章好像要看一分钟才能算

### ISSUE THREAD

**Issue by civiliann** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#429]
是直接秒看可能不算  没积分啊

**Comment by Fxxk-XueXiQiangGuo** [comment]
设计是至少 70 秒的，但是程序有 bug。

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#101---2019-11-03)。
