### ISSUE TITLE
因为是想在 Linux 服务器上跑这个，能否提供一个完全命令行的运行方式啊

### ISSUE THREAD

**Issue by songjave** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#443]
在服务器上运行必须要安装 GTK，但是我们基本上都是使用 SSH 上去的啊，不知道能不能麻烦提供一个完全使用命令行的方式啊

**Comment by ishowfun** [comment]
它这个东西的原理估计还是js定时刷新提交，你用命令行肯定不行的

**Comment by Fxxk-XueXiQiangGuo** [comment]
请阅读 [README#直接在命令行界面运行](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#%E7%9B%B4%E6%8E%A5%E5%9C%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E7%95%8C%E9%9D%A2%E8%BF%90%E8%A1%8C)。
