### ISSUE TITLE
v1.0.2 无法自动识别验证码

### ISSUE THREAD

**Issue by xinmeng** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#446]
这样就没法自动登录了，这个有解决办法吗？

![Untitled](https://user-images.githubusercontent.com/2274273/70585887-9c88a500-1c00-11ea-9fb0-a0a7a6421cca.png)

**Comment by Barrencastle** [comment]
出现同样的问题

**Comment by yangxinyujy** [comment]
来人解决一下吧，这个不麻烦

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#103---2020-05-17)。
