### ISSUE TITLE
反馈一个使用问题，并提供一个建议

### ISSUE THREAD

**Issue by Barrencastle** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#452]
问题：使用账号登录时，验证码识别后自动输入出现“undefined”，无法实现自动登录。
建议：添加手动输入验证码功能

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经解决无法识别验证码的问题](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#103---2020-05-17)。
