### ISSUE TITLE
学习强国学习二字是谁写的？

### ISSUE THREAD

**Issue by bbfxier** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#477]

**Comment by xiaxudong175** [comment]
I think you can serach it by Google photo search

**Comment by bbfxier** [comment]
> I think you can serach it by Google photo search

我觉得你是个假洋鬼子。。。
没用的，搜不到，习近平写自己签名就爱用繁体，但是我不是专业的，看不出来是不是同一个人写的

**Comment by Gnothi-Seauton** [comment]
「习的签名，是模仿毛体的。」
https://hanweb.kanhan.com/TuniS/gbcode.rthk.hk/TuniS/app3.rthk.hk/mediadigest/content.php?aid=2164

**Comment by bbfxier** [comment]
> 「习的签名，是模仿毛体的。」
> https://hanweb.kanhan.com/TuniS/gbcode.rthk.hk/TuniS/app3.rthk.hk/mediadigest/content.php?aid=2164

你不会是钓鱼执法的吧，我都打不开，翻墙了也打不开

**Comment by bbfxier** [comment]
> 「习的签名，是模仿毛体的。」
> https://hanweb.kanhan.com/TuniS/gbcode.rthk.hk/TuniS/app3.rthk.hk/mediadigest/content.php?aid=2164
没办法插图，习近平写自己签名是用繁体字，但是学习的习很瘦，他自己的签名的习，矮胖。
习近平自己的签名
https://matters.news/@qg32117/%E7%AC%94%E8%BF%B9%E9%89%B4%E5%AE%9A-%E4%BB%8E%E6%AF%9B%E5%88%B0%E4%B9%A0-zdpuAumBrAgVCdHcRLdWuUYKd2s4EGTAzuBpuR3meaDDEKMAD
https://www.google.com/search?q=%E4%B9%A0%E8%BF%91%E5%B9%B3+%E7%AD%BE%E5%90%8D&tbm=isch&source=univ&sa=X&ved=2ahUKEwjalrnV5OznAhVlg-AKHZDcDwIQsAR6BAgKEAE&biw=1366&bih=695
https://news.qq.com/a/20141119/046182.htm
学习强国的习
https://www.xuexi.cn/
