### ISSUE TITLE
cannot execute binary file: Exec format error!

### ISSUE THREAD

**Issue by Anway2** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#482]
ubuntu 32位系统，按主页指引操作线上安装，最后弹出“bash: ./Fuck学习强国: cannot execute binary file: Exec format error”，无法fuck！看issues也有人遇到此类问题，但也一头雾水。
why？关键是How？
谢谢！

**Comment by muwuren** [comment]
这个程序是64位的
`Fuck学习强国: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, stripped`

**Comment by Fxxk-XueXiQiangGuo** [comment]
是 64 位的。现在 32 位的 Ubuntu 很少了吧，而程序的 Windows 版是 32 位的，因为 64 位 Windows 开箱支持运行 32 位程序，二是考虑到单位的老电脑很多都只有 32 位的 Windows 7。
