### ISSUE TITLE
使用过程中，不小心断网，再重新登陆，无法刷。

### ISSUE THREAD

**Issue by MouMouNan** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#485]
![P00318-150859(1)](https://user-images.githubusercontent.com/62325521/76934657-7e7ebf00-692a-11ea-96ed-95a9aa90cd08.jpg)

重新登陆，退出防火墙登陆，各种登陆都不行。

**Comment by whhxmwhh** [comment]
先要退出学习。然后重新来过。

**Comment by MouMouNan** [comment]
收到，感谢回复

whhxmwhh <notifications@github.com> 于 2020年3月25日周三 09:42写道：
