### ISSUE TITLE
已被封号

### ISSUE THREAD

**Issue by liyiliuxingyu** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#491]
请不要使用

**Comment by yanxublack** [comment]
从未出现过，使用了差不多一年了

**Comment by Yancy-19** [comment]
大兄弟给张图出来啊？一句话摆在这是不是有点不负责任？

**Comment by liyiliuxingyu** [comment]
> 大兄弟给张图出来啊？一句话摆在这是不是有点不负责任？

![微信图片_20200416084707](https://user-images.githubusercontent.com/21255612/79402580-e292b280-7fbe-11ea-8b16-a4a369c6a124.jpg)
这回可以了？相信了？我怎么个不负责任？？你说

**Comment by danjuanyang** [comment]
嗐，这下就不知道多久不好了，难受

**Comment by T147258** [comment]
有点慌

**Comment by ciao1** [comment]
@liyiliuxingyu 大兄弟是一个人刷分吗？还是多个刷分，给点具体线索。我现在刷着有点慌啊

**Comment by liyiliuxingyu** [comment]
> @liyiliuxingyu 大兄弟是一个人刷分吗？还是多个刷分，给点具体线索。我现在刷着有点慌啊

一个人啊

**Comment by liyiliuxingyu** [comment]
> > @liyiliuxingyu 大兄弟是一个人刷分吗？还是多个刷分，给点具体线索。我现在刷着有点慌啊
> 
> 一个人啊

也是在组织里面

**Comment by T147258** [comment]
> 有点慌

太难了,兄弟有其他好用的了 吱一声呗,,,我好想刷题

**Comment by jrmd79** [comment]
卧槽，看到这个消息让我肛门一紧！

**Comment by antaluqi** [comment]
> > 大兄弟给张图出来啊？一句话摆在这是不是有点不负责任？
> 
> 
> 
> ![微信图片_20200416084707](https://user-images.githubusercontent.com/21255612/79402580-e292b280-7fbe-11ea-8b16-a4a369c6a124.jpg)
> 
> 这回可以了？相信了？我怎么个不负责任？？你说

是不是一边挂机一边做题，系统检测到同时得分的情况多的话会封号，

**Comment by zhongxiang1206** [comment]
瞬间不敢用了

**Comment by CNzxy0820** [comment]
被封了几天,啥情况被封的,有啥特殊操作吗

**Comment by MingJoy** [comment]
是不是电脑一边刷，题目一边做啊……

**Comment by LiXin1993730** [comment]
大兄弟是按正常规则做吗？还是手机也同时做被检测到了？给大家点有用的信息啊！感谢

**Comment by BBSMLtd** [comment]
吓得我肛门一紧

**Comment by liyiliuxingyu** [comment]
> > > 大兄弟给张图出来啊？一句话摆在这是不是有点不负责任？
> > 
> > 
> > 
> > ![微信图片_20200416084707](https://user-images.githubusercontent.com/21255612/79402580-e292b280-7fbe-11ea-8b16-a4a369c6a124.jpg)
> > 
> > 这回可以了？相信了？我怎么个不负责任？？你说
> 
> 是不是一边挂机一边做题，系统检测到同时得分的情况多的话会封号，

谁不是一边挂机一边做，答题都要做才能达到要求

**Comment by nandesiga** [comment]
不看回复，盲猜lz是边挂机边刷题了，这是必死操作，请后来者不要作死

**Comment by Fxxk-XueXiQiangGuo** [comment]
实在是不好意思，我已经决定停止更新本项目了，见 #578 。  
多谢大家支持。
