### ISSUE TITLE
代码不开源吗

### ISSUE THREAD

**Issue by NeilXu2888** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#498]
代码不能开源吗？不开源的东西不敢用呀

**Comment by Hoexhe** [comment]
> 代码不能开源吗？不开源的东西不敢用呀
源码在另一个仓库
https://github.com/fuck-xuexiqiangguo/source-code

**Comment by NeilXu2888** [comment]
好的 谢谢啦
