### ISSUE TITLE
建议支持订阅，收藏，分享，功能这几个功能

### ISSUE THREAD

**Issue by locxiang** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#5]

**Comment by jiejie2004** [comment]
pc版本来不支持这些功能。coder也没办法弄的。

**Comment by fyu0h** [comment]
这几个功能必须手机版吧

**Comment by Fxxk-XueXiQiangGuo** [comment]
这几个功能目前必须使用手机版 APP，以后会考虑通过伪造数据包支持

**Comment by XueTeng2** [comment]
建议在窗口最下方显示目前刷了多少分。

**Comment by supppig** [comment]
> 这几个功能目前必须使用手机版 APP，以后会考虑通过伪造数据包支持

不建议伪造数据包，怕封号。现在已经在打击了。如果以后能伪造数据包，要希望留一个开关。

**Comment by noway2014** [comment]
学习强国实在是让人太辛苦了特别是年纪大的眼睛也不好。希望能增加功能，并做好防御，因为现在已经开始防止刷分了，要研究如何提防。好用的话一定捐助

**Comment by noway2014** [comment]
运行程序，会打开一个窗口，似乎一直在那个学习窗口，不能自动看视频或者看文章。需要不断自己选择文章阅读吗？并非自动？

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 学习强国实在是让人太辛苦了特别是年纪大的眼睛也不好。希望能增加功能，并做好防御，因为现在已经开始防止刷分了，要研究如何提防。好用的话一定捐助

捐助会暴露许多个人信息，所以不接受捐助

**Comment by bluef1ash** [comment]
> > 学习强国实在是让人太辛苦了特别是年纪大的眼睛也不好。希望能增加功能，并做好防御，因为现在已经开始防止刷分了，要研究如何提防。好用的话一定捐助
> 
> 捐助会暴露许多个人信息，所以不接受捐助

可以用PayPal

**Comment by shangming-wang** [comment]
我是不会用这个工具的，我都是自愿学习的。点击star和下载是为了警醒自己要远离诱惑，要实事求是，绝不弄虚作假。

**Comment by Fxxk-XueXiQiangGuo** [comment]
> > > 学习强国实在是让人太辛苦了特别是年纪大的眼睛也不好。希望能增加功能，并做好防御，因为现在已经开始防止刷分了，要研究如何提防。好用的话一定捐助
> > 
> > 
> > 捐助会暴露许多个人信息，所以不接受捐助
> 
> 可以用PayPal

PayPal也一样，因为绑定了真实银行卡信息。可以考虑使用加密电子货币。

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 我是不会用这个工具的，我都是自愿学习的。点击star和下载是为了警醒自己要远离诱惑，要实事求是，绝不弄虚作假。

如果你认为你的时间不值钱，没有人拦着你手动学刁。

**Comment by twinfishxixi** [comment]
> > 我是不会用这个工具的，我都是自愿学习的。点击star和下载是为了警醒自己要远离诱惑，要实事求是，绝不弄虚作假。
> 
> 如果你认为你的时间不值钱，没有人拦着你手动学刁。

这哥们是说的反话啊，楼主！哈哈哈！

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 这哥们是说的反话啊，楼主！哈哈哈！

我可能缺乏幽默细胞，没意识到这是反话啊。哈哈。

**Comment by jianxuanbing** [comment]
自己写一个还是可以滴，模拟操作

**Comment by gantrylueng** [comment]
> > 这哥们是说的反话啊，楼主！哈哈哈！
> 
> 我可能缺乏幽默细胞，没意识到这是反话啊。哈哈。

楼主这样是不是更可爱？
论理工科党员的基本修养。现在不会正话反说，都已经不能说话了都，唉。

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 建议在窗口最下方显示目前刷了多少分。

[已经支持](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#060---2019-03-30)。
