### ISSUE TITLE
交流学刁的最佳实践

### ISSUE THREAD

**Issue by ananymous1982** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#513]
好想自动学刁，怕被检测到。有老铁分享自动学刁的经验吗？

**Comment by HolmesZhao** [comment]
用这个项目挂机, 然后关闭APP 后台, 然后分数够了, 再打开, 自己写个自动答题就行了

**Comment by whhxmwhh** [comment]
第二窗口的二维码出不来了。刷新了也是一样出不来。程序可能改了。
