### ISSUE TITLE
强烈建议作者不要夹带个人政治目的

### ISSUE THREAD

**Issue by GengchenXU** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#514]
看待事物要用发展的眼光看，有时候让子弹再飞一会不是更好吗？就拿这次疫情来说，疫情初期确实做的不好，老百姓也知道网上民怨也很沸腾，可是我们的制度有自己的优势啊，你看现在的除了方方那种死要面子活受罪的，百姓都承认这次中共确实做的很好，毕竟没人想活成欧美那个样。生存权才是最大的人权

**Comment by ArcSinZero** [comment]
强烈支持作者表达个人政治观点的自由
