### ISSUE TITLE
发现学习的速度比较慢，是有意采取的学习策略绕过封号吗

### ISSUE THREAD

**Issue by ananymous1982** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#518]
发现自动学习学两小时也没学多少分，是脚本故意不在短时间里学很多分吗？

**Comment by ananymous1982** [comment]
是不是学习的时候不能将窗口最小化。窗口非最小化的状态下，短时间内学了2分。

**Comment by Merck-Lewis** [comment]
请问win7   64位  下下来  怎么运营不了啊  点exe文件没反应

**Comment by whhxmwhh** [comment]
> 是不是学习的时候不能将窗口最小化。窗口非最小化的状态下，短时间内学了2分。
是这样的。默认窗口，或者最大化都可以的。

**Comment by zuxingshui** [comment]
> > 是不是学习的时候不能将窗口最小化。窗口非最小化的状态下，短时间内学了2分。
> > 是这样的。默认窗口，或者最大化都可以的。

你好，我现在打不开作者内容，下载不了，不知方便分享你现在用的版本给我么，谢谢，970717654@qq.com，

**Comment by zuxingshui** [comment]
> 发现自动学习学两小时也没学多少分，是脚本故意不在短时间里学很多分吗？

你好，我现在打不开作者内容，下载不了，不知方便分享你现在用的版本给我么，谢谢，970717654@qq.com，

**Comment by ananymous1982** [comment]
> 
> 
> 请问win7 64位 下下来 怎么运营不了啊 点exe文件没反应

可以新建issue反馈一下? 我的电脑系统是 win 10 64位。

**Comment by ananymous1982** [comment]
> 
> 
> > 发现自动学习学两小时也没学多少分，是脚本故意不在短时间里学很多分吗？
> 
> 你好，我现在打不开作者内容，下载不了，不知方便分享你现在用的版本给我么，谢谢，[970717654@qq.com](mailto:970717654@qq.com)，

github 下载链接可以直接访问，就是下载慢一点。如果不方便上网，可以找shadowsocks服务， 或者v2ray 服务，或者买vpn也行。
