### ISSUE TITLE
能不能出答题功能？

### ISSUE THREAD

**Issue by xiehuajieaa** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#535]
如题

**Comment by ming871** [comment]
要求太高了，很复杂的，涉及到AIＡＩ

**Comment by EasonTong** [comment]
> 要求太高了，很复杂的，涉及到AI

应该就是个题库吧，他的问题也不能是自动生成的

**Comment by corgy-w** [comment]
> > 要求太高了，很复杂的，涉及到AI
> 
> 应该就是个题库吧，他的问题也不能是自动生成的

题库是实时的
这个不好搞

**Comment by xiehuajieaa** [comment]
哦哦！



---原始邮件---
发件人: "corgy"<notifications@github.com&gt;
发送时间: 2020年12月2日(周三) 下午4:28
收件人: "fuck-xuexiqiangguo/Fuck-XueXiQiangGuo"<Fuck-XueXiQiangGuo@noreply.github.com&gt;;
抄送: "xiehuajieaa"<2275808037@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo] 能不能出答题功能？ (#535)




   
要求太高了，很复杂的，涉及到AI
  
应该就是个题库吧，他的问题也不能是自动生成的
  
题库是实时的
 这个不好搞

**Comment by PRaichu** [comment]
> 哦哦！

这个支持答题，一天45分   https://github.com/PRaichu/xxqg

**Comment by Fxxk-XueXiQiangGuo** [comment]
实在是不好意思，我已经决定停止更新了，见 #578 。  
（请原谅我有一些自私，因为我身边的人都已经不再强制要求使用学刁强国了。如果再次被强制使用，我可能才会改变主意。）
