### ISSUE TITLE
要求习近平同志辞去党和国家领导职务

### ISSUE THREAD

**Issue by sizukari** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#54]
习近平同志，你好。

　　我们是忠诚的共产党员。值此全国“两会”召开之际，我们给你写这封信，要求你辞去所有党和国家领导职务。提出这个要求，是出于党的事业的考虑，是出于国家和民族前途的考虑，同样，也是出??于你和你家人自身安全的考虑。

　　习近平同志，你自2012年在党的“十八大”当选新一届的中央委员会总书记以来，立志反腐打老虎，党内的贪污腐败等不正之风有所好转。你亲自出任中央全面深化改革领导小组等多个小组的组长，为经济发展也做了大量的工作，得到了一些老百姓的拥戴，这些我们都看在了眼裡。

　　但是，习近平同志，我们不得不指出的是，正是因为你用这种方式，将权力全面抓到了自己的手裡，直接决策，在政治经济思想文化等各个领域，都造成了前所未有的问题和危机。

　　政治上，你抛弃了党的优良传统，其中最显着的是让各级领导表态支持你为核心，抛弃了以民主集主制为核心的常委会集体领导原则，权力过分集中。你在强化人大政协国务院党组职能的同时，弱化了国家各权力机关的独立性，包括国务院总理李克强在内等同志的职权受到了很大影响。与此同时，中纪委派驻各机关单位和国企的巡视组成了新的权力体系，导致各级党委政府权责不清，决策溷乱。

　　外交上，你抛弃了邓小平同志“韬光养晦”的一贯方针，盲目出手，不仅没能创造良好的周边国际环境，还让朝鲜成功进行了原子弹和导弹的试验，形成对中国国家安全的巨大威胁；也让美国成功重返亚洲，与南朝鲜、日本、菲律宾及东南亚各国形成统一战线，联手遏制中国。在处理港澳台问题上，没有遵从邓小平同志英明的“一国两制”构想，进退失据，从而导致民进党获得台湾政权，香港独立势力抬头。特别是在香港问题上，以非正常方式把香港书商带回内地，对“一国两制”构成了直接的伤害。

　　经济上，你通过中央财政经济领导小组，直接参与宏观和微观经济政策的製订，导致了中国股市楼市的巨幅动盪，老百姓数以十万计的财富化为乌有，哀鸿遍野。供给侧改革及去产能政策，导致国企央企职工大量下岗；民营企业倒闭成风，大量人员失业。“一带一路”战略，把大量的外汇储备投入溷乱的国家和地区，不见回报。外汇储备过度消耗，人民币进入贬值週期，大家的信心日渐低落，国民经济陷入即将崩溃的境地，人心思变。

　　在思想文化上，你强调“媒体姓党”，而无视媒体的人民性，举国愕然；你扶持周小平花千芳这样水平较低的人成为文艺战线的代表，让广大文艺工作者心寒；你纵容文化单位直接给你唱讚歌，你的爱人彭丽媛的妹妹出任中央电视台春节联欢晚会的製片主任，使本来大家喜闻乐见的春晚成为你个人的宣传工具。你这些纵容个人崇拜，不许“妄议中央”，搞“一言党”的做法，让我们这些经历过“文化大革命”的人不禁暗自揪心——我们的党、国家和民族再也经不起新的十年浩劫！。

　　习近平同志，你推行高压反腐，对纠正党的不正之风有帮助作用，但是，因为没有配套措施跟上，客观上，也造成了目前各级政府消极怠工的现像，官员怕事不办事，老百姓怨声载道，也进一步加剧了经济形势的恶化。我们也看到，现在的反腐，目标只集中在权力斗争。我们担心，这种加剧党内权力斗争的做法，也可能给你和你的家人带来人身安全上的隐患。

　　因此，我们认为，习近平同志你不具备带领党和国家走向未来的能力，不适合再担任总书记一职。我们要求你为了党的事业兴旺发达，为了国家的长治久安，为了你和你家人的安全，辞去所有的党和国家的职务，让党中央及全国人民另选贤能，带领我们积极进取，走向未来。

　　忠诚的共产党员

**Comment by hongyuatcufe** [comment]
看着很解气，但还是多讨论技术和bug吧，历史会给大家答案

**Comment by CT-ABT** [comment]
这是好多年前的老文了……

**Comment by loocer** [comment]
大家好 我是楼主的爸爸 楼主因为欠下赌债 被海外间谍利用 试图诋毁和分裂国家 请大家不要听他瞎逼逼

**Comment by njzjz** [comment]
已向中央网信办（report.12377.cn）举报你的账号，查询码：15419030615281000063

**Comment by njzjz** [comment]
![814f9653-f807-41a3-bc63-c3d53d73ec43](https://user-images.githubusercontent.com/9496702/53863344-ed8dbc00-4024-11e9-977a-05c77ef9e078.png)

**Comment by wangty6** [comment]
笑死我了，楼主小学毕业了么？

**Comment by jieli4970** [comment]
这个APP不是挺好的吗？看权威新闻啥的还是很方便的～～

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 这个APP不是挺好的吗？看权威新闻啥的还是很方便的～～

中共权威新闻 != 真实新闻

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 这个APP不是挺好的吗？看权威新闻啥的还是很方便的～～

可信度极低，客观度为0。

**Comment by bingoku** [comment]
这里不是反共了，是反华了，GitHub 危在旦夕了。

**Comment by AndyLockhart** [comment]
还是不要那么作死，一会github被封了大家都玩完

**Comment by sizukari** [comment]
> 已向中央网信办（report.12377.cn）举报你的账号，查询码：15419030615281000063

感谢您的支持，我以后将不遗余力的伤害以习近平为核心的党中央和大陆粉红的感情！

**Comment by sizukari** [comment]
> 这里不是反共了，是反华了，GitHub 危在旦夕了。

习=华？川普=美？哪个老师教给你的？

**Comment by jsuyanyong** [comment]
这是要把github推向墙外的节奏啊?

**Comment by sunwukongop** [comment]
> > 已向中央网信办（report.12377.cn）举报你的账号，查询码：15419030615281000063
> 
> 感谢您的支持，我以后将不遗余力的伤害以习近平为核心的党中央和大陆粉红的感情！
川普。。你是湾湾?

**Comment by njzjz** [comment]
如果你不是中共党员，或者不是中华人民共和国公民，我想你没有资格用一个刚刚注册的三无账号，对我党和我国的职务说三道四。不干涉内政是《联合国宪章》和《国际法原则宣言》的基本原则。

如果你是中共党员，或者中华人民共和国公民，请遵守中华人民共和国的法律。如果你认为你已经很好的遵守了，你可以无视我对你的举报。如果你不想遵守中华人民共和国法律，你可以选择失去中华人民共和国国籍。

请不要使用这种零repo、零followers、零commit的三无小号发言，这样显得你是五毛水军。

**Comment by KINGJIN2017** [comment]
> report.12377.cn

fuck you

**Comment by 55380855** [comment]
github没墙真是个奇迹

**Comment by hshx123** [comment]
> github没墙真是个奇迹

要是有墙…国内多少开发者完蛋🤔

**Comment by xijinping0** [comment]
sizukari 同志，你好。

我是习近平。你的来信我已收到，写得非常诚恳。

但是你还是 too young，还是要多学习。为了连任我谋划多年，2018 年就把宪法给改了，今年更是以疫情为借口，把全国都封得死死的。那个上海，自以为经济搞得不错，和中央叫板，结果还不是被我派去的春兰同志收拾得服服帖帖。现在二十大近在眼前，我马上就要实现我的帝王梦（年号庆丰），你让我下台？你啊，naive！

小王，把这里的人员记录一下，拉个清单。等我连任之后，加急处理！

----

[![突开](https://img.youtube.com/vi/B8V4rrKuTkE/0.jpg)](https://youtu.be/B8V4rrKuTkE?t=113)

推荐阅读：《[习近平与他的情人们](https://xijinping0.github.io/lovers/docs/toc)》
更多资讯：[xijinping0](https://github.com/xijinping0)

**Comment by emperorboy888** [comment]
已经收到您的邮件，谢谢~~！！
