### ISSUE TITLE
“学习强国”学习平台自2020年9月1日起整顿用户获取学习积分的行为，对违规刷分的用户采取封禁、积分清零或永久封禁等处罚。

### ISSUE THREAD

**Issue by ChesterZero** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#548]
求教fuck学习强国刷分是否会被检测到？

怎样算违规刷分？
利用非法软件、模拟器、买卖账号假学，同时多开浏览器等方式获取学习积分属于违规刷分。
第一次违规：实名认证+警告
用户进行实名认证，并通过强国助手发送消息警告；已实名认证的用户，强国助手消息警告。
...

**Comment by Fxxk-XueXiQiangGuo** [comment]
这个提示不是第一次出現了。主要是威慑和恐吓的作用。

**Comment by Fxxk-XueXiQiangGuo** [comment]
求教，`非法软件`们违反了什么法律了？
中国是不是有一种`必须旗帜鲜明地接受习近平思想洗脑`法？

**Comment by ChesterZero** [comment]
> 这个提示不是第一次出现了。主要是威慑和恐吓的作用。

好的~多谢~
