### ISSUE TITLE
巴拿马文件：中国资金是如何逃到海外？

### ISSUE THREAD

**Issue by sizukari** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#55]
在香港银行大楼的背景下，有一排排的兑换外币的店铺，进行着快速和匿名的一些交易。

这个景象的背后，是数额更大的资金以史无前例的速度在转移。内地的财富经过香港或海外的外汇交易商外流。去年，有大约一万亿美元资金从中国外流，令外汇储备缩水。

这一变化可能会动摇中国的整体经济。

莫萨克·冯赛卡（Mossack Fonseca）泄露出来的文件，让我们了解到中国领导人的家人如何把钱转到海外。

至少7名现任和前任领导人与这家巴拿马公司所设立的离岸公司有牵连，包括中国国家主席习近平和另两名领导人。

这项丑闻涉及的中国现任及前任领导人家族成员：
现任领导人：
习近平（中国国家主席）——姐夫邓家贵是两家离岸公司的董事及股东。
刘云山（中共中央政治局常委）——儿媳妇贾丽青是一家离岸公司的董事和股东。
张高丽（中共中央政治局常委）——女婿李圣泼是3家离岸公司的股东。
前任领导人：
李鹏（国务院总理：1987年至1998年）——女儿李小琳是一家离岸公司的董事和股东。
贾庆林（中国政协主席：2002年至2012年）——外孙女李紫丹拥有一家离岸公司。
曾庆红（国家副主席：2002年至2007年）——胞弟曾庆淮是一家离岸公司的董事。
胡耀邦（党总书记：1982年至1987年）——三儿子胡德华是一家离岸公司的董事和股东。
这些名字此前在与离岸银行相关的报道中出现。但是，新文件泄露的时机对中国领导人来说比较棘手。

中国领导人家族利用“避税天堂”
中国：“巴拿马文件”捕风捉影 不作评论

拥有离岸公司在中国并不违法，但这些隐秘金融机构的存在给中国领导人的家庭提出了各种疑问。

根据党章，中国共产党的官员应该“廉洁”，不能从以权谋私，他们的家属也不能从与高层的关系中获利。

香港城市大学政治评论员林和立说，习近平把自己塑造成“一个在道德和廉洁上纯粹的人”。

他说，在海外帐户上存放着大量的资金“明显与习近平的要求和共产党的传统相悖”。

“至于高官子女是否非法取得财富，这很难说，毕竟中国司法体系太隐晦。”

图片版权AP
Image caption
莫萨克·冯赛卡公司帮助习近平的姐夫邓家贵在英属维尔京群岛上设立了三家离岸公司。（资料图片）
资本逃逸
巴拿马文件透露了更多的关于中国权贵阶层海外资金状况。大批的电子邮件显示，莫萨克·冯赛卡（Mossack Fonseca）公司没有按照国际法的要求，在没有做背景调查的情况下，长期帮助一些有政治关系的客户成为离岸公司的股东。

比如，莫萨克·冯赛卡帮助习近平的姐夫邓家贵在英属维尔京群岛上设立了三家离岸公司。

但是，莫萨克·冯赛卡在2004年和2009年帮助邓家贵购买公司的时候，并没有调查邓与中共高层的关联。

尚不清楚这三家公司是被用来做什么的，尽管其中一家已解散，另两家在习近平2012年担任中共中央总书记后成为休眠公司。

这其中的讽刺意味很明显：自从习近平上台后，他在党内展开了密集的反腐运动，仅2015年，就有超过30万官员因违反反腐条例被惩处。

在莫萨克·冯赛卡发生的事情也在别的地方被复制。富有的中国人利用香港作为跳板，将资金挪到海外，以便保护他们的财产。

在香港的独立中国分析员安德鲁·科利尔（Andrew Collier）说：“把钱放在中国通常有两点担心。第一，中国经济放缓；第二，中国领导层试图清理腐败，有些人担心钱放在中国不安全，因此要把资金挪到海外。”

香港成为中国封堵资金外流的焦点。上月，中国反贪官员表示，外流的资金大多途经香港，并表示要阻止这一势头，尽管这可能很难做到。

“出现恐慌”
尽管中国的银行加强管控，去年大约有6.5亿美元的资金离开中国。中国公民每年只能五万美元的外汇额度，超过这个限额的资金转移就是违法。有些人利用复杂的转帐来将资金转移出境。

一名非法外汇交易员告诉我们，他是如何通过在中国、香港、越南和菲律宾的大批“僵尸”账户将资金秘密转到海外。

他利用那些已去世的人的名下账户，来确保无法追查到他自己。

他笑着说：“我将客户的钱存到某个国家的某个账户，然后兑换后将钱存到另一个国家的另一个帐户。”

但是，他不再接受那些试图把人民币从中国转移到海外的生意了。

他皱着眉头说：“我已经有了太多的人民币。”

如果中国对他这样的人采取打压，更严格地执法会怎么样呢？

他说：“恐慌，那就会有恐慌。”

图片版权AFP
Image caption
北京国际机场。（资料图片）
钱骡
资本流动的背后是焦虑。

林和立说：“人们对金融和经济决策团队的能力没有信心。如果他们有一、两百万美元，不在海外存放一半的资金那就是愚蠢的，因为他们对党的未来没有什么信心。”

那些无法得到大牌外汇交易员服务的人，就依靠“钱骡”来帮助他们把钱弄到海外。我们见到了一名钱骡，他告诉我们他业务繁忙，帮助焦虑的客户把钱挪到海外。

“如果我的客户想移民，或者在境外投资，他们就需要我的帮助。”

“有时我把现金绑在身上，或者装进一个小袋子里。海关人员经常针对行李很多的人、或看上去紧张的人来检查，所以我就尽量保持镇静。”

中国最富裕的人把钱转移到海外有何影响呢？

钱一旦离开的中国，就必须有一个去向。

大量资金外流推高了全球的房价。根据从事华人海外购房生意的居外海外房产网（juwai.com）介绍，中国买家去年花费520亿美元购买境外房产。

在香港，来自内地的中国人挥重金购买高端房产。这在其它地方也是如此——中国最富裕的人在各地存放和消费他们资金，也许包括最高层的人。

他们试图保护自己，但这让中国变得更脆弱。

**Comment by sizukari** [comment]
https://www.bbc.com/zhongwen/simp/china/2016/04/160406_panama_papers_china_capital_outflows

**Comment by samos1808** [comment]
真正的最大的盜國賊是王岐山等人。詳見郭文貴爆料。
https://www.youtube.com/channel/UCO3pO3ykAUybrjv3RBbXEHw

**Comment by samos1808** [comment]
郭文貴爆料視頻和文字:
https://github.com/ourhimalayas/txt

**Comment by Fxxk-XueXiQiangGuo** [comment]
这种文章还是建议不要在这里发。当然我也不会主动删除它。随想君的 zhao 就是因为某个 issue 中的某种原因（[诽谤刁斤干杀人？](https://github.com/github/gov-takedowns/blob/master/China/2016/2016-06-08-programthink-zhao.md)）在中国大陆被 takedown 的。

**Comment by ddzy** [comment]
> 在香港银行大楼的背景下，有一排排的兑换外币的店铺，进行着快速和匿名的一些交易。
> 
> 这个景象的背后，是数额更大的资金以史无前例的速度在转移。内地的财富经过香港或海外的外汇交易商外流。去年，有大约一万亿美元资金从中国外流，令外汇储备缩水。
> 
> 这一变化可能会动摇中国的整体经济。
> 
> 莫萨克·冯赛卡（Mossack Fonseca）泄露出来的文件，让我们了解到中国领导人的家人如何把钱转到海外。
> 
> 至少7名现任和前任领导人与这家巴拿马公司所设立的离岸公司有牵连，包括中国国家主席习近平和另两名领导人。
> 
> 这项丑闻涉及的中国现任及前任领导人家族成员：
> 现任领导人：
> 习近平（中国国家主席）——姐夫邓家贵是两家离岸公司的董事及股东。
> 刘云山（中共中央政治局常委）——儿媳妇贾丽青是一家离岸公司的董事和股东。
> 张高丽（中共中央政治局常委）——女婿李圣泼是3家离岸公司的股东。
> 前任领导人：
> 李鹏（国务院总理：1987年至1998年）——女儿李小琳是一家离岸公司的董事和股东。
> 贾庆林（中国政协主席：2002年至2012年）——外孙女李紫丹拥有一家离岸公司。
> 曾庆红（国家副主席：2002年至2007年）——胞弟曾庆淮是一家离岸公司的董事。
> 胡耀邦（党总书记：1982年至1987年）——三儿子胡德华是一家离岸公司的董事和股东。
> 这些名字此前在与离岸银行相关的报道中出现。但是，新文件泄露的时机对中国领导人来说比较棘手。
> 
> 中国领导人家族利用“避税天堂”
> 中国：“巴拿马文件”捕风捉影 不作评论
> 
> 拥有离岸公司在中国并不违法，但这些隐秘金融机构的存在给中国领导人的家庭提出了各种疑问。
> 
> 根据党章，中国共产党的官员应该“廉洁”，不能从以权谋私，他们的家属也不能从与高层的关系中获利。
> 
> 香港城市大学政治评论员林和立说，习近平把自己塑造成“一个在道德和廉洁上纯粹的人”。
> 
> 他说，在海外帐户上存放着大量的资金“明显与习近平的要求和共产党的传统相悖”。
> 
> “至于高官子女是否非法取得财富，这很难说，毕竟中国司法体系太隐晦。”
> 
> 图片版权AP
> Image caption
> 莫萨克·冯赛卡公司帮助习近平的姐夫邓家贵在英属维尔京群岛上设立了三家离岸公司。（资料图片）
> 资本逃逸
> 巴拿马文件透露了更多的关于中国权贵阶层海外资金状况。大批的电子邮件显示，莫萨克·冯赛卡（Mossack Fonseca）公司没有按照国际法的要求，在没有做背景调查的情况下，长期帮助一些有政治关系的客户成为离岸公司的股东。
> 
> 比如，莫萨克·冯赛卡帮助习近平的姐夫邓家贵在英属维尔京群岛上设立了三家离岸公司。
> 
> 但是，莫萨克·冯赛卡在2004年和2009年帮助邓家贵购买公司的时候，并没有调查邓与中共高层的关联。
> 
> 尚不清楚这三家公司是被用来做什么的，尽管其中一家已解散，另两家在习近平2012年担任中共中央总书记后成为休眠公司。
> 
> 这其中的讽刺意味很明显：自从习近平上台后，他在党内展开了密集的反腐运动，仅2015年，就有超过30万官员因违反反腐条例被惩处。
> 
> 在莫萨克·冯赛卡发生的事情也在别的地方被复制。富有的中国人利用香港作为跳板，将资金挪到海外，以便保护他们的财产。
> 
> 在香港的独立中国分析员安德鲁·科利尔（Andrew Collier）说：“把钱放在中国通常有两点担心。第一，中国经济放缓；第二，中国领导层试图清理腐败，有些人担心钱放在中国不安全，因此要把资金挪到海外。”
> 
> 香港成为中国封堵资金外流的焦点。上月，中国反贪官员表示，外流的资金大多途经香港，并表示要阻止这一势头，尽管这可能很难做到。
> 
> “出现恐慌”
> 尽管中国的银行加强管控，去年大约有6.5亿美元的资金离开中国。中国公民每年只能五万美元的外汇额度，超过这个限额的资金转移就是违法。有些人利用复杂的转帐来将资金转移出境。
> 
> 一名非法外汇交易员告诉我们，他是如何通过在中国、香港、越南和菲律宾的大批“僵尸”账户将资金秘密转到海外。
> 
> 他利用那些已去世的人的名下账户，来确保无法追查到他自己。
> 
> 他笑着说：“我将客户的钱存到某个国家的某个账户，然后兑换后将钱存到另一个国家的另一个帐户。”
> 
> 但是，他不再接受那些试图把人民币从中国转移到海外的生意了。
> 
> 他皱着眉头说：“我已经有了太多的人民币。”
> 
> 如果中国对他这样的人采取打压，更严格地执法会怎么样呢？
> 
> 他说：“恐慌，那就会有恐慌。”
> 
> 图片版权AFP
> Image caption
> 北京国际机场。（资料图片）
> 钱骡
> 资本流动的背后是焦虑。
> 
> 林和立说：“人们对金融和经济决策团队的能力没有信心。如果他们有一、两百万美元，不在海外存放一半的资金那就是愚蠢的，因为他们对党的未来没有什么信心。”
> 
> 那些无法得到大牌外汇交易员服务的人，就依靠“钱骡”来帮助他们把钱弄到海外。我们见到了一名钱骡，他告诉我们他业务繁忙，帮助焦虑的客户把钱挪到海外。
> 
> “如果我的客户想移民，或者在境外投资，他们就需要我的帮助。”
> 
> “有时我把现金绑在身上，或者装进一个小袋子里。海关人员经常针对行李很多的人、或看上去紧张的人来检查，所以我就尽量保持镇静。”
> 
> 中国最富裕的人把钱转移到海外有何影响呢？
> 
> 钱一旦离开的中国，就必须有一个去向。
> 
> 大量资金外流推高了全球的房价。根据从事华人海外购房生意的居外海外房产网（juwai.com）介绍，中国买家去年花费520亿美元购买境外房产。
> 
> 在香港，来自内地的中国人挥重金购买高端房产。这在其它地方也是如此——中国最富裕的人在各地存放和消费他们资金，也许包括最高层的人。
> 
> 他们试图保护自己，但这让中国变得更脆弱。

我是韭菜, 啥也没看到

**Comment by ddzy** [comment]
我是韭菜, 啥也没看到😢

**Comment by houkanghong188** [comment]
韭菜路过

**Comment by forblanca** [comment]
> 郭文貴爆料視頻和文字:
> https://github.com/ourhimalayas/txt

兄弟，虽然国内主流喉舌都可信度极低，但是拿郭文贵这个可信度更低的爆料来佐证还是算了吧。
好比国际上谴责中国人权状况极差，国内人权确实差，但是如果拉达赖来站台，就会显得毫无底气。
我们要冲破枷锁，应当用对的去冲破错的，不应拿本身就不一定站得住的东西来打假呀。

**Comment by chenfancy** [comment]
> 在香港银行大楼的背景下，有一排排的兑换外币的店铺，进行着快速和匿名的一些交易。
> 
> 这个景象的背后，是数额更大的资金以史无前例的速度在转移。内地的财富经过香港或海外的外汇交易商外流。去年，有大约一万亿美元资金从中国外流，令外汇储备缩水。
> 
> 这一变化可能会动摇中国的整体经济。
> 
> 莫萨克·冯赛卡（Mossack Fonseca）泄露出来的文件，让我们了解到中国领导人的家人如何把钱转到海外。
> 
> 至少7名现任和前任领导人与这家巴拿马公司所设立的离岸公司有牵连，包括中国国家主席习近平和另两名领导人。
> 
> 这项丑闻涉及的中国现任及前任领导人家族成员： 现任领导人： 习近平（中国国家主席）——姐夫邓家贵是两家离岸公司的董事及股东。 刘云山（中共中央政治局常委）——儿媳妇贾丽青是一家离岸公司的董事和股东。 张高丽（中共中央政治局常委）——女婿李圣泼是3家离岸公司的股东。 前任领导人： 李鹏（国务院总理：1987年至1998年）——女儿李小琳是一家离岸公司的董事和股东。 贾庆林（中国政协主席：2002年至2012年）——外孙女李紫丹拥有一家离岸公司。 曾庆红（国家副主席：2002年至2007年）——胞弟曾庆淮是一家离岸公司的董事。 胡耀邦（党总书记：1982年至1987年）——三儿子胡德华是一家离岸公司的董事和股东。 这些名字此前在与离岸银行相关的报道中出现。但是，新文件泄露的时机对中国领导人来说比较棘手。
> 
> 中国领导人家族利用“避税天堂” 中国：“巴拿马文件”捕风捉影 不作评论
> 
> 拥有离岸公司在中国并不违法，但这些隐秘金融机构的存在给中国领导人的家庭提出了各种疑问。
> 
> 根据党章，中国共产党的官员应该“廉洁”，不能从以权谋私，他们的家属也不能从与高层的关系中获利。
> 
> 香港城市大学政治评论员林和立说，习近平把自己塑造成“一个在道德和廉洁上纯粹的人”。
> 
> 他说，在海外帐户上存放着大量的资金“明显与习近平的要求和共产党的传统相悖”。
> 
> “至于高官子女是否非法取得财富，这很难说，毕竟中国司法体系太隐晦。”
> 
> 图片版权AP Image caption 莫萨克·冯赛卡公司帮助习近平的姐夫邓家贵在英属维尔京群岛上设立了三家离岸公司。（资料图片） 资本逃逸 巴拿马文件透露了更多的关于中国权贵阶层海外资金状况。大批的电子邮件显示，莫萨克·冯赛卡（Mossack Fonseca）公司没有按照国际法的要求，在没有做背景调查的情况下，长期帮助一些有政治关系的客户成为离岸公司的股东。
> 
> 比如，莫萨克·冯赛卡帮助习近平的姐夫邓家贵在英属维尔京群岛上设立了三家离岸公司。
> 
> 但是，莫萨克·冯赛卡在2004年和2009年帮助邓家贵购买公司的时候，并没有调查邓与中共高层的关联。
> 
> 尚不清楚这三家公司是被用来做什么的，尽管其中一家已解散，另两家在习近平2012年担任中共中央总书记后成为休眠公司。
> 
> 这其中的讽刺意味很明显：自从习近平上台后，他在党内展开了密集的反腐运动，仅2015年，就有超过30万官员因违反反腐条例被惩处。
> 
> 在莫萨克·冯赛卡发生的事情也在别的地方被复制。富有的中国人利用香港作为跳板，将资金挪到海外，以便保护他们的财产。
> 
> 在香港的独立中国分析员安德鲁·科利尔（Andrew Collier）说：“把钱放在中国通常有两点担心。第一，中国经济放缓；第二，中国领导层试图清理腐败，有些人担心钱放在中国不安全，因此要把资金挪到海外。”
> 
> 香港成为中国封堵资金外流的焦点。上月，中国反贪官员表示，外流的资金大多途经香港，并表示要阻止这一势头，尽管这可能很难做到。
> 
> “出现恐慌” 尽管中国的银行加强管控，去年大约有6.5亿美元的资金离开中国。中国公民每年只能五万美元的外汇额度，超过这个限额的资金转移就是违法。有些人利用复杂的转帐来将资金转移出境。
> 
> 一名非法外汇交易员告诉我们，他是如何通过在中国、香港、越南和菲律宾的大批“僵尸”账户将资金秘密转到海外。
> 
> 他利用那些已去世的人的名下账户，来确保无法追查到他自己。
> 
> 他笑着说：“我将客户的钱存到某个国家的某个账户，然后兑换后将钱存到另一个国家的另一个帐户。”
> 
> 但是，他不再接受那些试图把人民币从中国转移到海外的生意了。
> 
> 他皱着眉头说：“我已经有了太多的人民币。”
> 
> 如果中国对他这样的人采取打压，更严格地执法会怎么样呢？
> 
> 他说：“恐慌，那就会有恐慌。”
> 
> 图片版权AFP Image caption 北京国际机场。（资料图片） 钱骡 资本流动的背后是焦虑。
> 
> 林和立说：“人们对金融和经济决策团队的能力没有信心。如果他们有一、两百万美元，不在海外存放一半的资金那就是愚蠢的，因为他们对党的未来没有什么信心。”
> 
> 那些无法得到大牌外汇交易员服务的人，就依靠“钱骡”来帮助他们把钱弄到海外。我们见到了一名钱骡，他告诉我们他业务繁忙，帮助焦虑的客户把钱挪到海外。
> 
> “如果我的客户想移民，或者在境外投资，他们就需要我的帮助。”
> 
> “有时我把现金绑在身上，或者装进一个小袋子里。海关人员经常针对行李很多的人、或看上去紧张的人来检查，所以我就尽量保持镇静。”
> 
> 中国最富裕的人把钱转移到海外有何影响呢？
> 
> 钱一旦离开的中国，就必须有一个去向。
> 
> 大量资金外流推高了全球的房价。根据从事华人海外购房生意的居外海外房产网（juwai.com）介绍，中国买家去年花费520亿美元购买境外房产。
> 
> 在香港，来自内地的中国人挥重金购买高端房产。这在其它地方也是如此——中国最富裕的人在各地存放和消费他们资金，也许包括最高层的人。
> 
> 他们试图保护自己，但这让中国变得更脆弱。
