### ISSUE TITLE
大神，怎么把争上游答题给写一下就好了，这个很有力量

### ISSUE THREAD

**Issue by WXHJYC** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#551]
大神，怎么把争上游答题给写一下就好了，这个很有力量，基层群众等待你的声音

**Comment by BBSMLtd** [comment]
同求哈哈

**Comment by BBSMLtd** [comment]
找到了
https://github.com/SpringCity-LaoYang/AutoXue-multiuser

**Comment by whhxmwhh** [comment]
这个环境要求有点高。要安装开发环境，有点麻烦。能做简单易用的就好了。暂时放弃

**Comment by studyhelperhelper** [comment]
https://github.com/studyhelperhelper/studyhelper.git

**Comment by Nevidebla** [comment]
> 找到了
> https://github.com/SpringCity-LaoYang/AutoXue-multiuser

这个被删了啊

**Comment by Fxxk-XueXiQiangGuo** [comment]
实在是不好意思，我已经决定停止更新了，见 #578 。  
（请原谅我有一些自私，因为我身边的人都已经不再强制要求使用学刁强国了。如果再次被强制使用，我可能才会改变主意。）
