### ISSUE TITLE
请问今天打开后被监控火绒安全监控到程序打开电脑摄像头!!!请帮忙解释下....

### ISSUE THREAD

**Issue by apple280** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#553]
如题...
1.我不明白为什么火绒安全提示要打开电脑摄像头.
2.麻烦作者出来解释下这个问题能否?

**Comment by Fxxk-XueXiQiangGuo** [comment]
明确告诉你，程序是不可能请求打开摄像头的，我可没有这种癖好。

至于为什么会被提示打开摄像头，毕竟中国产的“安全软件”也是需要有党性的。
