### ISSUE TITLE
ubuntu可以不用安装图形化界面来运行吗？

### ISSUE THREAD

**Issue by ljccccccccccc** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#555]
如题。

**Comment by Fxxk-XueXiQiangGuo** [comment]
看 README 中 [直接在命令行界面运行](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#%E7%9B%B4%E6%8E%A5%E5%9C%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E7%95%8C%E9%9D%A2%E8%BF%90%E8%A1%8C)。
