### ISSUE TITLE
软件更新建议，应该有用

### ISSUE THREAD

**Issue by EdwardXiaoran** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#559]
学刁墙国的视频是html5，我就想能不能加速html5视频的播放速度来节省时间，于是就去找了一些开源的hrml5外部控制的项目，大佬看看能不能整合进fuck-xuexiqiangguo里面？如果可以就好多了。
https://github.com/igrigorik/videospeed

**Comment by ubun222** [comment]
小心驶得万年船。。。

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 学刁墙国的视频是html5，我就想能不能加速html5视频的播放速度来节省时间，于是就去找了一些开源的hrml5外部控制的项目，大佬看看能不能整合进fuck-xuexiqiangguo里面？如果可以就好多了。
> https://github.com/igrigorik/videospeed

不需要啊，更改视频的 `playbackRate` 就可以了 <https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement>

**Comment by Fxxk-XueXiQiangGuo** [comment]
实在是不好意思，估计是不会实现了，我已经决定软件不再更新，见 #578 。
