### ISSUE TITLE
不知什么原因，现在积分增长非常慢？

### ISSUE THREAD

**Issue by swotom** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#568]
上周之前应该还是好的，登录之后半个小时差不多就刷到了24积分，现在登录之后挂一上午也只有3、4积分，再就不涨了，有人遇到同样的问题吗？只能等更新解决了吗？

**Comment by guhonghu11** [comment]
我今天出现跟你一样的情况，可能被检测出来了

**Comment by lisztomania-Zero** [comment]
https://github.com/lisztomania-Zero/learning-power
来试试我的，45分

**Comment by ananymous1982** [comment]
需要保持软件没有最小化。在前台运行。

**Comment by ananymous1982** [comment]
> 
> 
> https://github.com/lisztomania-Zero/learning-power
> 来试试我的，45分

我倒还是觉得这个脚本策略最简单，最保险。

**Comment by Fxxk-XueXiQiangGuo** [comment]
实在是不好意思，我已经决定停止更新了，见 #578 。  
（请原谅我有一些自私，因为我身边的人都已经不再强制要求使用学刁强国了。如果再次被强制使用，我可能才会改变主意。）
