### ISSUE TITLE
为什么浏览的资讯是老的, 不是最新的?

### ISSUE THREAD

**Issue by laobei** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#569]
![image](https://user-images.githubusercontent.com/5109298/101712477-94439e00-3ad0-11eb-98fe-df0fa4c06484.png)

**Comment by ananymous1982** [comment]
不清楚原因。但因为xxqg在刷的时候，我也不会去看，只要涨分就行了。也不用追求自动刷的资讯是最新的吧？

**Comment by sukabulie887** [comment]
作者都被抓了，还用这个？

**Comment by Xmader** [comment]
不要瞎说，我还活着好好的On Feb. 26, 2021 07:34, sukabulie887 <notifications@github.com> wrote:

作者都被抓了，还用这个？
