### ISSUE TITLE
windows端能不能直接登录账户，不使用二维码

### ISSUE THREAD

**Issue by ziven123** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#576]
我有一台windows小主机，24小时不关机。所以想一直挂着，每天移动刷分。但是我发现打开软件后只能刷一次，第二天需要重新打开，重新扫描二维码登录，很蛋痛。
大佬有什么方法直接登录账号，不需要扫描二维码。
我可以在windows上设置任务计划程序，每天准点打开程序。现在问题是每天准点打开的程序需要扫描二维码。求作者抽空解决一下。

**Comment by low-bee** [comment]
要是能账号密码登录就好了, 这样直接放在服务器上运行多爽

**Comment by Fxxk-XueXiQiangGuo** [comment]
实在是不好意思，我已经决定停止更新了，见 #578 。  
（请原谅我有一些自私，因为我身边的人都已经不再强制要求使用学刁强国了。如果再次被强制使用，我可能才会改变主意。）

**Comment by ziven123** [comment]
好吧 那就这样吧 祝你好运
