### ISSUE TITLE
我去，这里是技术社区，能远离政治吗？

### ISSUE THREAD

**Issue by SerBad** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#58]
我去，这里是技术社区，能远离政治吗？

**Comment by mxvlgrz** [comment]
替代性攻击思维不可取

**Comment by minororange** [comment]
先是娱乐圈、后有游戏圈、现在已经波及到github了，这群人真的够了

**Comment by Fxxk-XueXiQiangGuo** [comment]
我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。

**Comment by dexterque** [comment]
怎么就没点娱乐精神呢？

**Comment by sizukari** [comment]
https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/issues/62

**Comment by wuyucun** [comment]
您不认同的行为，请您远离！谁也没有逼着您用。
既然我们不想学习强国，我们自愿使用。

井水不犯河水，你有你不用的权利，我有我用的权利。谢谢

**Comment by terminus1984** [comment]
**只要CCP还在利用技术/艺术/新闻来打压人民，我们就不应该也不会停止使用技术/艺术/新闻来反抗！**

**Comment by CeresCa** [comment]
关你屁事

**Comment by darkstar321** [comment]
你翻墙出来说远离政治？

**Comment by tabris17** [comment]
你脑子进屎了吧

**Comment by cz1980** [comment]
> 我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。

这是一个讨论技术的社区，不是讨论政治的地方。况且，政治观点不论，这里很多人发的帖子，不谈论事实、理由和依据，“出口成脏”的人，这样的谈的也算政治吗。你说的言论自由我想应该指的是自由的观点，而不是攻击他人的，粗话、脏话。

**Comment by dexterque** [comment]
> > 我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。
> 
> 这是一个讨论技术的社区，不是讨论政治的地方。况且，政治观点不论，这里很多人发的帖子，不谈论事实、理由和依据，“出口成脏”的人，这样的谈的也算政治吗。你说的言论自由我想应该指的是自由的观点，而不是攻击他人的，粗话、脏话。

你可以不看这个项目，离开这个留言板就行了

**Comment by k53247l2** [comment]
> > > 我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。
> > 
> > 
> > 这是一个讨论技术的社区，不是讨论政治的地方。况且，政治观点不论，这里很多人发的帖子，不谈论事实、理由和依据，“出口成脏”的人，这样的谈的也算政治吗。你说的言论自由我想应该指的是自由的观点，而不是攻击他人的，粗话、脏话。
> 
> 你可以不看这个项目，离开这个留言板就行了

这是问题交流板块，不是你在这里灌水的论坛版块，该是请你离开才对！

**Comment by dexterque** [comment]
> > > > 我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。
> > > 
> > > 
> > > 这是一个讨论技术的社区，不是讨论政治的地方。况且，政治观点不论，这里很多人发的帖子，不谈论事实、理由和依据，“出口成脏”的人，这样的谈的也算政治吗。你说的言论自由我想应该指的是自由的观点，而不是攻击他人的，粗话、脏话。
> > 
> > 
> > 你可以不看这个项目，离开这个留言板就行了
> 
> 这是问题交流板块，不是你在这里灌水的论坛版块，该是请你离开才对！

你可以提bug啊 楼主提的是啥？好了 我走了你们玩

**Comment by cz1980** [comment]
> 
> 
> > > > 我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。
> > > 
> > > 
> > > 这是一个讨论技术的社区，不是讨论政治的地方。况且，政治观点不论，这里很多人发的帖子，不谈论事实、理由和依据，“出口成脏”的人，这样的谈的也算政治吗。你说的言论自由我想应该指的是自由的观点，而不是攻击他人的，粗话、脏话。
> > 
> > 
> > 你可以不看这个项目，离开这个留言板就行了
> 
> 这是问题交流板块，不是你在这里灌水的论坛版块，该是请你离开才对！

你说的有道理，原本我是好奇代码是怎么实现的，学习学习。没想到一进来，这么多骂人的，这么多负面情绪，不知道这些骂人的，自己有没有兴趣研究和讨论技术，还是只是跑过来做伸手党来了。没几个在真正讨论技术的，真是瞎耽误功夫。

**Comment by gnaggnoyil** [comment]
> 
> 
> > 我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。
> 
> 这是一个讨论技术的社区，不是讨论政治的地方。况且，政治观点不论，这里很多人发的帖子，不谈论事实、理由和依据，“出口成脏”的人，这样的谈的也算政治吗。你说的言论自由我想应该指的是自由的观点，而不是攻击他人的，粗话、脏话。

纯粹的技术不可能远离纯粹的价值体系而存在——首先你得有一个"什么是好的"的定义或者判断.而政治显然是价值体系的一种表现形式.

此外政治最强有力的在场形式就是让场上所有人都不敢谈论它从而达成其自己在形式上的不在场.所以所有要求要政治远离技术的无一例外都会促成"谈政治色变"的高压政治气氛,可谓是高压政治的忠实打手,简直自嘲完美.

**Comment by cz1980** [comment]
> > > 我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。
> > 
> > 
> > 这是一个讨论技术的社区，不是讨论政治的地方。况且，政治观点不论，这里很多人发的帖子，不谈论事实、理由和依据，“出口成脏”的人，这样的谈的也算政治吗。你说的言论自由我想应该指的是自由的观点，而不是攻击他人的，粗话、脏话。
> 
> 纯粹的技术不可能远离纯粹的价值体系而存在——首先你得有一个"什么是好的"的定义或者判断.而政治显然是价值体系的一种表现形式.
> 
> 此外政治最强有力的在场形式就是让场上所有人都不敢谈论它从而达成其自己在形式上的不在场.所以所有要求要政治远离技术的无一例外都会促成"谈政治色变"的高压政治气氛,可谓是高压政治的忠实打手,简直自嘲完美.
> 
> 以及"礼节"甚至从来不是撕逼所看重的要素之一.撕逼的首要目的是达成对观点的共识.温文尔雅地进行争辩固然很好,但是如果有人想以"温文尔雅"为幌子打压人们撕逼达成共识的进程,那首先遭到抛弃的必然是这个幌子.这个幌子被抛弃固然可惜,但是造成这种局面的罪魁祸首毫无疑问是那些举着幌子打压人们撕逼的人.

不知道是我水平差，还是你说的太绕，总是我不是太明白你说的是什么意思。你说的撕逼，是不是双方言语之间的相互攻击，诸如侮辱别人的父母，诋毁别人的尊严之类的。这样的撕逼的首要目的是达成对观点的共识？在我看来这纯粹是情绪的宣泄，没有什么建设性。就像那些骂人的自己不会去想这个软件的原理是什么，怎么做出来。骂人容易，真正能做成事情很难。

**Comment by yiding-he** [comment]
我也想远离政治，但政治一直追着我跑。楼主能不能呼吁学习强国的开发人员远离政治，不要开发这个 App？

**Comment by OCer** [comment]
APP没错 错在在issue带节奏的人  用心险恶

**Comment by gnaggnoyil** [comment]
> 
> 
> > > > 我是觉得一些 issue 发在这里不太合适，例如 #52 、#54 和 #55 ，它们应该被发在更合适的地方。但我尊重言论自由，不会去干预的。
> > > 
> > > 
> > > 这是一个讨论技术的社区，不是讨论政治的地方。况且，政治观点不论，这里很多人发的帖子，不谈论事实、理由和依据，“出口成脏”的人，这样的谈的也算政治吗。你说的言论自由我想应该指的是自由的观点，而不是攻击他人的，粗话、脏话。
> > 
> > 
> > 纯粹的技术不可能远离纯粹的价值体系而存在——首先你得有一个"什么是好的"的定义或者判断.而政治显然是价值体系的一种表现形式.
> > 此外政治最强有力的在场形式就是让场上所有人都不敢谈论它从而达成其自己在形式上的不在场.所以所有要求要政治远离技术的无一例外都会促成"谈政治色变"的高压政治气氛,可谓是高压政治的忠实打手,简直自嘲完美.
> > 以及"礼节"甚至从来不是撕逼所看重的要素之一.撕逼的首要目的是达成对观点的共识.温文尔雅地进行争辩固然很好,但是如果有人想以"温文尔雅"为幌子打压人们撕逼达成共识的进程,那首先遭到抛弃的必然是这个幌子.这个幌子被抛弃固然可惜,但是造成这种局面的罪魁祸首毫无疑问是那些举着幌子打压人们撕逼的人.
> 
> 不知道是我水平差，还是你说的太绕，总是我不是太明白你说的是什么意思。你说的撕逼，是不是双方言语之间的相互攻击，诸如侮辱别人的父母，诋毁别人的尊严之类的。这样的撕逼的首要目的是达成对观点的共识？在我看来这纯粹是情绪的宣泄，没有什么建设性。就像那些骂人的自己不会去想这个软件的原理是什么，怎么做出来。骂人容易，真正能做成事情很难。

虽然我所说的"撕逼"其实指的是一切因利益或立场的冲突而产生的对立过程,不过您还别说,言语乃至现实上的相互攻击本来也算是实现共识的一种方式——把无论如何都无法达成共识的相关方踢出共识圈子,剩下的多数相关方不就能达成共识了么:) 至于为啥这些相关方在明明作为相关方的情况下还死活达不成共识乃至最后不得不使用言语乃至现实上的相互攻击而被踢出共识圈子,至少对于达成共识的人们来说这纯粹是少数相关方的问题.

至于想跳过共识的达成就想直接做事情的,请看我一开始发的回复中的第一段话:)

**Comment by mxvlgrz** [comment]
> APP没错 错在在issue带节奏的人 用心险恶

又来了！”一小撮别有用心的人“！
