### ISSUE TITLE
如何每天自动登陆一下？

### ISSUE THREAD

**Issue by trunksjiang78** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#584]
单位只要求每天登陆一下拿1分就可以了，通过钉钉账户密码的方式不行
家里有群晖nas，有梅林路由器，有啥好办法每天自动登陆一下？
现在都要扫码登陆才行

**Comment by Oopas** [comment]
> 单位只要求每天登陆一下拿1分就可以了，通过钉钉账户密码的方式不行
> 家里有群晖nas，有梅林路由器，有啥好办法每天自动登陆一下？
> 现在都要扫码登陆才行

请问是怎么解决的呢
