### ISSUE TITLE
> > 女拳能不能死啊

### ISSUE THREAD

**Issue by tracygoo** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#585]
> > 女拳能不能死啊
> 
> 猥琐恶臭中国男先去死。
> 中国女性都应该找尊重女性的白人。

你拜登爹给你发了多少狗粮，让你这么拼，装女的带节奏？你这么做真不怕你🐎暴毙哦

_Originally posted by @seancheer in https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/issues/581#issuecomment-828221775_

**Comment by ZhanLongqi** [comment]
欸,好好的技术社区(sad)
