### ISSUE TITLE
本人不是党员，但是使用这个的党员，就像考试作弊一样，让人反感。

### ISSUE THREAD

**Issue by koudle** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#60]

**Comment by Fxxk-XueXiQiangGuo** [comment]
大家是被强迫去使用的

**Comment by G159Z** [comment]
虽然不需要学习，但是顶答主。

**Comment by lynnhuel** [comment]
支持楼主。

**Comment by rocky-191** [comment]
反感的项目

**Comment by dexterque** [comment]
因为考试本身就让人反感啊

**Comment by noway2014** [comment]
很多地方非党员也要学，而且还要强迫排名，排名后的，各种理由等着被整。不考虑身体，眼睛，年纪，个人实际情况等，都统一要求。难道这是合理的？

**Comment by jianxuanbing** [comment]
每天30分

**Comment by kehao95** [comment]
就是，明明主子要求大家一起要吃屎的，居然有些人不好好当狗选择不吃，这让我心里很不平衡。

**Comment by jasonyangmx** [comment]
首先利益相关我是党员
我想和大家分享一下我在使用时的感受。不知道各位是否详细考察过这款应用，里面的答题基本上只要是识字就不会出错，因为在答题的时候，每道题的下面就有答案，只不过通常是一段文字，需要初中以上的阅读理解能力。有的甚至用颜色高亮了答案。说起来我更觉得这像是一种强化记忆的复习资料。
另外，积分的情况，我感觉积分不是很难拿到。如果你去看积分说明的话，就知道里面提到了双倍积分的时间段，早中晚都有，基本是在非工作时间。
另外，程序里除了党政相关视频，还有其他内容，比如慕课，诗词大会等等
最后我有一点比较奇怪，这个程序至少在我这里只是对党员有要求。既然如此，作为一个团体成员，了解团体最新动态至少也是应该的吧。如果不喜欢这个团体，那又为何非要加入？
无意和大家争论，只是我自己的想法。有不同观点欢迎理性回复。我也不常上git，是从群里同学发来的信息打开看的。
谢谢大家。

**Comment by CeresCa** [comment]
滚回墙内

**Comment by Neo-Zhixing** [comment]
真是什么人都来了

**Comment by wenfeng0218** [comment]
求你反感我

**Comment by Puppey** [comment]
我推荐你入党
