### ISSUE TITLE
支持技术不应该夹杂政治！请学习强国停止使用 TCP/IP ，编程等技术。

### ISSUE THREAD

**Issue by sizukari** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#62]
众所周知，技术是纯洁的，艺术是纯洁的，新闻是纯洁的，技术社区是纯洁的，编程语言是纯洁的，TCP/IP 是纯洁的。这些纯洁的事物是不应该夹杂政治的，政治是邪恶的，政治是和普通人无关的。

在此，我强烈呼吁，倡议，抗议，要求学习强国APP停止使用纯洁的TCP/IP 技术，停止使用 M3U8, H264 等纯洁的视频编码/索引技术，停止使用纯洁的 TLS 技术，停止使用 Unix 和 其他开源程序。开源是自由的，而自由是邪恶的。

另外，强烈抗议新疆当局使用纯洁的视频监控技术监控民众。强烈抗议使用纯洁的DNA技术对民众进行生物识别。

技术是纯洁的，是不应该夹杂政治的！

**Comment by ddzy** [comment]
> 众所周知，技术是纯洁的，艺术是纯洁的，新闻是纯洁的，技术社区是纯洁的，编程语言是纯洁的，TCP/IP 是纯洁的。这些纯洁的事物是不应该夹杂政治的，政治是邪恶的，政治是和普通人无关的。
> 
> 在此，我强烈呼吁，倡议，抗议，要求学习强国APP停止使用纯洁的TCP/IP 技术，停止使用 M3U8, H264 等纯洁的视频编码/索引技术，停止使用纯洁的 TLS 技术，停止使用 Unix 和 其他开源程序。开源是自由的，而自由是邪恶的。
> 
> 另外，强烈抗议新疆当局使用纯洁的视频监控技术监控民众。强烈抗议使用纯洁的DNA技术对民众进行生物识别。
> 
> 技术是纯洁的，是不应该夹杂政治的！

hhhhh

**Comment by wuyucun** [comment]
您不认同的行为，请您远离！谁也没有逼着您用。
既然我们不想学习强国，我们自愿使用。

井水不犯河水，你有你不用的权利，我有我用的权利。谢谢

**Comment by sizukari** [comment]
> 您不认同的行为，请您远离！谁也没有逼着您用。
> 既然我们不想学习强国，我们自愿使用。
> 
> 井水不犯河水，你有你不用的权利，我有我用的权利。谢谢

您没有读明白我的意思，对于 “Fuck-XueXiQiangGuo” 这种用技术让生活更美好的APP我为什么要反对呢？ 我反对的是学习强国APP的开发者中共宣传部使用纯洁的编程技术开发政治APP。

**Comment by wuyucun** [comment]
> 您没有读明白我的意思，对于 “Fuck-XueXiQiangGuo” 这种用技术让生活更美好的APP我为什么要反对呢？ 我反对的是学习强国APP的开发者中共宣传部使用纯洁的编程技术开发政治APP。

抱歉，我这段话是想回复在另一个帖子《请各党员理智学习，不要支持此类项目》，十分抱歉！
最后，我很认同您的观点！！👍

**Comment by terminus1984** [comment]
**我来逐条反驳！**

> 众所周知，技术是纯洁的，艺术是纯洁的，新闻是纯洁的，技术社区是纯洁的，编程语言是纯洁的，TCP/IP 是纯洁的。这些纯洁的事物是不应该夹杂政治的

**反驳：**[GFW](https://zh.wikipedia.org/zh-hans/%E9%98%B2%E7%81%AB%E9%95%BF%E5%9F%8E)怎么说？[大规模监控](https://cn.nytimes.com/china/20180710/china-surveillance-technology/)怎么说？**只要CCP还在利用技术/艺术/新闻来打压人民，我们就不应该也不会停止使用技术/艺术/新闻来反抗！**

> 政治是邪恶的

**反驳：** 政治是邪恶的？你是说CCP的领导层都是恶魔咯？笑

> 政治是和普通人无关的

**反驳：** 政治和我们每个人都[息息相关](https://www.zhihu.com/question/30660963)

> 开源是自由的，而自由是邪恶的

**反驳：** 自由邪恶？呵呵。自由是[基本人权](https://zh.wikipedia.org/wiki/%E4%BA%BA%E6%9D%83)了解一下

> 另外，强烈抗议新疆当局使用纯洁的视频监控技术监控民众。强烈抗议使用纯洁的DNA技术对民众进行生物识别。

**注意：** 这句倒没什么可反驳的。不过看了你其他的言论，我不敢轻易相信你是真心而不是故意混淆视听的。你的小册子里或许是这么写的？：混淆视听时不能全说一种言论，相对的言论也掺合一句？（笑

> 技术是纯洁的，是不应该夹杂政治的！

**反驳：** 上面说过了，**只要CCP还在利用技术/艺术/新闻来打压人民，我们就不应该也不会停止使用技术/艺术/新闻来反抗！**

**Comment by sizukari** [comment]
> **我来逐条反驳！**
> 
> > 众所周知，技术是纯洁的，艺术是纯洁的，新闻是纯洁的，技术社区是纯洁的，编程语言是纯洁的，TCP/IP 是纯洁的。这些纯洁的事物是不应该夹杂政治的
> 
> **反驳：**[GFW](https://zh.wikipedia.org/zh-hans/%E9%98%B2%E7%81%AB%E9%95%BF%E5%9F%8E)怎么说？[大规模监控](https://cn.nytimes.com/china/20180710/china-surveillance-technology/)怎么说？**只要CCP还在利用技术/艺术/新闻来打压人民，我们就不应该也不会停止使用技术/艺术/新闻来反抗！**
> 
> > 政治是邪恶的
> 
> **反驳：** 政治是邪恶的？你是说CCP的领导层都是恶魔咯？笑
> 
> > 政治是和普通人无关的
> 
> **反驳：** 政治和我们每个人都[息息相关](https://www.zhihu.com/question/30660963)
> 
> > 开源是自由的，而自由是邪恶的
> 
> **反驳：** 自由邪恶？呵呵。自由是[基本人权](https://zh.wikipedia.org/wiki/%E4%BA%BA%E6%9D%83)了解一下
> 
> > 另外，强烈抗议新疆当局使用纯洁的视频监控技术监控民众。强烈抗议使用纯洁的DNA技术对民众进行生物识别。
> 
> **注意：** 这句倒没什么可反驳的。不过看了你其他的言论，我不敢轻易相信你是真心而不是故意混淆视听的。你的小册子里或许是这么写的？：混淆视听时不能全说一种言论，相对的言论也掺合一句？（笑
> 
> > 技术是纯洁的，是不应该夹杂政治的！
> 
> **反驳：** 上面说过了，**只要CCP还在利用技术/艺术/新闻来打压人民，我们就不应该也不会停止使用技术/艺术/新闻来反抗！**

反驳的不错！我讽刺的是一些程序员挂在嘴边的纯洁论，政治与屁民无关论，受害者有错轮。

**Comment by dexterque** [comment]
这个题目容易被误伤哈哈哈

**Comment by dexterque** [comment]
不过 项目的名字太惹人耳目 建议改成 love-xuexiqiangguo

**Comment by AngelFalse** [comment]
太高级黑容易让人认不出来哈哈哈哈

**Comment by keys961** [comment]
你把大🔥逗乐了

**Comment by AntiMoron** [comment]
你把大🔥逗乐了

**Comment by bingoku** [comment]
这位大神，你的诉求是什么？

**Comment by excitingduckduckgo** [comment]
强烈同意技术不应该参杂政治！
请学习全国停止使用这些技术开发软件！

**Comment by terminus1984** [comment]
> 太高级黑容易让人认不出来哈哈哈哈

好吧，还真没看出来，下次开头先说明是友军😄
