### ISSUE TITLE
感谢作者，为了中国人的未来，大家关注郭文贵

### ISSUE THREAD

**Issue by UnicornQ** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#66]
为了中国人而不是共匪的未来，关注郭文贵
https://www.youtube.com/channel/UCO3pO3ykAUybrjv3RBbXEHw

**Comment by UnicornQ** [comment]
大家注意看，越多攻击文贵的五毛，就越证明他是中共的最大威胁

**Comment by gustav183** [comment]
一切都是刚刚开始

**Comment by Lz1y** [comment]
真是什么人都来了

**Comment by Pzhao199007** [comment]
政治上的东西，请不要咋在技术论坛里讨论!

**Comment by lynnhuel** [comment]
怕是没有判断是非的能力吧？别人说啥都是对的。文贵漏洞百出的言论，还是有人会相信。

**Comment by dxl1236** [comment]
文贵就是借剿匪之名敛财而已

**Comment by Fyred** [comment]
国内捞了不法之财，跑到国外怕被追逃，然后把自己伪装成政治迫害者，对了，政治避难签证办下来了吗？
