### ISSUE TITLE
建议增加个多开功能

### ISSUE THREAD

**Issue by fyu0h** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#7]
建议增加个多开功能，想帮朋友一起刷了

**Comment by zhangziran** [comment]
我个人感觉这样操作风险比较大，除非作者使用沙箱方式解决。不然鬼知道阿里做这玩意是否会通过其他未知的方式获取系统信息。

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 我个人感觉这样操作风险比较大，除非作者使用沙箱方式解决。不然鬼知道阿里做这玩意是否会通过其他未知的方式获取系统信息。

浏览器本身就相当于一个沙箱，以沙箱的方式运行js代码

**Comment by yimouleng** [comment]
linux 使用screen ，虽然没试过，但觉得可行

**Comment by sonicning** [comment]
请问一下，配置相关的内容是存在当前文件夹下，还是存在用户文件夹下啊？这个放不同的文件夹下运行，能够提供多开功能么？

**Comment by Fxxk-XueXiQiangGuo** [comment]
现在程序已经提供了[多开功能（多用户模式）](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#040---2019-03-13)，可以使用 `--multi-user` 命令行选项启用。

```
./Fuck学习强国 --multi-user
```

或者使用[指定用户ID的多用户模式](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#041---2019-03-13)（用户ID作用是区分用户，保存cookies，可随便填写），使用 `--user=<user_name>` 命令行选项启用。

```
./Fuck学习强国 --user=abc

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 请问一下，配置相关的内容是存在当前文件夹下，还是存在用户文件夹下啊？这个放不同的文件夹下运行，能够提供多开功能么？

Windows下在 `%APPDATA%/fuck-xuexiqiangguo/`
Linux下在 `~/.config/fuck-xuexiqiangguo/`
Mac下在 `~/Library/Application Support/fuck-xuexiqiangguo/`

**Comment by whhxmwhh** [comment]
这个能详细介绍一下吗？

**Comment by whhxmwhh** [comment]
![多开捕获](https://user-images.githubusercontent.com/7959854/54250582-65a53600-457f-11e9-9255-d8aaddf3cfb3.JPG)
是这个意识吗？

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 是这个意识吗？

不是这个意思，是打开powershell，进入程序所在目录，运行

```
.\Fuck学习强国.exe --multi-user
```

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#042---2019-03-13)可以直接多开程序（正常打开），自动使用多用户模式。

**Comment by whhxmwhh** [comment]
![多开问题捕获](https://user-images.githubusercontent.com/7959854/54253787-caff2400-458b-11e9-910f-1634e19df57f.JPG)
shi'f是否还要定位到学习的目录？

**Comment by whhxmwhh** [comment]
午休一下了。楼主辛苦了！感谢

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 是否还要定位到学习的目录？

是的（顺手去掉了多输入的 `shi'f` ）

**Comment by whhxmwhh** [comment]
谢谢！辛苦了！
可以使用了。登陆界面出现了。明天再测试。今天剩下手动刷分的了。



![多开1捕获](https://user-images.githubusercontent.com/7959854/54254075-54fbbc80-458d-11e9-9e34-5626a437678e.JPG)
![多开2捕获](https://user-images.githubusercontent.com/7959854/54254086-5b8a3400-458d-11e9-9de1-408133d82fba.JPG)

**Comment by whhxmwhh** [comment]
是的（顺手去掉了多输入的 shi'f ）这个什么意识？

**Comment by Fxxk-XueXiQiangGuo** [comment]
你多输入了 `shi'f` ，发表时是这样的：

> ![多开问题捕获](https://user-images.githubusercontent.com/7959854/54253787-caff2400-458b-11e9-910f-1634e19df57f.JPG)
> shi'f是否还要定位到学习的目录？

**Comment by whhxmwhh** [comment]
谢谢

**Comment by whhxmwhh** [comment]
这个还是要再研究一下。
1.能否直接手机号码已经密码登陆不要注册丁丁
2.退出还是退出不了。

**Comment by whhxmwhh** [comment]
![维护捕获](https://user-images.githubusercontent.com/7959854/54413082-9deb7680-472f-11e9-96d4-96c876a2639b.JPG)
视频维护

**Comment by Fxxk-XueXiQiangGuo** [comment]
实在是不好意思，我已经决定停止更新本项目了，见 #578 。  
多谢大家支持。
