### ISSUE TITLE
你翻墙出来说远离政治？

### ISSUE THREAD

**Issue by cz1980** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#70]
你翻墙出来说远离政治？

_Originally posted by @darkstar321 in https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/issues/58#issuecomment-470327719_

翻墙出来是为了学习技术

**Comment by zuozishi** [comment]
诶，Github不用翻墙啊

**Comment by dexterque** [comment]
有点证件不充分 :)

**Comment by OCer** [comment]
把GitHub弄封了就要翻墙了 @zuozishi

**Comment by Fyred** [comment]
github需要翻墙？你个臭傻逼轮子，哪来的滚回哪去，滚回你李洪志祖宗的逼里去
