### ISSUE TITLE
感觉这个库迟早会被这些讨论政治的人耗死

### ISSUE THREAD

**Issue by AngelFalse** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#71]
过不了多久就会有“KGB”来了，作者也赶紧收拾点东西准备跑路吧。

另外，讲真，虽然不是不允许，也没有违反啥takedown policy(毕竟女装照啥的也已经有了)，但在github上讨论政治(issue里的那些人)，这不是希望github赶快被土啬吗？到时候国内的开发者怎么办？

还有，实际上这里应该发的是源代码，各个build应该放在release里发出来。（GitHub的基本使用方法）

**Comment by Neo-Zhixing** [comment]
首先国外的开发者没必要为国内的开发者考虑。如果GitHub真封了，谁封的找谁去，责怪网站的用户干什么。

其次一个开发者连基本翻墙 google 上stackoverflow的能力都没有，真不知道怎么成为开发者的。

最后，同意作者应该在这里发源代码。

**Comment by AngelFalse** [comment]
> 首先国外的开发者没必要为国内的开发者考虑。如果GitHub真封了，谁封的找谁去，责怪网站的用户干什么。

讲真，有本事我也想去找封的人（笑死）。可是我没那本事（悲）。

> 其次一个开发者连基本翻墙 google 上stackoverflow的能力都没有，真不知道怎么成为开发者的。

据我所知，有很多开发者**的确是**不上g上stackOverflow的。
虽然，是有那个能力，总归还是变麻烦了。而且谁能说我的梯子不会被**随着github一起被封掉**呢www

**Comment by OCer** [comment]
唉 总有人不把GitHub闹死就不开心  ㄟ( ▔, ▔ )ㄏ
还总喊着“谁封的找谁去”  怎么被封的没点B数  事情的发生总有原因的 而作为原因的一方还觉得自己无罪 ㄟ( ▔, ▔ )ㄏ

**Comment by szl0834** [comment]
你们什么时候有了不闹腾就不会被封锁的错觉？

**Comment by wsmrxc** [comment]
> 
> 
> 唉 总有人不把GitHub闹死就不开心 ㄟ( ▔, ▔ )ㄏ
> 还总喊着“谁封的找谁去” 怎么被封的没点B数 事情的发生总有原因的 而作为原因的一方还觉得自己无罪 ㄟ( ▔, ▔ )ㄏ

所以你认为错的是这群人？而不是gfw？

**Comment by OCer** [comment]
> 所以你认为错的是这群人？而不是gfw？

是是是 你们都是对啊  https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/issues/63
赶紧去拥护吧  一起去起义啊  事成了你们就是开国大臣了  @wsmrxc
