### ISSUE TITLE
请不要把政治问题带到技术社区，谢谢

### ISSUE THREAD

**Issue by wyhhxxttxs** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#75]
作为一个人，我可以理解此类项目出现在Github，也能理解作者发布此项目的初衷。

如果你要展示自己的才能请你换一个项目或者换一种方式去实现；如果你是其他企图亡我中华反华反党分子之流，我们一定会与你斗争到底。你可以继续更新甚至关闭此帖。

如果你执意要这么做，我一定会积极的向Github、学习强国、中宣部举报此类行径。

最后，希望其他中共党员以及Github用户理智地、科学地、有效地学习，切勿盲目追随支持此类项目。

**Comment by Neo-Zhixing** [comment]
> 如果你是其他企图亡我中华反华反党分子之流，我们一定会与你斗争到底。

扣帽子，稻草人。作者只是写了几句代码，可曾说过一句有关“中国应该被殖民一百年，中国人都该死”这样的话。


然后，混淆概念。反党不等同于“企图亡我中华”，更不同于“反华”。现在看来没有某党反而是件好事。
