### ISSUE TITLE
封所有人GitHub的，不是我们这些人，而是你们这些人。

### ISSUE THREAD

**Issue by Neo-Zhixing** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#76]
并没有人规定GitHub只是一个技术社区。用GitHub干其他事情的人多了去了，GitHub官方和微软并不反对，我不知道一些人又有什么意见。

而正是你们的自我审查，对强权的纵容，才会造成现在的局面，他们想封杀谁封杀谁。

这就好比，有人把100只待宰杀的羊关在一间黑屋子里，后来有一只羊掀开一块砖头准备逃脱死于屠刀的命运，结果一半的羊嫌阳光太亮刺眼，一半的羊说“草别跑啊，跑了我们明天食物就要减半”

**如果GitHub被封了，谁封的找谁去。**

**Comment by MagShadow** [comment]
自我审查者已经觉得我党想封禁谁就封禁谁是一件天经地义的事情了。
因为还愿辱包而骂他们可能导致steam被封掉——请问辱特朗普的游戏被美国封禁了吗？？？是共产党做的封禁还是开发者做的封禁？？？

**Comment by AntiMoron** [comment]
您好，亲。 我国政治主要是治理人云亦云的傻逼用的。结果非傻逼被一刀切导致闹心了。如果能从加强孩子教育上开始加大力度，那么我们的政治立场将空前宽松。

**Comment by TigerHix** [comment]
大佬牛逼！
