### ISSUE TITLE
英国政府项目都托管在GitHub,凭什么说技术社区与政治无关!!!

### ISSUE THREAD

**Issue by ghost** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#77]
一群自我阉割,自我审查的奴隶.政府无限的权力都是你们自我阉割自我审查放弃造成的!!
正是因为你们自我阉割自我审查,才造就了如今的GFW.
审查制度的最高境界就是自我审查的同时逼迫他人自我审查!!

**Comment by Fyred** [comment]
傻逼轮子的智商就是突破天际，人家不爱搭理你你还舔着碧莲往上贴吗，你怎么不跟你李洪志爷爷一起升仙？

**Comment by yiding-he** [comment]
@Fyred 楼主的账号是一个小时前注册的，没有其他信息。我很好奇你怎么知道 TA 的身份。

**Comment by mxvlgrz** [comment]
> @Fyred 楼主的账号是一个小时前注册的，没有其他信息。我很好奇你怎么知道 TA 的身份。

竖个假想敌就完事了，除了"你们轮子"，还有"你们台湾人"。
YouTube上有人和粉红互动，粉红从第一句开始，每句开头都是”你们台湾人“，那个人每句都回一句”我是大陆的“，233333

**Comment by Fyred** [comment]
> @Fyred 楼主的账号是一个小时前注册的，没有其他信息。我很好奇你怎么知道 TA 的身份。

对面以“奴隶”“阉割”这种词汇称呼你了，骂到你脸上来了，你还要去探究他什么身份，是不是迂腐过头了？我承认我没气度，回怼我之常情。

**Comment by Fyred** [comment]
> > @Fyred 楼主的账号是一个小时前注册的，没有其他信息。我很好奇你怎么知道 TA 的身份。
> 
> 竖个假想敌就完事了，除了"你们轮子"，还有"你们台湾人"。
> YouTube上有人和粉红互动，粉红从第一句开始，每句开头都是”你们台湾人“，那个人每句都回一句”我是大陆的“，233333

同上

**Comment by yiding-he** [comment]
@Fyred 你觉得骂了你，那就是承认了自己在github上自我审查。github 上理性表态并无不可，牵涉到政治的开源项目数不胜数，你没有必要在这里自我审查。
