### ISSUE TITLE
win ser 2003用户表示很伤心，打不开。

### ISSUE THREAD

**Issue by zhangziran** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#8]
提示bcrypt.dll丢失

**Comment by tangbao** [comment]
去网上下一个然后丢到system32之类的文件夹里呢

**Comment by PussAzuki** [comment]
根据谷歌结果表示是您的系统缺少该文件，我作为一个闲人在此推荐您重装完整版的系统并打上所有补丁。
如果重装完整版系统并打好所有补丁也还有这个问题的话，推荐您升级系统。
什么？不能升级系统？那没救了，还请另请高明

**Comment by Fxxk-XueXiQiangGuo** [comment]
Fuck学习强国 使用的 Electron 开发框架在 Windows 上仅支持 Windows 7 及以上，或者 Windows Server 2008 R2 及以上（二者使用相同的内核），所以没有办法解决，还是推荐您升级系统。

**Comment by zhangziran** [comment]
> 根据谷歌结果表示是您的系统缺少该文件，我作为一个闲人在此推荐您重装完整版的系统并打上所有补丁。
> 如果重装完整版系统并打好所有补丁也还有这个问题的话，推荐您升级系统。
> 什么？不能升级系统？那没救了，还请另请高明



> 根据谷歌结果表示是您的系统缺少该文件，我作为一个闲人在此推荐您重装完整版的系统并打上所有补丁。
> 如果重装完整版系统并打好所有补丁也还有这个问题的话，推荐您升级系统。
> 什么？不能升级系统？那没救了，还请另请高明

哈哈，首先非常感谢你的热心帮助。但是该类型问题大多是由于不兼容。。。。就算我放进去这文件还会缺其他的。另外作者已经回复了。

**Comment by zhangziran** [comment]
> Fuck学习强国 使用的 Electron 框架在 Windows 上仅支持 Windows 7 及以上，或者 Windows Server 2008 R2 及以上（二者使用相同的内核），所以没有办法解决，还是推荐您升级系统。

感谢给予解答。

**Comment by AngelFalse** [comment]
> 另请高明

**我说另请高明吧，我实在也不是谦虚。**
