### ISSUE TITLE
早该管管了

### ISSUE THREAD

**Issue by remrait** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#80]
github上充斥着这类反党，反政府，反国家，反革命，反社会主义，反华，反人类的仓库，提供ssr, v2ray, lantern等违法访问youtube、pornhub、中国数字时代、自由亚洲、美国之声等反动网站的软件，宣传一中各表、新疆集中营、监控数据泄露、709律师、镇压六四、迫害基督教、巴拿马文件、佳士工运、非洲猪瘟、假疫苗、鸿茅药酒、豆腐渣工程、社会信用系统、蓝金黄、监狱网评员、低人权优势等谣言，以及普世价值、新闻自由、司法独立、公民权利、公民思想、权贵资产阶级、党的历史错误等反动思想，还利用小熊维尼、庆丰包子、小学博士、画像泼墨、符文印章、金科绿玉、颐使气指、岿然不动、萨格尔王等手段抹黑我国最高领导人。
最严重的是它忽悠大量中国的爱国程序员向该网站上传代码，并且提供后门，让境外反动势力访问代码，盗窃我国的合法知识产权。它还使用英语界面，从语言上对我国爱国的程序员进行渗透，令英语差的程序员难以进入行业，也就是扶植英语能力强的买办代理人，利用英语这门语言传递反华思想，最终实现对我国高新技术领域的掌控。
并且github大量提供为华为的竞争对手所利用的代码，华为是中国的骄傲，反对华为就是反对共产党，反对习近平。特别是它为台湾企业提供大量的代码，其台独之心昭然若揭。资敌之罪当诛九族，必须依法治国，惩罚github的叛国行为。
我们要坚决打击这种邪恶的行为，弘扬爱国主义精神，拒绝使用github提交代码，自主创新建立符合中国特色社会主义的代码仓库，所有的代码向政府提交审核，政府审核过后再提供下载和运行，实现先审后跑。政府也不应再对邪恶的西方势力坐实不管，当机立断，封禁github及其所属的微软公司，宣布其windows产品非法，并在全国推广国产系统，对每个程序都实行先审后执行，并将使用windows的人打成现行反革命，诛杀九族。

**Comment by kylezhe** [comment]
这是一枚傻逼吗？

**Comment by MagShadow** [comment]
> 这是一枚傻逼吗？

你怕不是看不懂什么是反串黑什么是真傻逼吧2333333

**Comment by AntiMoron** [comment]
@kylezhe 我发现你这个人很没娱乐精神呢？也太可爱了

**Comment by rmctJ** [comment]
这个算是低级红还是算高级黑

**Comment by csiq123** [comment]
差点就拿意大利炮轰死你，你怕不怕？

**Comment by wenguonideshou** [comment]
好 支持 威武 有希望了
