### ISSUE TITLE
转发省委宣传部通知

### ISSUE THREAD

**Issue by hiplon** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#82]
接省委宣传部通知： 目前中宣部已会同中央网信办、公安部对积分代刷非法网站进行严格处置。目前已封堵相关非法网站，严格处置相关责任主体，下一步网信和公安部门会加强网上督察，加强对积分代刷非法网站和平台的排查和打击。同时在技术层面抓紧上线积分反作弊策略，将在手机客户端“积分说明”中增加特别说明项，一旦检测到使用刷分软件获取学习积分现象，该用户所有学习积分全部清零；如果该用户被检测到第二次使用刷分软件获取学习积分情况，将被取消登陆资格。

**Comment by hiplon** [comment]
善意提醒而已

**Comment by wenfeng0218** [comment]
看到了 多谢提醒。但我看这个所谓的刷分实现的原理就是用js脚本自动地点击网页中的链接、下拉网页。应该还好，不是那种外挂啊、代码注入啊、篡改网络数据包啊之类的。

**Comment by hiplon** [comment]
@wenfeng0218 其实严格来说只要不是人手去学习就应该当作是刷分，但是至于能不能侦测行为出来，就看学习那边的IT guy有没有这个技术啦。不过也不难，脚本的行为动作和真人的动作应该还是比较容易区分出来得，特别是都用刷分的账户的动作肯定很一致。

**Comment by CT-ABT** [comment]
> @wenfeng0218 其实严格来说只要不是人手去学习就应该当作是刷分，但是至于能不能侦测行为出来，就看学习那边的 IT guy 有没有这个技术啦。不过也不难，脚本的行为动作和真人的动作应该还是比较容易区分出来得，特别是都用刷分的账户的动作肯定很一致。

把操作的时间间隔给 randomise 一下就是了（估计已经有了？估计这是本来设置？）。再不行可以加入一些模拟人工的操作。

**Comment by CT-ABT** [comment]
> @wenfeng0218 其实严格来说只要不是人手去学习就应该当作是刷分，但是至于能不能侦测行为出来，就看学习那边的 IT guy 有没有这个技术啦。不过也不难，脚本的行为动作和真人的动作应该还是比较容易区分出来得，特别是都用刷分的账户的动作肯定很一致。

把操作的时间间隔给 randomise 一下就是了（估计已经有了？估计这是本来设置？）。再不行可以加入一些模拟人工的操作。

**Comment by kloudmuka** [comment]
公务员系统里面用来吓唬基层的，网信没空理这些屁事情
