### ISSUE TITLE
建议把F-word改为Love

### ISSUE THREAD

**Issue by AntiMoron** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#85]
如题，这样我才敢用你的功能。

**Comment by mdevc** [comment]
你真的love的话，下载了重命名或者fork了改了都行的

**Comment by wenfeng0218** [comment]
我想起来看过台湾的一档节目《情趣用品大公开》。
男主持问女主持：「你知道情趣用品在大陆叫做什么？叫做夫妻保健用品。你看人家说的人模人样，结果还不都是一样！」

**Comment by n3uz** [comment]
学习使我快乐。学习使我快乐。学习使我快乐。

**Comment by meterXu** [comment]
我爱学习，我爱学习，我爱学习

**Comment by AngelFalse** [comment]
说得专业点，下次把f-word换成[EXPLETIVE]如何( ͡° ͜ʖ ͡°)
或者说，
下图所指的词汇：
![image](https://user-images.githubusercontent.com/28922095/54084042-c7d71e80-4366-11e9-9147-57c76555197d.png)
2333333

**Comment by meterXu** [comment]
666

**Comment by iZiwer** [comment]
我爱学习..... 我爱学习.....
