### ISSUE TITLE
有人梦想做富翁，有人梦想做明星，更多的人梦想做盖世太保和红卫兵。

### ISSUE THREAD

**Issue by wenfeng0218** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#86]
有人梦想做富翁，有人梦想做明星，
更多的人梦想做盖世太保和红卫兵。

**Comment by wenfeng0218** [comment]
就在上个月。

2月21日的中国人：国产之光，中国游戏的骄傲！
2月23日的中国人：台独游戏，跟中国没有关系！

**Comment by AntiMoron** [comment]
养了条狗，过来喂肉给它吃，喂完把人咬了。大铁棍抡死。有什么毛病？

**Comment by AntiMoron** [comment]
说话不要只讲后果不讲前因、这才是智商正常人。

**Comment by wenfeng0218** [comment]
中国人感情被伤害的频率比性生活还要高。

**Comment by Lollijinkun** [comment]
难道你的意思是别人给了一坨屎，我他么还得忍着给吃了？台巴子？

**Comment by zyc-ai** [comment]
> 就在上个月。
> 
> 2月21日的中国人：国产之光，中国游戏的骄傲！
> 2月23日的中国人：台独游戏，跟中国没有关系！

“国产之光，中国游戏的骄傲”似乎是行政院副院长陈其迈说的？第二个似乎不能查到可考的来源。看语气也不像是中国人会说的话。
