### ISSUE TITLE
咿～这样是指不用学了吗？

### ISSUE THREAD

**Issue by elleys** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#88]
按照#82 

>目前中宣部已会同中央网信办、公安部对积分代刷非法网站进行严格处置。目前已封堵相关非法网站，严格处置相关责任主体，下一步网信和公安部门会加强网上督察，加强对积分代刷非法网站和平台的排查和打击。同时在技术层面抓紧上线积分反作弊策略，将在手机客户端“积分说明”中增加特别说明项，一旦检测到使用刷分软件获取学习积分现象，该用户所有学习积分全部清零；如果该用户被检测到第二次使用刷分软件获取学习积分情况，将被取消登陆资格。

其中
> 如果该用户被检测到第二次使用刷分软件获取学习积分情况，将被取消登陆资格。

咿～这样是指不用学了吗？

虽然个人觉得强国里面某些文章和高校mooc很不错啊，还有电影可以看，其实要不强制学习还是一个很好的新闻来源补充。

但是宣传部发出的要求一个月要有一千分，纳入意识形态考核？，不达标取消评先资格，活生生把一个好东西变成人人厌恶的东西。如果按照一天六十六分来算，最少需要五十二分钟，求问如何在不影响项目ddl的情况下刷满这么多分，一周九九六已经要命啦好不好？

请看到举报过来的宣传部的pm先管管各个地方行不行。

**Comment by yiding-he** [comment]
你说的电影文章新闻那些东西别地方又不是没有，特别是新闻，全国通稿那个网站都一样。不能用没什么可惜的。

**Comment by elleys** [comment]
> 你说的电影文章新闻那些东西别地方又不是没有，特别是新闻，全国通稿哪个网站都一样。不能用没什么可惜的。

就是我觉得这个使用协议写得。。。按照逻辑，不是反而让有的不想学得人有理由不学啦吗～～
>不知道干了什么莫名其妙不能登陆啦

**Comment by lasidexiaohai** [comment]
辅助每天只能31分？
