### ISSUE TITLE
鲁迅-「聪明人与傻子与奴才」

### ISSUE THREAD

**Issue by KusakaMirai** [fuck-xuexiqiangguo/Fuck-XueXiQiangGuo#97]
奴才总不过是寻人诉苦。只要这样，也只能这样。有一日，他遇到一个聪明人。

“先生！”他悲哀地说，眼泪联成一线，就从眼角上直流下来。“你知道的。我所过的简直不是人的生活。吃的是一天未必有一餐，这一餐又不过是高粱皮，连猪狗都不要吃的，尚且只有一小碗……”

“这实在令人同情。”聪明人也惨然⑴说。

“可不是么！”他高兴了。“可是做工是昼夜无休息的：清早担水晚烧饭，上午跑街夜磨面，晴洗衣裳雨张伞，冬烧汽炉夏打扇。半夜要煨银耳，侍候主人耍钱；头钱从来没分，有时还挨皮鞭……。”

“唉唉……”聪明人叹息着，眼圈有些发红，似乎要下泪。

“先生！我这样是敷衍不下去的。我总得另外想法子。可是什么法子呢？……”

“我想，你总会好起来……”

“是么？但愿如此。可是我对先生诉了冤苦，又得你的同情和慰安，已经舒坦得不少了。可见天理没有灭绝……”

但是，不几日，他又不平起来了，仍然寻人去诉苦。

“先生！”他流着眼泪说，“你知道的。我住的简直比猪窠还不如。主人并不将我当人；他对他的叭儿狗还要好到几万倍……”

“混帐！”那人大叫起来，使他吃惊了。那人是一个傻子。

“先生，我住的只是一间破小屋，又湿，又阴，满是臭虫，睡下去就咬得真可以。秽气冲着鼻子，四面又没有一个窗……。”

“你不会要你的主人开一个窗的么？”

“这怎么行？……”

“那么，你带我去看去！”

傻子跟奴才到他屋外，动手就砸那泥墙。

“先生！你干什么？”他大惊地说。

“我给你打开一个窗洞来。”

“这不行！主人要骂的！”

“管他呢！”他仍然砸。

“人来呀！强盗在毁咱们的屋子了！快来呀！迟一点可要打出窟窿来了！……”他哭嚷着，在地上团团地打滚。

一群奴才都出来了，将傻子赶走。

听到了喊声，慢慢地最后出来的是主人。

“有强盗要来毁咱们的屋子，我首先叫喊起来，大家一同把他赶走了。”他恭敬而得胜地说。

“你不错。”主人这样夸奖他。

这一天就来了许多慰问的人，聪明人也在内。

“先生。这回因为我有功，主人夸奖了我了。你先前说我总会好起来，实在是有先见之明……。”他大有希望似的高兴地说。

“可不是么……”聪明人也代为高兴似的回答他。

**Comment by KusakaMirai** [comment]
1925年12月26日

**Comment by jvbaocn** [comment]
有些人对这个寓言理解不透，实际上我党领导的我们国家才是砸墙开窗的！

像五眼联盟还有日本韩国事事追随美国，美国让他们咬我们中国他们就咬，美国才尚他们点饭吃。他们不敢造核武器不敢触犯美国，他们没有主权，就是些奴才国家！

而我党领导着我国人民，造出了核武器，我国人民站了起了！我们就可以敢怼美国！！

现在我国把这些宝贵经验总结在“学习强国”app中，要求公职人员，学校学生等我国未来的栋梁学习，居然还有人看不惯，只能说那些人理解力低下。

**Comment by AntiMoron** [comment]
台湾政治人总是喜欢耍嘴皮子搞小聪明。除此之外搞不出任何花样儿了。奴才们表示很羡慕小聪明

**Comment by wenfeng0218** [comment]
> 有些人对这个寓言理解不透，实际上我党领导的我们国家才是砸墙开窗的！
> 
> 像五眼联盟还有日本韩国事事追随美国，美国让他们咬我们中国他们就咬，美国才尚他们点饭吃。他们不敢造核武器不敢触犯美国，他们没有主权，就是些奴才国家！
> 
> 而我党领导着我国人民，造出了核武器，我国人民站了起了！我们砸掉了美国构筑的科技壁垒墙，我们就可以敢怼美国！！
> 
> 现在我国把这些宝贵经验总结在“学习强国”app中，要求公职人员，学校学生等我国未来的栋梁学习，居然还有人看不惯，只能说那些人理解力低下。

欧美国家的公民：根据社会契约论，国家的一切权利属于我们公民所有。我们每个人上交一部分权力形成公权力，组成政府，代表我们管理这个国家。这个政府是民选、民治、民享的民主政府。我们每个人按照法律的规定给政府交纳税款，我们就是纳税人。所以政府有法定义务保护我们的生命和财产安全、保护我们的合法权益、保护我们不受战乱、病痛之苦。我爱我的国家，但是警惕我的政府。法律是可靠的，人是靠不住的。我们不会支持一个不容许人们提反对意见的政府，这样的政府我们要把它赶走。我们是国家的主人，政府只是仆人。主人是不可能更换的，但是仆人可以经常换。

古代中国的子民：皇恩浩荡！谢主隆恩！微臣世受皇恩，定当肝脑涂地，以身殉国！

现代中国的五毛：我党领导着我国人民，造出了核武器，我国人民站了起来！我们砸掉了美国构筑的科技壁垒墙，我们就可以敢怼美国！！我们吃的饭是共产党给的！我们穿的衣是共产党给的！我们住的房子是共产党给的！我们可以避免沦为美国的奴隶也是拜共产党所赐！共产党发布学习强国App就是给我们传授先进的科学文化知识！提高我们的专业技能！你们这群卖国贼翻墙出来找刷分软件，还对共产党有意见，真是良心大大的坏了！你们真的很该死！我要去举报把GitHub封掉！以后所有的东西在共产党的领导下我们国家自己造出来！我要把你们这群卖国贼抓起来判死刑！

**Comment by CoderYellow** [comment]
冷嘲热讽，还自以为很聪明。鲁迅先生抨击的恰恰是你们这些洋奴，资产阶级所谓的民主才是居高施舍，掩盖阶级矛盾。相反的是，共产党才是最革命，最先进的，代表广大无产阶级的力量。“从来没有什么救世主”，这种革命精神刻进了每一个真正党员的骨子里。
